### PR TITLE
Dark elf + new Prison texture

### PR DESCRIPTION
**Pull request by Danimal696**
Still missing normal elf and new ranged weapons

### CODE REVIEW

**Comment by Bertram25** [comment]
Whoohoo, can't wait to see him in game. :D

**Comment by hwoarangmy** [comment]
Cool. I will try that tonight ^^

@Danimal696 Note that you can gather all materials in one file to avoid having several files for the same model

**Comment by hwoarangmy** [comment]
works well

**Comment by Danimal696** [comment]
size it 0.11 for better results, the walk and attack speed also needs to be adjusted

**Comment by hwoarangmy** [comment]
Note that there will be a problem of synchronization when we will have the proper missile. The architecture makes that the missile is thrown at animation start which is not exactly what will be expected from what I've seen in the animation.

**Comment by Danimal696** [comment]
i can cut the animation to jump at shoot point from the start, should i?

**Comment by hwoarangmy** [comment]
I think it would be better. To say that they have a weapon ready for firing and the warmup would be used to reload.

**Comment by Danimal696** [comment]
okay

**Pull request merged**
