### PR TITLE
Made the resource manager retrieve the OD installation path at load time...

### PR DESCRIPTION
**Pull request by Bertram25**
I also made it so the ./resources.cfg file is tested first to override the data path to "./",
to still permit developer builds when necessary

Works fine for me but needs testing though to make sure.

Should help with #58

### CODE REVIEW

**Comment by Bertram25** [comment]
Should be almost done for #25 , too.

**Comment by akien-mga** [comment]
As far as I understand it this PR fixes most of #57. I'll test whether the OpenDungeons.bin binary can be run both from the source directory and from any other directory when data is located in OPENDUNGEONS_DATA_PATH; if it works, fixing #57 simply means dropping the IF here: https://github.com/OpenDungeons/OpenDungeons/blob/development/CMakeLists.txt#L10-L14

Though we might want to define PROJECT_BINARY_NAME in lower-case on Unix, and then use PROJECT_BINARY_NAME to define the default installation path for the data.

**Comment by akien-mga** [comment]
There is still an issue with loading the levels/ and scripts/ directories it seems (when the data is installed system wide). See the discussion about it on https://github.com/OpenDungeons/OpenDungeons/issues/58#issuecomment-51886016

**Comment by oyvindln** [comment]
Ah, I had just made a patch removing dirent, now it's going to be a mess to merge :/

**Comment by Bertram25** [comment]
> There is still an issue with loading the levels/ and scripts/ directories it seems (when the data is installed system wide). See the discussion about it on #58 (comment)

@akien-mga Ok, I'll have a look.

> Ah, I had just made a patch removing dirent, now it's going to be a mess to merge :/

@oyvindln  Feel free to create it and we'll merge yours after review first. I'll rebase afterwards. :)

**Comment by Bertram25** [comment]
Own TODO so far:
- [x] Use boost::filesystem instead of custom file exist code.
- [x] Use boost filesystem also for the createDirIfNotExist() function, too, if @oyvindln hasn't already done it.
- [x] Use a lower-cased project binary name and use it when setting the installation path.
- [x] Make sure to use the resource path prefix when searching for music, sounds, levels, and scripts.

Feel free to point out other blockers. :)
Once all this is done and merged, I'll deal with XDG stuff ( #25 ). Akien will then be able to drop the launch script (AFAIK there was one, right?) and .bin in the binary name.

**Comment by Bertram25** [comment]
@akien-mga @hwoarangmy @oyvindln  I should be done now according to the TODO above. Feel free to point me any errors. :)

**Comment by Bertram25** [comment]
Ah, to get a lowercase binary and installation path, you will need to clear your cmake cache.

**Comment by Bertram25** [comment]
> Just to be clear, this applies at runtime only? So if there is data in "./" when building the source, it won't remove the OD_DATA_PATH from the path? But it will do temporarily when running the game?

Yes. :) Useful for us, poor devs. ;)

**Comment by Bertram25** [comment]
Ah, btw. Don't start ./OpenDungeons.bin once build, now it is ./opendungeons.bin
I fell on that one a few times before removing the old binary. XD

**Comment by Bertram25** [comment]
I'll stop the commit frenzy. See ya later guys. :)

**Comment by akien-mga** [comment]
Code-wise it's looking good (as far as I can understand the code I read, that is :-p), apart from the line ending issue with scripts/console.as (another proof that we should take care of #53, at least for our own files, maybe not for the AS upstream files that need updating).

I'll test it live now.

**Comment by akien-mga** [comment]
This works GREAT :-D

@hwoarangmy, @oyvindln To test the system wide installation on Linux, since there are no "make install" instructions yet (I'll be on it once this gets merged), you can put all the relevant data manually in /usr/local/share/games/opendungeons (or do a symbolic link to your source directory), and then move the opendungeons.bin binary anywhere, and run it. It should work :-)

**Comment by hwoarangmy** [comment]
I won't be able to test until tonight. If someone test and sees it is ok, no need to wait for me before merging :)

**Comment by akien-mga** [comment]
@Bertram25 Once this gets merged, I think you might be able to merge the whole development branch in stable and do a Windows release (if you want to).

**Comment by Bertram25** [comment]
> @Bertram25 Once this gets merged, I think you might be able to merge the whole development branch in stable and do a Windows release (if you want to).

Ok, I'll do it. :) But before that, I need to take care of a certain commit :crying_cat_face: >:}]

**Comment by Bertram25** [comment]
@hwoarangmy @akien-mga Sunny day, I might not do much before evening. ;)

**Comment by Bertram25** [comment]
@akien-mga as script line ending commit fixed. :)

**Comment by hwoarangmy** [comment]
It's ok for me on windows/MinGW. I will let someone else using linux merge that as I think it needs more test with this OS.

**Comment by Bertram25** [comment]
Good to hear it's ok on windows. :) I'll let @akien-mga merge once/if he's ok.

**Pull request merged**
