### PR TITLE
Clear up the message and chat widget at mode destruction.

### PR DESCRIPTION
**Pull request by Bertram25**
Following @oyvindln's advice.

This is fixing clearing the chat log for instance when opening/closing the console.

Not an ideal patch, but it's ok for the release.

### CODE REVIEW

**Comment by akien-mga** [comment]
Changes look fine IMO.

**Comment by hwoarangmy** [comment]
@Bertram25 When this PR will be in, could you please create the 0.5.0 official branch so that we can start integrating @oyvindln PR ?

**Comment by Bertram25** [comment]
> @Bertram25 When this PR will be in, could you please create the 0.5.0 official branch so that we can start integrating @oyvindln PR ?

Sure. :) Once this one is in, I'll push this to the stable branch and create a 0.5 branch there. :)
I'll also tag the 0.5 branch commit with 0.5.0RC1 and tell you when it's done.

**Comment by akien-mga** [comment]
Works fine :)

**Comment by Bertram25** [comment]
Cool, I push to master asap.

**Pull request merged**
