### PR TITLE
Abstracted logmanager for unit tests

### PR DESCRIPTION
**Pull request by oyvindln**
Made logmanager abstract
Started adding unit test for creaturedefinition

### CODE REVIEW

**Comment by hwoarangmy** [comment]
The code seems good to me. The requested changes can be done later if you prefer. Just a few questions to answer ^^

**Comment by oyvindln** [comment]
Added some fixes. I will fixe the merge conflict tomorrow.
Also, I found that the compiler happily accepts operator>> on a forward-declared pointer type, which caused me a bit of confusion. We should be wary of using and defining operator>> directly on pointers, and probably prefer references instead.

**Comment by hwoarangmy** [comment]
Code seems good to me. I will test tonight with windows ^^

**Comment by hwoarangmy** [comment]
Testing right now

**Comment by hwoarangmy** [comment]
Works well. I merge

**Pull request merged**
