### PR TITLE
Goblin updated with normals Fixes #503

### LINKED ISSUE #503: The troll bed material should be tweaked to use normals.
As seen here: http://forum.freegamedev.net/viewtopic.php?p=62443#p62443

For now, with normals applied, the bed woods are looking metallic shiny.
Work on the different light values should be done to fix that and finally import the models with normals support.

### PR DESCRIPTION
**Pull request by Danimal696**

### CODE REVIEW

**Comment by Danimal696** [comment]
ill upload them as i update the models

**Comment by akien-mga** [comment]
> ill upload them as i update the models

Great! :) Tell us when you're done with the first batch.

**Comment by Danimal696** [comment]
Okay, its best to have this pull open for a bit

**Comment by Bertram25** [comment]
In any case, even if we merge, you can still push other commits and reopen a new PR. :)

**Comment by Bertram25** [comment]
OMG, I can't wait to test all that :D

**Comment by Danimal696** [comment]
its looking better now

**Comment by Danimal696** [comment]
you can merge for now, ill make a new batch this weekend

**Comment by Bertram25** [comment]
With normals, the forge and traininghall ground textures are gorgeous :D I'll have a look at the creatures now.

**Comment by Bertram25** [comment]
To me it's working great. Some test on nvidia/proprietary drivers may be needed, though.

**Comment by akien-mga** [comment]
> To me it's working great. Some test on nvidia/proprietary drivers may be needed, though.

I'm on it :)

**Comment by akien-mga** [comment]
I see no difference with intel and nvidia, but I do see one good old issue coming back:
od-dan-intel

Yep, #133 :-)
@Danimal696 did not touch the wall models, so there's definitely something wrong in the way we render normals.

**Comment by hwoarangmy** [comment]
@akien-mga For me, this issue has never been fixed ;-)
Could you try to edit the map and add rock tiles ? On my computer, the dirt tiles that also exist in the same level as rock tiles are not displayed like that

**Comment by akien-mga** [comment]
> For me, this issue has never been fixed ;-)

Oh :-o I didn't know.
Adding rock tiles doesn't fix the issue, even in the editor I get broken dirt tiles next to the rock tiles. I also tested the edited level in skirmish mode, same issue.
od-strange-dirt-tiles

**Comment by Danimal696** [comment]
i also noticed one thing, normals are not applied onto floor tiles, no doubt the odd pass system is the culprit

**Comment by hwoarangmy** [comment]
> I also tested the edited level in skirmish mode, same issue

In your screenshot, the dirt and rock tiles are different (we can see a north oriented rock tile and a single one while the buggy dirt tiles are west, east and horizontal). Could you please try to have the exact same tiles (for example, 2 tiles dirt and rock with water around) ?

**Comment by akien-mga** [comment]
> Could you please try to have the exact same tiles (for example, 2 tiles dirt and rock with water around) ?

I'm not 100% sure what you mean. From what I understood you think that if a rock tile is present with a certain orientation, then the dirt tiles with the same orientation won't have the bug?
From my tests I can't really find a reliable rule :-/

**Comment by hwoarangmy** [comment]
> you think that if a rock tile is present with a certain orientation, then the dirt tiles with the same orientation won't have the bug?

That's what I've seen so far. For example, If I only add a 1x1 rock tile to the 2v2 skirmish map, the 1v1 dirt tiles will be correctly displayed while the other dirt tiles will not. Note that I've tried to add them at first (0x0) or at last (50x50) and it doesn't change anything. So, it seems like it is not the loading order that matters.

**Comment by Bertram25** [comment]
I guess we need a minimal example level. This way, we could hunt down the way the tiles are created/refreshed, and surely obtain more info on the culprit code and/or material, IMHO.
Does this means creating a 2x1 level would be enough for the bug example level?

**Comment by Bertram25** [comment]
Great, more normals! :D 

Btw, it seems you removed the normal for the bookcase but didn't remove the corresponding texture (which is white, btw.). Is that "normal"? ;)

**Comment by Bertram25** [comment]
I tested them, works great. The game looks gorgeous. (Just start 0.4.9 and you should have a shock when seeing the changes...) Good to be merged IMHO. Please test and do so if it's ok.

**Comment by Danimal696** [comment]
normals go a long way, and i barely started on creatures, ill erase the white texture and kill some indentations on kingthcoffin material

**Comment by hwoarangmy** [comment]
That's also good to me. Should we merge even with the bug that @akien-mga saw ?
@Danimal696 Do you see a reason why there could be this behaviour ?

**Comment by Bertram25** [comment]
> That's also good to me. Should we merge even with the bug that @akien-mga saw ?

EDIT: Depends, but I think yes. (In yes, I think we should merge.)
Is the issue here before this PR? IMO it is, as it is the case for me, too (before the PR).
In that case, this is not a regression due to the PR but rather to the way passes are handled by Ogre, and we'll have to use a minimal example to track down the problem.
Last word is on @akien-mga 's shoulders, though. ;)

**Comment by oyvindln** [comment]
> Is the issue here before this PR? IMO it is, as it is the case for me, too (before the PR).

I also have this issue (without this PR), so it's something wrong in the code, but I don't know what. The affected tiles look like they have lighting applied more than once or something.

**Comment by Bertram25** [comment]
>  The affected tiles look like they have lighting applied more than once or something.

Yeah, that's also my impression but it might be more twisted.

**Comment by hwoarangmy** [comment]
ok. Then, everybody have the bug. I thought I was the only one with this bug. Maybe not after all ^^
In any case, that's not a regression from this PR so I merge

**Pull request merged**
