### PR TITLE
Add initial release notes for 0.6.0 + misc adjustments

### PR DESCRIPTION
**Pull request by akien-mga**
Note that the release notes are a bit more exhaustive than #540, as I went through the actual issues that were closed against the 0.6.0 milestone, and as usual, I found some gems that @hwoarangmy coded by surprise and that we forgot to list in the release issue ;-)

### CODE REVIEW

**Comment by akien-mga** [comment]
@Danimal696 Do we still use Claimedwall.material and ClaimedWall*.png, or have those been replaced by the DCW*.material and DungeonClaimedWall*.png files?

**Comment by Danimal696** [comment]
only if we want to keep the legacy walls around, those wont be necesary if they are erased from everywhere

**Comment by akien-mga** [comment]
> only if we want to keep the legacy walls around, those wont be necesary if they are erased from everywhere

But I think it's no longer the legacy walls:
https://github.com/OpenDungeons/OpenDungeons/blob/development/materials/textures/ClaimedWall.png

**Comment by Bertram25** [comment]
@akien-mga 

> Fix misspellings found by codespell using the same procedure as described in #685

I'll be beaten for such arrogance I know ;), but could you add that small "procedure" to a new release management" page. I propose we add there what needs not to be forgotten when releasing, little by little.

**Comment by akien-mga** [comment]
@Bertram25 I force-pushed a change to fix the commit log of e498c86 (and fix the two wrong # symbols used instead of *). Force-pushes are not a good practice, but it's cleaner with a correct log IMO :)

**Comment by akien-mga** [comment]
> > Fix misspellings found by codespell using the same procedure as described in #685
> 
> I'll be beaten for such arrogance I know ;), but could you add that small "procedure" to a new release management" page. I propose we add there what needs not to be forgotten when releasing, little by little.

Good idea, I'll do that.

**Comment by Bertram25** [comment]
All fine I merge.

**Pull request merged**
