### PR TITLE
GUI update.

### PR DESCRIPTION
**Pull request by Bertram25**
This is in preparation of the addition of the research tree and the settings menu.

This part does only change the GUI part, no cpp was changed.
The logic part will be part of another PR.

Part of #3 
Part of #517

### CODE REVIEW

**Comment by Bertram25** [comment]
I'll add code to make the options menu open instead of the settings window. I'll add it there if I have the time but feel free to merge if it's ok for you guys.

**Comment by akien-mga** [comment]
Hey, is that OpenDungeons 0.6.0 already? This GUI looks gorgeous :-D

**Comment by Bertram25** [comment]
Thanks :)

**Comment by akien-mga** [comment]
Just one thing: the options window can be shown with F10, but it can't be close with F10. It would be nice to have this implemented, as it is done currently for the help (F1) and objectives (F3).
When you add the research screen, the F4 key should also have a toggle behaviour IMO.

**Comment by Bertram25** [comment]
Yeah, I'm on it at this very moment in fact. :)

**Comment by Bertram25** [comment]
I added the Game Options Menu. The available buttons should be working, while the settings window should still not be functional.
I'll have a go at doing the same for the editor.
Then, I'll start working on the research tree. :)

**Comment by Bertram25** [comment]
Ah, of course, if you have feed-back concerning usability or anything, just tell.  Let's adapt until it feels right.

**Comment by hwoarangmy** [comment]
I like the new GUI. The next release will really rock ^^

**Comment by hwoarangmy** [comment]
I've just tested and it seems that in editor mode, the option menu doesn't popup (by pressing F10 or the button)

**Comment by Bertram25** [comment]
> I've just tested and it seems that in editor mode, the option menu doesn't popup (by pressing F10 or the button)

Yeah, that's almost done.

**Comment by Bertram25** [comment]
For the record, I'd like to add stuff little by little, and not hide the buttons if possible. If we reach a release while I'm not finished, I'll hide them back at that moment.

**Comment by akien-mga** [comment]
Nice! The only issue (or better said, "yet unimplemented feature that you are probably aware of, but I tell it nonetheless") I found is that the "Quit game" button in the options menu does not bring up the "quit" dialog.

**Comment by Bertram25** [comment]
>  I found is that the "Quit game" button in the options menu does not bring up the "quit" dialog.

ah ? It should, I'll have a look.

**Comment by Bertram25** [comment]
I just tested, the exit pop-up does show in the game mode. Did you speak about the editor mode?

**Comment by akien-mga** [comment]
> I just tested, the exit pop-up does show in the game mode. Did you speak about the editor mode?

Indeed, I just tested again it works fine. I was speaking about the game mode, but either I'm misclicked, or I hit some corner case where the GUI is not responding properly when you've clicked on all buttons in random order... I couldn't reproduce any issue with the Quit game button, so let's assume it's a PEBKAC :)

**Comment by Bertram25** [comment]
> Indeed, I just tested again it works fine. I was speaking about the game mode, but either I'm misclicked, or I hit some corner case where the GUI is not responding properly when you've clicked on all buttons in random order... I couldn't reproduce any issue with the Quit game button, so let's assume it's a PEBKAC :)

Now you may have catched something here. I've noticed several times the quit window being show at game start for no reasons. So there is definitely something but it's not linked to this PR. Maybe in the popupExit() function or the way it is called?

**Comment by Bertram25** [comment]
Allright. Evil plan part II is online. If you're fine with this PR, feel free to merge. :)

**Comment by Bertram25** [comment]
> I like the new GUI. The next release will really rock ^^

Thanks a lot :) Feel free to point out anything, even it seems obvious just as @akien-mga did.
We're one step closer from having a complete GUI. :)
Next step: The research tree.

**Comment by akien-mga** [comment]
Great! At least with have a visible "Save level" button, I guess early modders will have a hard time finding the F8 key on 0.4.9 ;-)
For me this is really good stuff, I merge.

**Pull request merged**
