### PR TITLE
Display chat/event messages in editor mode

### LINKED ISSUE #647: Editor does not show notification when saving level
I guess it's a regression due to @Bertram25's work on the game mode chat/notifications, maybe the editor hasn't been completely adapted to the new system yet.

### PR DESCRIPTION
**Pull request by hwoarangmy**
used root window in the editor and gamemode instead of calling the gui to get the window
fixes #647

### CODE REVIEW

**Comment by akien-mga** [comment]
After a quick test, this works fine. I'll let @Bertram25 or @oyvindln review the code changes :)

**Comment by Bertram25** [comment]
The code looks good while since now chat messages stay forever, there is no more need to store the chat messages in the queue.

**Comment by Bertram25** [comment]
I should have removed that myself sorry.

**Comment by Bertram25** [comment]
Tested. Good to merge IMHO.

**Comment by akien-mga** [comment]
Merging then.

**Pull request merged**
