### PR TITLE
Simplified the way Chickens are handled in the hatchery

### LINKED ISSUE #216: Redo chicken logic

### PR DESCRIPTION
**Pull request by hwoarangmy**
- Chickens can be picked up
- Chickens can be dropped on claimed tiles
- Chickens leave hatchery only when dropped outside
- Chickens can live 30 turns outside the hatchery. After that, they die
- Only creatures using the hatchery will consider eating a chicken in the hatchery
- A creature not using the hatchery will consider eating chickens outside the hatchery only. Any creature, even ennemy can eat a free chicken
  fixes #216

### CODE REVIEW

**Comment by Danimal696** [comment]
Quite cool! will they also recover some health to the creature eating them?

**Comment by hwoarangmy** [comment]
No, they just feed creatures (decrease hunger). But we can make them heal if you want. BTW, now that you talk about it, it could be nice to have this in  a config file :
- How much hunger decreases per eaten chicken
- How many hp recovered per eaten chicken
- Chicken spawn rate (at the moment, it doesn't depend on active spots - only max number chickens depends on active spots)

**Comment by Bertram25** [comment]
Ok, there definitely need to be a config/rooms.cfg file, IMHO.
I'll open an issue. :) (Seems like I'll be on configuration stuff for some time. ;])

**Comment by Bertram25** [comment]
I've opened #239 
Feel free to comment :)

**Comment by Bertram25** [comment]
> > Quite cool! will they also recover some health to the creature eating them?
> 
> No, they just feed creatures (decrease hunger). But we can make them heal if you want.

Is it actually desired to make chicken restore HP? IMHO, only hunger should be restored, right?

**Comment by hwoarangmy** [comment]
ok. I've already done the change about indentation. It will come with my next PR. As you say, if there is nothing else, I would also prefer to merge this and I will do that at the same time as renaming room objects

**Comment by Bertram25** [comment]
Regression spotted: You can no more build the first treasury tile when you have no gold and no treasury tile. Simply test Scream in the dark and you'll see.

**Comment by Bertram25** [comment]
I've also got this crash exception at random:
opendungeons: /tmp/buildd/ogre-1.9-1.9.0+dfsg1/OgreMain/include/OgreAxisAlignedBox.h:252: void Ogre::AxisAlignedBox::setExtents(const Ogre::Vector3&, const Ogre::Vector3&): Assertion `(min.x <= max.x && min.y <= max.y && min.z <= max.z) && "The minimum corner of the box must be less than or equal to maximum corner"' failed.

Does this speak to someone?

**Comment by hwoarangmy** [comment]
Do you have the callstack ?

**Comment by Bertram25** [comment]
> Do you have the callstack ?

Unfortunately not yet, but I'll retry with gdb asap and try also to bisect it to see whether it's actually your patch causing it. Somehow, I doubt that.

**Comment by Bertram25** [comment]
According to these:
http://www.ogre3d.org/forums/viewtopic.php?f=2&t=47792&start=0
http://www.ogre3d.org/forums/viewtopic.php?f=2&t=48671

The assertion failure can come from either:
- A badly exported model that cause the assertion failure when rescaled.
- Same when its position or direction is set.
- When you scale a model with 0, 0, 0.

Might be the newest models as well. A bisect and some luck will tell. ;)

**Comment by hwoarangmy** [comment]
> Might be the newest models as well. A bisect and some luck will tell. ;)

Have you seen it often ? If yes, as my fork has not the latest models, it could explain why I didn't see this because I've let the game play for a while and saw no crash...

**Comment by hwoarangmy** [comment]
> Regression spotted: You can no more build the first treasury tile when you have no gold and no treasury tile. Simply test Scream in the dark and you'll see.

I've seen why. A wrong copy/paste I didn't see :-(
I've fixed it. Let's wait for more info about the crash and we will see for a patch.

**Comment by Bertram25** [comment]
> Have you seen it often ? If yes, as my fork has not the latest models, it could explain why I didn't see this because I've let the game play for a while and saw no crash...

Each time. The bad news is that I've played with the newest models but without your PR and the game did fine. :S I'll try to give you a bt asap.

**Comment by hwoarangmy** [comment]
ok. Let's hope the bt will tell us more ^^

**Comment by akien-mga** [comment]
> Each time. The bad news is that I've played with the newest models but without your PR and the game did fine. :S I'll try to give you a bt asap.

That's good news IMO. It's always better when we know where a bug originates from :-)

**Comment by Bertram25** [comment]
Computing turn 574Adding rendered object Room_Object_Farm21_219,MeshName=Chicken

During this turn there were 28 calls to GameMap::path().miscUpkeepTime=12697
Server sends newturn=574
Client received turnStarted=574
opendungeons: /tmp/buildd/ogre-1.9-1.9.0+dfsg1/OgreMain/include/OgreAxisAlignedBox.h:252: void Ogre::AxisAlignedBox::setExtents(const Ogre::Vector3&, const Ogre::Vector3&): Assertion `(min.x <= max.x && min.y <= max.y && min.z <= max.z) && "The minimum corner of the box must be less than or equal to maximum corner"' failed.

Bt:

```
(gdb) bt
#0  0x00007ffff3fd5077 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff3fd6458 in __GI_abort () at abort.c:89
#2  0x00007ffff3fce196 in __assert_fail_base (fmt=0x7ffff41048c8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=assertion@entry=0x7ffff7a72728 "(min.x <= max.x && min.y <= max.y && min.z <= max.z) && \"The minimum corner of the box must be less than or equal to maximum corner\"",
    file=file@entry=0x7ffff7a726e0 "/tmp/buildd/ogre-1.9-1.9.0+dfsg1/OgreMain/include/OgreAxisAlignedBox.h", line=line@entry=252,
    function=function@entry=0x7ffff7ab0180 "void Ogre::AxisAlignedBox::setExtents(const Ogre::Vector3&, const Ogre::Vector3&)") at assert.c:92
#3  0x00007ffff3fce242 in __GI___assert_fail (
    assertion=0x7ffff7a72728 "(min.x <= max.x && min.y <= max.y && min.z <= max.z) && \"The minimum corner of the box must be less than or equal to maximum corner\"",
    file=0x7ffff7a726e0 "/tmp/buildd/ogre-1.9-1.9.0+dfsg1/OgreMain/include/OgreAxisAlignedBox.h", line=252,
    function=0x7ffff7ab0180 "void Ogre::AxisAlignedBox::setExtents(const Ogre::Vector3&, const Ogre::Vector3&)") at assert.c:101
#4  0x00007ffff7722d56 in ?? () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#5  0x00007ffff7908d94 in Ogre::MovableObject::getWorldBoundingBox(bool) const () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#6  0x00007fffe7a2cbff in Ogre::OctreeNode::_updateBounds() () from /usr/lib/x86_64-linux-gnu/OGRE-1.9.0/Plugin_OctreeSceneManager.so.1.9.0
#7  0x00007ffff7828e74 in Ogre::Node::_update(bool, bool) () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#8  0x00007ffff77d45f0 in Ogre::SceneNode::_update(bool, bool) () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#9  0x00007ffff7828e74 in Ogre::Node::_update(bool, bool) () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#10 0x00007ffff77d45f0 in Ogre::SceneNode::_update(bool, bool) () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#11 0x00007ffff77a0e99 in Ogre::SceneManager::_updateSceneGraph(Ogre::Camera*) () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#12 0x00007ffff77b63e1 in Ogre::SceneManager::_renderScene(Ogre::Camera*, Ogre::Viewport*, bool) () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#13 0x00007ffff77e3470 in Ogre::Camera::_renderScene(Ogre::Viewport*, bool) () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#14 0x00007ffff79ab2ea in Ogre::RenderTarget::_updateViewport(Ogre::Viewport*, bool) () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#15 0x00007ffff79ab0fb in Ogre::RenderTarget::_updateAutoUpdatedViewports(bool) () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#16 0x00007ffff79aaece in Ogre::RenderTarget::updateImpl() () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#17 0x00007ffff79ab694 in Ogre::RenderTarget::update(bool) () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#18 0x00007ffff792ff7f in Ogre::RenderSystem::_updateAllRenderTargets(bool) () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#19 0x00007ffff7960f4a in Ogre::Root::_updateAllRenderTargets() () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#20 0x00007ffff7961020 in Ogre::Root::renderOneFrame() () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#21 0x00007ffff7961065 in Ogre::Root::startRendering() () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#22 0x000000000058916a in ODApplication::ODApplication (this=0x7fffffffe0a0) at /home/yohann/Projets/opendungeons/source/ODApplication.cpp:124
#23 0x0000000000466052 in main (argc=<optimized out>, argv=<optimized out>) at /home/yohann/Projets/opendungeons/source/main.cpp:82
```

**Comment by Bertram25** [comment]
The common point between all crash is that a chicken is added just before.
I've started the Scream in the Dark level and waited without playing. the crash happened...
(Even if unfortunately, nothing seems to be really useful in the BT)

**Comment by akien-mga** [comment]
The backtrace got us a nice cross-linking in all first 23 issues ;-)

**Comment by Bertram25** [comment]
> The backtrace got us a nice cross-linking in all first 23 issues ;-)

Yeah, now we don't have any choice but to fix them. ;)

**Comment by hwoarangmy** [comment]
I've tried 3 games scream in the dark turn > 2000 doing nothing or building a hatchery and couldn't reproduce the crash :-(
Can you lauch the game with gdb to see if you can get some more information ?

**Comment by Bertram25** [comment]
> I've tried 3 games scream in the dark turn > 2000 doing nothing or building a hatchery and couldn't reproduce the crash :-(
> Can you lauch the game with gdb to see if you can get some more information ?

I'm so sorry I can give more info right now, btw. I really don't want to represent a burden here. :S 

@akien-mga Since you're also on Linux, can you do the test?

**Comment by hwoarangmy** [comment]
> I really don't want to represent a burden here. :S

That's not your fault if you see a bug ;)

**Comment by hwoarangmy** [comment]
I've tried to stash the changes I had in my sources to have the same sources as my repo and test again but I still can't reproduce.
@Bertram25 Have you done something special ? Like picking up creatures, marking tiles, moving the camera, anything ?
Do you have the crash when you do nothing at all, even not moving the camera ?

**Comment by akien-mga** [comment]
I played ~2500 turns on Scream in the dark and could not reproduce the crash either (without doing anything apart from digging a few tiles). I'm now playing Stonekeep Siege "normally" (i.e. digging and creating rooms) to see if it happens.

Edit: After 6000 turns on Stonekeep Siege, no crash.

**Comment by hwoarangmy** [comment]
@Bertram25 From what I've seen in Ogre source, I don't see what we can do in code that could explain this bug. But because the chicken mesh displays warnings, could you try to replace it by another that do not display warnings and see if it changes anything (the easiest way would be to change in ChickenEntity the mesh name - do not forget to change in both constructors) ?

**Comment by Bertram25** [comment]
> ? For me it is set everytime. The first constructor (only one that should be used outside server communication handling, rotation angle is mandatory). The second one (that expects a call to operator >> for ODPacket) will fill the rotation angle in the operator. What makes you think there is a problem with the angle ?

Nothing at all, I'm just pointing out possible causes (/me is a bit running out of options, ony a few ones left. ;])

> @Bertram25 From what I've seen in Ogre source, I don't see what we can do in code that could explain this bug. But because the chicken mesh displays warnings, could you try to replace it by another that do not display warnings and see if it changes anything (the easiest way would be to change in ChickenEntity the mesh name - do not forget to change in both constructors) ?

Yep, I wanted to try that even if I didn't find the time yet. I'll tell you asap. :)

**Comment by hwoarangmy** [comment]
> Yep, I wanted to try that even if I didn't find the time yet. I'll tell you asap. :)

ok, no pb. And if you do reproduce the bug, could you please try to add a log in 
https://github.com/hwoarangmy/OpenDungeons/blob/development/source/RenderManager.cpp#L689
and
https://github.com/hwoarangmy/OpenDungeons/blob/development/source/RenderManager.cpp#L1121
that displays the position vector ?

PS : don't forget to test that the name contains "Farm" to not have a log too full

**Comment by Bertram25** [comment]
Ok, I'm on it. I change the Chicken with the ChickenCoop model and the bug is much more frequent now. I'll give the log asap.

**Comment by Bertram25** [comment]
Got something!!

```
Room object: Room_Object_Farm13_50, mesh: Chicken, fullname: RoomObject_Room_Object_Farm13_50
Degree rotation: Degree(2.4803e-43)
Mesh: Loading Chicken.mesh.
position: Vector3(0, 0, 0)
Room object: Room_Object_Farm14_51, mesh: Chicken, fullname: RoomObject_Room_Object_Farm14_51
Degree rotation: Degree(-nan)
position: Vector3(0, 0, 0)
opendungeons: /tmp/buildd/ogre-1.9-1.9.0+dfsg1/OgreMain/include/OgreAxisAlignedBox.h:252: void Ogre::AxisAlignedBox::setExtents(const Ogre::Vector3&, const Ogre::Vector3&): Assertion `(min.x <= max.x && min.y <= max.y && min.z <= max.z) && "The minimum corner of the box must be less than or equal to maximum corner"' failed.
```

The degree seems unset: I added the following in the room object creation function:

``` c++
void RenderManager::rrCreateRoomObject(const RenderRequest& renderRequest)
{
    RoomObject* curRoomObject = static_cast<RoomObject*> (renderRequest.p);
    std::string name = renderRequest.str;
    std::string meshName = renderRequest.str2;
    std::string tempString = curRoomObject->getOgreNamePrefix() + name;

std::cout << "Room object: " << name << ", mesh: " << meshName << ", fullname: " << tempString << std::endl;
std::cout << "Degree rotation: " << Ogre::Degree(curRoomObject->getRotationAngle()) << std::endl;

    Ogre::Entity* ent = mSceneManager->createEntity(tempString, meshName + ".mesh");
    Ogre::SceneNode* node = mRoomSceneNode->createChildSceneNode(tempString + "_node");
std::cout << "position: " << node->getPosition() << std::endl;
    node->setPosition(curRoomObject->getPosition());
    node->setScale(Ogre::Vector3(0.7, 0.7, 0.7));
    node->roll(Ogre::Degree(curRoomObject->getRotationAngle()));
    node->attachObject(ent);
}
```

**Comment by Bertram25** [comment]
I'll add log to get the initial rotationAngle() value given to Ogre::Degree() which seems to give nan.

**Comment by Bertram25** [comment]
The angle seems not set again:

```
Room object: Room_Object_Farm14_57, mesh: Chicken, fullname: RoomObject_Room_Object_Farm14_57
Rotation Angle: -nan
Degree rotation: Degree(-nan)
position: Vector3(0, 0, 0)
```

**Comment by hwoarangmy** [comment]
good, now, we know what is happening. We just need to understand why ;-)

**Comment by Bertram25** [comment]
> good, now, we know what is happening. We just need to understand why ;-)

I've added a default mRotationAngle value (of 0) in the RoomObject constructor and the bug seems gone:
https://github.com/hwoarangmy/OpenDungeons/blob/development/source/RoomObject.cpp#L45

I've reset the chicken model used and will do more tests, but I guess we're not far. :)

**Comment by hwoarangmy** [comment]
ok, I understand. Thanks for your tests. As you said, the angle is not set by ODPacket. I've another PR ready that will fix that by using objects on a more proper way (no more use of operator << and >> but functions instead).

However, the changes are quite huge (I've done that while adding trap boulder and renamed RoomObject to RenderedMovableEntity). Do you want to integrate this one before or shall I push my changes to this PR ?

**Comment by Bertram25** [comment]
Hey :)

For the record, I reached turn > 2000 twice so I guess simply setting the constructor value fixed it. :)

> ok, I understand. As you said, the angle is not set by ODPacket. I've another PR ready that will fix that by using a more proper use of objects (no more use of operator << and >> but a function instead).

All fine by me on paper. :) Could you set a default value in the RoomObject constructor anyway?
It cannot hurt, IMHO.

> However, the changes are quite huge (I've done that while adding trop boulder and renamed RoomObject to RenderedMovableEntity). Do you want to integrate this one before or shall I push my changes to this PR ?

Go ahead. I'll have a look while I'm on all that :)

**Comment by hwoarangmy** [comment]
@Bertram25 COuld you try like this please ?

**Comment by Bertram25** [comment]
@hwoarangmy With a lot of pleasure. :)

**Comment by hwoarangmy** [comment]
BTW, I warn you, the boulder trap is not very nice. There is no animation so... 
But it is enough for now ^^

**Comment by Bertram25** [comment]
> BTW, I warn you, the boulder trap is not very nice. But there is no animation so...

Ok. At least it's a nice basis and @Danimal696 has no more excuses. ;)

**Comment by Bertram25** [comment]
The trap boulder icon position is overlapping the spike trap one. Apart from that, the beast is mergeable. So I'll merge it and we'll fix the the icon position in the next PR. :)
Let's move on! ;)

**Comment by Danimal696** [comment]
> Ok. At least it's a nice basis and @Danimal696 has no more excuses. ;)

I do :P ; I though it would be done in code, do i animate it rotating?

**Comment by Bertram25** [comment]
> I do :P ; I though it would be done in code, do i animate it rotating?

Eh eh. The boulder might need a rolling animation indeed. :)

**Pull request merged**
