### PR TITLE
Added some more commands to menu screen

### PR DESCRIPTION
**Pull request by hwoarangmy**

### CODE REVIEW

**Comment by akien-mga** [comment]
Code looks good.

Should we try to plan a game sometime this weekend?

**Comment by hwoarangmy** [comment]
@akien-mga I will try to connect tomorrow if I can. We will see if someone is around on IRC.

**Comment by Bertram25** [comment]
I will be available only next week-end, but do not hesitate to have one if you can. :)

**Comment by hwoarangmy** [comment]
@akien-mga I'm currently uploading a snapshot based on my current repo. Could you please build similar binaries so we can use the same tomorrow ?

**Pull request merged**
