### PR TITLE
Weapons for Elf and Dark Elf + two objects for casino

### PR DESCRIPTION
**Pull request by Danimal696**
Elfs are copies of wizards config data, included weapons in equipment
file.
One wall object and one center spot for casino.

Closes:
#981
#1054

### CODE REVIEW

**Comment by hwoarangmy** [comment]
@Danimal696 I've tried but there is a problem with the bow normals. The file is jpg while the material uses a png. After converting it, it works ^^
Moreover, the textures you use are too big IMHO. 1024x512 is too much for a bow.

Please remember that ATM, the lags we have at game start come from loading textures. We should try to avoid too big textures ingame (but we can keep big ones on the media repo)

**Comment by hwoarangmy** [comment]
Also note that if you have an arrow in your stock, we could use a mesh to avoid using same effect as the wizard

**Comment by Danimal696** [comment]
ill also add the arrow

**Comment by Bertram25** [comment]
> Moreover, the textures you use are too big IMHO. 1024x512 is too much for a bow.

Is 512x512 not enough?

**Comment by Danimal696** [comment]
even less given the size of the model (128*256), sorry but i spent the whole day at a mountain :D
Tomorrow ill upload all fixes

**Comment by Bertram25** [comment]
> sorry but i spent the whole day at a mountain :D 

Don't be sorry. :) It's cool.

**Comment by hwoarangmy** [comment]
> even less given the size of the model (128*256), sorry but i spent the whole day at a mountain

For this time, it will be ok. But be sure it never happens again ;-)

**Comment by Bertram25** [comment]
> For this time, it will be ok. But be sure it never happens again ;-)

Yeah, torture time! :D

**Comment by Danimal696** [comment]
you just wait and we will see whose skin decorates my fireplace `~´

**Comment by hwoarangmy** [comment]
it works well. I will create a new issue about creatures to decide how to integrate the new models asap

**Pull request merged**
