### PR TITLE
Replaced BigKnight with a new creature

### PR DESCRIPTION
**Pull request by hwoarangmy**
@OpenDungeons/developers If you all agree with the replacement, I will upload the original model on the media repo (found on opengameart already animated)

I only had to decimate it a bit to reach 4.5k tris and to export animations

### CODE REVIEW

**Comment by Bertram25** [comment]
I will test now. :) My sole question so far is why was the PitDemon in particular chosen? Was there a problem with it (that I missed somehow)?

**Comment by Bertram25** [comment]
I like the new creature. I miss the Pit demon though, but maybe there is a good reason.

**Comment by hwoarangmy** [comment]
Because the creature looks like a tier 4.

Defender, Scarab, Orc and Troll are already final creatures. That only left PitDemon and Dragon (not good enough models compared to the rest). IMHO, Dragon is a little bit better than PitDemon so it got chosen ^^

**Comment by Bertram25** [comment]
I see. We miss a very demonic strong creature for the dark side, but the models looks good. :)

**Comment by hwoarangmy** [comment]
We could also replace BigKnight with this one (it can fit hero side IMHO)

Would you prefer ?

**Comment by Bertram25** [comment]
> We could also replace BigKnight with this one (it can fit hero side IMHO)
> Would you prefer ?

Yes, definitely. Good idea. :)

**Comment by hwoarangmy** [comment]
won't you miss too much the bigkight ?

**Comment by Bertram25** [comment]
> won't you miss too much the bigkight ?

No, since we already have knights (not big ones) using the same keeper-nightmarish model. :)

**Comment by hwoarangmy** [comment]
@Bertram25 @akien-mga It's done

**Comment by akien-mga** [comment]
Looks great! :D

**Comment by Bertram25** [comment]
Cool, thanks :)

**Pull request merged**
