### PR TITLE
Implemented Torture room + technical improvements

### PR DESCRIPTION
**Pull request by hwoarangmy**
For now, I've used a small roulette as room object for the torture room.

Enjoy ^^

### CODE REVIEW

**Comment by Danimal696** [comment]
What are its inner working regarding creatures? i drop them there and...?

**Comment by Danimal696** [comment]
not sure if related but i got a few of these crashes:
sin titulo-2 copia

and since i wont be just negative, great update! getting a working torture room is really nice; the beast is growing quite fast :)

**Comment by hwoarangmy** [comment]
@Danimal696 The bug is related to creature carrying. I've never seen it; though. Do you have the corresponding log and replay ?

> What are its inner working regarding creatures? i drop them there and...?

ATM, no creature works there. If you drop a creature (other than worker) ally or prisoner, it should go to one of the active spot and get tortured by fire. Is it not what they do ? If so, please upload a replay + logs

**Comment by Danimal696** [comment]
[Ogre.zip](https://github.com/OpenDungeons/OpenDungeons/files/76404/Ogre.zip)
[2016-01-02_231318-SK-StonekeepSiege.zip](https://github.com/OpenDungeons/OpenDungeons/files/76407/2016-01-02_231318-SK-StonekeepSiege.zip)
[replay_20150623_021412.zip](https://github.com/OpenDungeons/OpenDungeons/files/76408/replay_20150623_021412.zip)

I was refering that it seems there is chances of creature dying or converting; and yes that error seems to be related to creature carrying, happened when a kobold tried to imprison a dwarf.

Im attaching anything that could be useful.

**Comment by hwoarangmy** [comment]
> Im attaching anything that could be useful.

Thanks, I will have a look

> I was refering that it seems there is chances of creature dying or converting; 

Tortured creatures are hurt each turn like in prison. However, if they die, they spawn nothing for the moment.
You need to heal tortured creatures in order to make them last longer so that they turn to your side ^^

**Comment by hwoarangmy** [comment]
@Danimal696 I don't know where your log file comes from but the logs are not in it. Don't you have some "opendungeons.log" file ?
I will have a look at the replay anyway.

They log file should be in your 
{USER_DATA}\AppData\Roaming\opendungeons

**Comment by hwoarangmy** [comment]
@Danimal696 The replay you sent is not of the good version and is tagged from 23/06/2015. I guess it is not the good one ;)
You should find the replay here:
{USER_DATA}\AppData\Roaming\opendungeons\replay

**Comment by Danimal696** [comment]
The crashed program doesnt create a replay, is there a way to force it?
[opendungeons.zip](https://github.com/OpenDungeons/OpenDungeons/files/76640/opendungeons.zip)

**Comment by hwoarangmy** [comment]
Thanks to your log, I've seen a problem with carryable entities. However, it is not related to Dwarf99 but to Dwarf97. I've seen nothing special about Dwarf99.
I can only guess it is a side effect of the bug I've seen. I will open an issue

**Comment by Bertram25** [comment]
Code looks good AFAICS. Will torture^W test now. ;)

**Comment by hwoarangmy** [comment]
@Bertram25 I will wait for your review. I've fixed the bug @Danimal696 saw but I don't want to add commits while you ar testing ^^
Feel free to merge if you are ok

**Comment by Bertram25** [comment]
let's go!

**Pull request merged**
