### PR TITLE
Add installation instructions for Linux + some distribution bonus (desktop file, icon)

### LINKED ISSUE #58: Make OD system-wide installable on Linux
I've started working on proper "make install" instructions for Linux. I will soon commit some changes to my fork and we can discuss them here before I do a proper pull request.

I managed to install OD on my system, putting the two binaries (script and OpenDungeons.bin) into /usr/games and the data into /usr/share/games/opendungeons
The data is:

```
$ ls /usr/share/games/opendungeons/
gui/  levels/  materials/  models/  music/  plugins.cfg  resources.cfg  resources.zip.cfg  sounds/
```

Now, I'm having an issue with the "levels" folder, since it is not linked in resources.cfg nor in resources.zip.cfg. I tried adding a "[Level]" or "[Levels]" category, but obviously it does not work, so my guess is that the "./levels" path is hardcoded for now. Any clue about reading it from the resources.cfg too?

EDIT: The above is also valid for the "scripts" folder. For now I worked around the issue by adding "cd /usr/share/games/opendungeons" in the launch script, so that the executable is started from a folder containing the "levels" and "scripts" folder. That's really messy :-p

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #58.

### CODE REVIEW

**Comment by Bertram25** [comment]
Testing now :)

**Comment by akien-mga** [comment]
Note that on some distributions, /usr/local/games might not be in the PATH, so it could be that you won't be able to run "opendungeons" directly. I don't think that's something we have to cater for though, I already asked on the Mageia development mailing list if /usr/local/games could be added to the PATH (there is /usr/bin, /usr/games and /usr/local/bin already).

Same thing for the icons in /usr/local/share/icons/hicolor, it seems they are not picked up automatically here, so I had to configure the desktop file to point to the icon directly. So for the desktop file the icon field is `Icon=/usr/local/share/icons/hicolor/scalable/apps/opendungeons.svg`. I fear that this might break the purpose of the hicolor theme that should retrieve the correct size of the icon if it's available (as discussed in #202).
But that's something that can be improved afterwards (e.g. test whether the CMAKE_INSTALL_PREFIX is /usr, and use directly `Icon=opendungeons` in this case (since the distro should search for it directly in /usr/share/icons/hicolor).

**Comment by Bertram25** [comment]
I wouldn't fear too much the /usr/local stuff. You are the true packager here, but IMHO, people compiling will play using the developer behaviour, the other are users or packagers using both /usr.
My two cents, though.

**Comment by Bertram25** [comment]
Tested with latest patch. Works like a charm. :)

**Comment by akien-mga** [comment]
> I wouldn't fear too much the /usr/local stuff. You are the true packager here, but IMHO, people compiling will play using the developer behaviour, the other are users or packagers using both /usr.
> My two cents, though.

You have a point. Do you think I should drop the configuration step for the desktop file and just use:

```
Exec=opendungeons
Icon=opendungeons
```

**Comment by Bertram25** [comment]
If you are certain it is the common practice for desktop files, then yes I trust you upon this.

**Comment by akien-mga** [comment]
I'll think I will tweak the script in order to have, when installed in /usr:

```
Exec=/usr/games/opendungeons
Icon=opendungeons
```

and when installed in /usr/local:

```
Exec=/usr/local/games/opendungeons
Icon=/usr/local/share/icons/hicolor/scalable/apps/opendungeons.svg
```

The `Exec=opendungeons` works fine on Mageia and would on Debian, but I don't trust all distros to have /usr/games in their default PATH, so it doesn't cost much to be more specific.
As pointed out earlier for the icon, I think the `Icon=opendungeons` is the best solution to have a flexible icon (with different icons depending on the size), but would not work (at least on Mageia) if installed in /usr/local.

With my proposal from above, it should work in both prefixes, with the only fallback that your incoming 16x16 and 32x32 icons might not be used on /usr/local.

**Comment by Bertram25** [comment]
> With my proposal from above, it should work in both prefixes, with the only fallback that your incoming 16x16 and 32x32 icons might not be used on /usr/local.

The proposal looks more than fine, IMHO. As for the icons, well, I'm sure not a lot people will notice.
As it would be a very specific set of users, IMHO.

**Comment by akien-mga** [comment]
Commit b1483c0 implements the proposal described above.

I've noticed that if you run cmake with the default prefix, and then run it again with -DCMAKE_INSTALL_PREFIX=/usr, the Exec field in the desktop file won't be reconfigured. But it's not really important IMO, we don't support successive CMake calls with variations :-)

**Comment by Bertram25** [comment]
> I've noticed that if you run cmake with the default prefix, and then run it again with -DCMAKE_INSTALL_PREFIX=/usr, the Exec field in the desktop file won't be reconfigured. But it's not really important IMO, we don't support successive CMake calls with variations :-)

True. Works like a charm. :)
If you haven't anything left for doubts, I'll merge. ;)

**Comment by akien-mga** [comment]
Nice :-D

**Comment by akien-mga** [comment]
@Bertram25 Maybe now would be a good time to merge the beast into stable?

**Comment by Bertram25** [comment]
Done! :)

**Pull request merged**
