### PR TITLE
Stop rendering the tile under the room/trap ground tile.

### PR DESCRIPTION
**Pull request by Bertram25**
Thanks to oln for that, it was obvious but my mind wouldn't have make it this time. XD

I also removed the gold on ground when all the gold has been dug.
It is misleading and shouldn't be done until we have a better tile for that.

### CODE REVIEW

**Comment by Danimal696** [comment]
remember to lower the room/traps tiles to 0,0

**Comment by hwoarangmy** [comment]
> remember to lower the room/traps tiles to 0,0

@Bertram25 has already done that ;-)

**Comment by akien-mga** [comment]
Currently compiling... :-)

**Comment by hwoarangmy** [comment]
There is a problem with traps
Because they don't display anything on the Tile, they are displayed black with your patch. You can use curBuilding->shouldDisplayMeshOnGround() to set the tile visibility.

**Comment by akien-mga** [comment]
I can confirm the issue with traps (they display fine on claimed tiles, but not when you place other rooms on top of/around them.

Before:
od1

After:
od2

**Comment by hwoarangmy** [comment]
> they display fine on claimed tiles

That's not normal. it is hiding another bug.

**Comment by akien-mga** [comment]
> > they display fine on claimed tiles
> 
> That's not normal. it is hiding another bug.

I've had another look, and actually they display fine on claimed tiles, but then the ground tiles turns to black when it's refreshed (i.e. when claiming the wall next to the tile, or in my example above, when building a room next to it).

So maybe the tile has to be refreshed when an object is placed on it?

**Comment by Bertram25** [comment]
That's right. Tiles where you put a trap aren't refreshed. I'll have a look.

**Comment by hwoarangmy** [comment]
> they display fine on claimed tiles

Yes, I've had a look and that's because curBuilding->shouldDisplayMeshOnGround() is called when creating a building.

**Comment by Bertram25** [comment]
@akien-mga Btw, on the screenies given, the objectives say you have lost your temple. Was it the case or is it a bug?

**Comment by akien-mga** [comment]
> @akien-mga Btw, on the screenies given, the objectives say you have lost your temple. Was it the case or is it a bug?

Hehe yes I played with the destroy room button :-P

**Comment by Bertram25** [comment]
> Hehe yes I played with the destroy room button :-P

Ok, one less bug. ;)

**Comment by Danimal696** [comment]
is that a cannon and spike trap built over the library?

**Comment by akien-mga** [comment]
> is that a cannon and spike trap built over the library?

Nope, the library is just built around them afterwards. Though it's a nice tactic to defend your base with cannon + wizards :-D

**Comment by hwoarangmy** [comment]
but you loose active spots by doing that...

**Comment by akien-mga** [comment]
> but you loose active spots by doing that...

True. But don't try to analyse too deeply what hazardous behaviour an Evil Tester may have ;-)

**Comment by Bertram25** [comment]
I won't likely be able to code before the next week. So please be patient with that one. ;) And have a nice week-end guys. :)

**Comment by hwoarangmy** [comment]
No problem. Have a nice week end ^^

**Comment by Danimal696** [comment]
same here, dont get sunburnt

**Comment by Bertram25** [comment]
> same here, dont get sunburnt

Seems I took some light and fresh air, but not much UV :) Thanks.

I'll be back on that one asap.

**Comment by Bertram25** [comment]
@akien-mga @hwoarangmy @oyvindln It should be fixed now :)
I also added the new spider and fixed an animation bug when certain creatures are fleeing.

**Comment by akien-mga** [comment]
Hm, it segfaults on startup here:

```
Loading music...
Loading: Pal_Zoltan_Illes_OpenDungeons_maintheme.ogg
Loading: The_Dark_Amulet.ogg
Loading: yd_Searching_ingame.ogg
Music loading done
signal 11 (Segmentation fault), address is 0x1 from 0x1

Segmentation fault
```

**Comment by akien-mga** [comment]
I'll try to recompile in a clean build environment.

EDIT: Still segfaults.

**Comment by Bertram25** [comment]
> EDIT: Still segfaults.

Can you give me a bt?

**Comment by Bertram25** [comment]
@akien-mga After loading the music, the game start by loading cegui textures.
As a wild guess, I think that because of the new spider  texture, there could be some misalignment in the next one maybe?
Could you try reverting the spider model commit and try again?
If it doesn't fix the problem, then I'll need a bt as it doesn't crash here.

**Comment by akien-mga** [comment]
> As a wild guess, I think that because of the new spider texture, there could be some misalignment in the next one maybe?
> Could you try reverting the spider model commit and try again?

I still get segfaults without this commit. I'm not installing the needed debug info on all libraries to get a relevant bt :-)

**Comment by hwoarangmy** [comment]
I'm gonna try tonight

**Comment by Bertram25** [comment]
> I'm gonna try tonight

Thanks :)

**Comment by oyvindln** [comment]
Runs fine here. (I accidentally merged it into my angelscript update, but that shouldn't make a difference. )

I would have though ogre would throw an exception if there was something wrong with the spider model/material, though I can't see what else in the code would break, unless this:
Ogre::Entity\* tileEnt = mSceneManager->getEntity(curTile->getOgreNamePrefix() + curTile->getName());

somehow returns a null pointer for some reason.

**Comment by Bertram25** [comment]
> (I accidentally merged it into my angelscript update, but that shouldn't make a difference. )

@oyvindln In that case, you should rebase from the main development branch or someone will push my commits along with yours.
`git pull --rebase git://github.com/OpenDungeons/OpenDungeons.git development`
should do the trick.

**Comment by Bertram25** [comment]
> I would have though ogre would throw an exception if there was something wrong with the spider model/material, though I can't see what else in the code would break, unless this:
> Ogre::Entity\* tileEnt = mSceneManager->getEntity(curTile->getOgreNamePrefix() + curTile->getName()); somehow returns a null pointer for some reason.

Yeah, but @akien-mga has got a segfault much earlier than that. ?

**Comment by akien-mga** [comment]
Here is my backtrace:

```
Music loading done

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000001 in ?? ()
(gdb) bt
#0  0x0000000000000001 in ?? ()
#1  0x00007ffff5f7ff8a in CEGUI::XMLParser::initialise (this=0xefa440) at /usr/src/debug/cegui-0.8.4/cegui/src/XMLParser.cpp:50
#2  0x00007ffff5f21d52 in CEGUI::System::setXMLParser (this=0x1475c40, parserName=...) at /usr/src/debug/cegui-0.8.4/cegui/src/System.cpp:768
#3  0x00007ffff5f21dd4 in CEGUI::System::setupXMLParser (this=this@entry=0x1475c40) at /usr/src/debug/cegui-0.8.4/cegui/src/System.cpp:703
#4  0x00007ffff5f23b0f in CEGUI::System::System (this=0x1475c40, renderer=..., resourceProvider=<optimized out>, xmlParser=0x0, imageCodec=<optimized out>, scriptModule=<optimized out>, 
    configFile=..., logFile=...) at /usr/src/debug/cegui-0.8.4/cegui/src/System.cpp:160
#5  0x00007ffff5f2434a in CEGUI::System::create (renderer=..., resourceProvider=resourceProvider@entry=0x1475760, xmlParser=xmlParser@entry=0x0, imageCodec=imageCodec@entry=0x1475820, 
    scriptModule=scriptModule@entry=0x0, configFile=..., logFile=..., abi=208) at /usr/src/debug/cegui-0.8.4/cegui/src/System.cpp:885
#6  0x00007ffff5b664b0 in CEGUI::OgreRenderer::bootstrapSystem (abi=abi@entry=208) at /usr/src/debug/cegui-0.8.4/cegui/src/RendererModules/Ogre/Renderer.cpp:249
#7  0x00000000005bfb68 in Gui::Gui (this=0x11f1ee0) at /home/akien/Projects/opendungeons/OpenDungeons/source/render/Gui.cpp:60
#8  0x00000000006162a8 in ODApplication::ODApplication (this=0x7fffffffd920) at /home/akien/Projects/opendungeons/OpenDungeons/source/ODApplication.cpp:115
#9  0x000000000046c772 in main (argc=<optimized out>, argv=<optimized out>) at /home/akien/Projects/opendungeons/OpenDungeons/source/main.cpp:82
```

**Comment by akien-mga** [comment]
> > (I accidentally merged it into my angelscript update, but that shouldn't make a difference. )
> 
> @oyvindln In that case, you should rebase from the main development branch or someone will push my commits along with yours.

It seems @oyvindln was careful enough not to git push his branch after he merged your commits :-) As long as he doesn't have to add new commits to the PR, it should be fine.

**Comment by akien-mga** [comment]
@Bertram25 Ok nevermind my segfault... It was because I had cegui 0.7.9 installed alongside cegui 0.8.4 (to build https://github.com/Secretchronicles/TSC ), and it seems the former is used in such cases (it would be nice if we could fix that, but I have no clue about it).

I removed cegui 0.7.9, it now starts fine.

**Comment by Bertram25** [comment]
> It seems @oyvindln was careful enough not to git push his branch after he merged your commits :-) As long as he doesn't have to add new commits to the PR, it should be fine.

Ah true. Nevermind then. :)

> I removed cegui 0.7.9, it now starts fine.

Great! :) (Was the second time it happened to you. Old demons coming back?) Tell me if your trained eyes see anything. ;)

**Comment by Bertram25** [comment]
Btw, the cegui guys told me there is currently no way to separate cegui libs by default. I guess there is a common trick for such unfriendly libraries, but I can't remember atm.

**Comment by oyvindln** [comment]
@Bertram25 What I meant was that I accidentally merged my angelscript changes into a new branch used to test this, not the other way around.

**Comment by akien-mga** [comment]
> Great! :) (Was the second time it happened to you. Old demons coming back?)

Yes I'm more than looking forward to dropping this cegui 0.7.9 package... But Super Maryo Chronicles needs it, and now its fork TSC is making some awesome progress but they removed the switch to cegui 0.8.x from their 2.0 release, so I'll still have to be careful about this old cegui for a while :-)

**Comment by Bertram25** [comment]
> @Bertram25 What I meant was that I accidentally merged my angelscript changes into a new branch used to test this, not the other way around.

Yep, I have checked, sorry for seeming like patronizing. :S It wasn't my intention. Well, you know me. ;)

**Comment by Bertram25** [comment]
> TSC is making some awesome progress

Since I like a lot SecretMaryo I'll have to look at all that. :)

**Comment by akien-mga** [comment]
> Since I like a lot SecretMaryo I'll have to look at all that. :)

I've talked with them on IRC, they would be interested in some tips from someone with CEGUI knowledge :-P

**Comment by Bertram25** [comment]
> I've talked with them on IRC, they would be interested in some tips from someone with CEGUI knowledge :-P

Give them my mail and I'll have a look. ;)

**Comment by akien-mga** [comment]
Tested the PR, it works great. Look at this nice Cave Hornet:
cavehornet

The only regression that I spotted is that when you place a strike trap, the tile is first renderer black before the trap is drawn. Maybe some latency from the server paradigm? In this case a workaround could be to draw the trap before stopping to draw the ground.

**Comment by Bertram25** [comment]
> The only regression that I spotted is that when you place a strike trap, the tile is first renderer black before the trap is drawn. Maybe some latency from the server paradigm? In this case a workaround could be to draw the drap before stopping to draw the ground.

Hmm, I guess I'll make the ground tile still drawn as a quick-fix?

**Comment by hwoarangmy** [comment]
I confirm the bug seen by @akien-mga (and that the fix is not that easy ;-) )
The tiles are much better now.

**Comment by Bertram25** [comment]
@akien-mga @hwoarangmy I've quick-fixed the spike trap.
If you see anything else... ;)

**Comment by akien-mga** [comment]
I confirm the quick fix :-)
For me it's good to merge, but I see that @hwoarangmy has made some comments on the code, so I'll let you sort this out before.

**Comment by hwoarangmy** [comment]
Is there no graphical glitch since trap tile and ground tile should be at the same level, no ?

EDIT: nevermatters, I've had an idea for the spike bug problem. We could change shouldDisplayGroundTile so that it uses the concened tile as a parameter. This way, we would just have to adapt the trap code so that it returns true until the active spots are created and false after that. And to trigger a refresh tile after a new spiketrap active spot is created. It is generic and can even be used for rooms that would have active spots on ground (we could even do the same about shouldDisplayBuildingTile to allow choosing between room ground tile and room active spot).

If you have enough of playing with ground tiles for now, we can merge this PR and I will do it later. And if you want to do it yourself, if you want, we can merge this PR and wait another one...

**Comment by Bertram25** [comment]
Yeah, your idea is good. The perfect thing would be to have precedence on tiles. I mean display a building tile if there is one and fallback on a terrain tile if there isn't, and see whether we can adapt the api accordingly. Maybe it's even what you have in mind? I even wonder if we could merge getcovering*() functions at some point in order to streamline their use. Anyway, if there is no more bugs seen in thus pr, I'll request that it is merged and we keep on this discussion in a dedicated issue. Thanks for the help. :)

**Comment by akien-mga** [comment]
Tested the last commit, it doesn't seem to break anything. Merging :-)

**Pull request merged**
