### PR TITLE
Made creatures stay on the ground while sleeping + few improvements

### PR DESCRIPTION
**Pull request by hwoarangmy**

### CODE REVIEW

**Comment by akien-mga** [comment]
Looks fine to me provided the CI tests work (regarding the Ogre 1.10 changes).

**Comment by hwoarangmy** [comment]
There is a strange error with travis ci. Moreover, I didn't notice but compilation time increased much. I will have a closer look to see what is happening. In the meanwhile, please don't merge.

**Comment by akien-mga** [comment]
@hwoarangmy It looks like the 00-Random test lacks -lboost_system.

**Comment by hwoarangmy** [comment]
I saw. I guess I shouldn't have included something in a header (probably Helper since I didn't change anything in Random)

**Comment by hwoarangmy** [comment]
I guess it will be better now ^^
At least, compilation time dropped to what it was

**Comment by akien-mga** [comment]
@hwoarangmy Now it's msvc which is unhappy :)

**Comment by hwoarangmy** [comment]
> Now it's msvc which is unhappy :)

Yes. msvc needs to include cstdint to use intXX_t (not needed for gcc or MinGW). I guess that by removing some dependencies, I removed cstdint too. I will fix that tonight (should not be too hard) ^^

**Comment by hwoarangmy** [comment]
It looks like there is a problem with github. Travis did not want to trigger the build and appveyor displays a strange message. However, appveyor built my repo successfully and travis displays there is an error with github.

To me, this one is mergeable.

**Comment by akien-mga** [comment]
Works fine here.

**Pull request merged**
