### PR TITLE
Some more quick-fixes

### PR DESCRIPTION
**Pull request by Bertram25**
Line-endings + removed the golem worker from the keeper spawn pool :)

### CODE REVIEW

**Comment by akien-mga** [comment]
Looking good. I just wondered, what is this resources.zip.cfg stuff anyway? Is it something that we use, or should we drop it?

**Comment by Bertram25** [comment]
Good question. For now, we're not zipping resources but will we do that in the future? @oyvindln Do you remember what was the original plan?

**Comment by hwoarangmy** [comment]
resource.zip.cfg is a problem not concerned by this PR. I merge

**Comment by oyvindln** [comment]
@Bertram25 I think it's just a leftover from ogre example code, it should be safe to remove.

**Comment by Bertram25** [comment]
@oyvindln Ok, I'll make sure to remove it in one of my next commits. Thanks for the info. :)

**Pull request merged**
