### PR TITLE
Fixed MinGW compilation issues

### PR DESCRIPTION
**Pull request by hwoarangmy**
Note to self: It would also be nice to replace the calls to Ogre::StringConverter::toString by Helper::toString

### CODE REVIEW

**Comment by Bertram25** [comment]
Looks fine as far as I'm concerned. If another linuxian can confirm it is, let's merge. :)

**Comment by akien-mga** [comment]
Builds and runs fine here, I merge.

**Comment by oyvindln** [comment]
Is there any reason to reinvent the wheel instead of using  boost::lexical_cast or stringconverter directly? Also this means that console arguments that are mistyped become 0 instead of giving an error.

**Comment by Bertram25** [comment]
> Is there any reason to reinvent the wheel instead of using boost::lexical_cast or stringconverter directly? Also this means that console arguments that are mistyped become 0 instead of giving an error.

I agree with you  @oyvindln . I see your point but the wheel will need to be cross-platform and supported on MingW.
Is there a way to achieve this while keeping readable code?

**Comment by hwoarangmy** [comment]
> Is there any reason to reinvent the wheel instead of using boost::lexical_cast or stringconverter directly?

Well there was no use of boost::lexical_cast in any code I've read. Moreover, IIRC, boost::lexical_cast can throw exceptions when Helper::toDouble/toInt just return 0 when it fails. That's why changing to boost::lexical_cast  is not straightforward IMHO...

**Comment by oyvindln** [comment]
The console code already relied on exceptions, the functions from the standard library worked that way. Other places returning 0 may make more sense.
But why not use ogre::stringconverter directly instead of adding a function in helper.h that calls it?

**Comment by hwoarangmy** [comment]
> Other places returning 0 may make more sense.

Yes because AFAIK, most of the places where Helper::toDouble/toInt are called are during config file parsing (for example creatures.cfg). So using an exception thrower function can really change the current behaviour (even if I can understand that one do not want to use broken config files but that's just how it is currently done).

> But why not use ogre::stringconverter directly instead of adding a function in helper.h that calls it?

Well, the functions are inlined (so if I am not mistaken, the performances are equal). Moreover, using:
Ogre::StringConverter::toString() is longer than:
Helper::toString
And last, if we want to change, for example, to boost::lexical_cast, it will be easier to change in one place only than changing everywhere in the code.

That's why I used the Helper functions. But if most of us want to change, I won't bother.

**Comment by Bertram25** [comment]
I'll add that the helper functions are also a way to make sure we use code approved to do certain common operations.
As for the exception handling. I'll daresay I hate them and prefer making programs that handle such cases and go on rather than triggering an exception for anything. Let's use them only when they matters. It is especially important in a game where the players want to keep playing.
What I agree about, on the other hand, is using boost libraries when they help us rather than coding stuff ourselves but that's a slightly different point.

**Comment by hwoarangmy** [comment]
IMHO, there are 2 ways of handling unexpected states:
- Throw an exception
- Try to continue without segfault and see what happens

In the code there are loads of checks like testing nullptr that continues when there is an unexpected state. The choice has already been made for the second possibility. As a java coder, I'm more used for the first one but usually, when I start working on a code that is not mine, I try to adapt and to follow its philosophy ^^

**Pull request merged**
