### PR TITLE
Set 8 health levels for health overlay + Added creature mood overlay + fixes

### PR DESCRIPTION
**Pull request by hwoarangmy**

### CODE REVIEW

**Comment by Bertram25** [comment]
My comment about sleep action apart, the code looks good.
I'll test asap. Looks like a pretty cool thing done. :D

**Comment by akien-mga** [comment]
I'll test it in a couple of hours :)

**Comment by Bertram25** [comment]
Ah, before I forget: Here is the KO icon:
creatureko

**Comment by hwoarangmy** [comment]
Note that the KO icon is not used so it can be used later...

**Comment by Bertram25** [comment]
I'll add it into the issue then. :)

**Comment by hwoarangmy** [comment]
I've created #751 for that

**Comment by Bertram25** [comment]
I'll test tonight. :) Thanks for your patience. :S

**Comment by akien-mga** [comment]
> I'll test tonight. :) Thanks for your patience. :S

Oops, sorry for not testing earlier either. I've been playing around with the Godot engine lately ;-) https://github.com/akien-mga/dynadungeons (No, the name is absolutely not inspired from OpenDungeons :-P).

**Comment by Bertram25** [comment]
> Oops, sorry for not testing earlier either. I've been playing around with the Godot engine lately ;-) https://github.com/akien-mga/dynadungeons (No, the name is absolutely not inspired from OpenDungeons :-P).

Congrats! :) It's cool to see a bomber being developed. :)  I can see you're already thinking about adding RPG elements... ;)

**Comment by akien-mga** [comment]
Tested the PR and it works great :)
Personally I saw something more discrete for the mood overlay (maybe only displayed when pressing Alt or hovering the creature, as for the health overlay), but this can be fine tuned later. The most important is the logic :)

**Comment by hwoarangmy** [comment]
> Personally I saw something more discrete for the mood overlay (maybe only displayed when pressing Alt or hovering the creature, as for the health overlay), but this can be fine tuned later.

As you say, it can be changed later. However, the mood overlay is only displayed when there is something wrong with the creature so it is usually not a good sign to see too many overlays ^^

**Comment by hwoarangmy** [comment]
> I'll test tonight. :) Thanks for your patience. :S

No problem ^^

**Comment by Bertram25** [comment]
> so it is usually not a good sign to see too many overlays ^^

Eh eh. eager to try that.

**Comment by Bertram25** [comment]
It's incredible!! :D It makes the creatures intention so much clearer.
Congrats for adding status icon cycling also. I'll merge now. congrats!!

**Pull request merged**
