### PR TITLE
Restore stats windows when middle clic on creature

### LINKED ISSUE #78: Refresh creature infos when stats window open

### PR DESCRIPTION
**Pull request by hwoarangmy**
fixes #78
- Fixed a small bug in the hunger system (stupid me)

### CODE REVIEW

**Comment by hwoarangmy** [comment]
@Bertram25 @akien-mageia Could you have a look ? It's not a big one this time :)

**Comment by akien-mga** [comment]
Builds fine and the stats window works too. From my side it's okay to be pushed, maybe @Bertram25 will want to look through the code quickly before pushing.

**Comment by Bertram25** [comment]
> maybe @Bertram25 will want to look through the code quickly before pushing.
> Yep, and code looks fine. :)

Thanks for bonus fix about hunger when dropped. I looked at the condition when reviewing the former patch but misinterpreted it. (I'm also stupid, eh. ;])
Merging...

**Comment by hwoarangmy** [comment]
> I looked at the condition when reviewing the former patch but misinterpreted it. (I'm also stupid, eh. ;])

Yes, it can be tricky as hunger works the opposite as awakeness (from 0 to 100 instead of 100 to 0). But it was the most understandable IMO so I prefered to use it.

**Comment by Bertram25** [comment]
> But it was the most understandable IMO so I prefered to use it.

I agree: Hunger grows when not eating. The reverse would be weird.

**Pull request merged**
