### PR TITLE
Turned ConfigManager::mUserConfig into a vector of map.

### LINKED ISSUE #848: [Technical] - Turn the ConfigManager::mUserConfig into a vector or maps.
As discussed with @hwoarangmy .

No behavioral changes should be noticeable, but it is saner.

### PR DESCRIPTION
**Pull request by Bertram25**
As discussed with @hwoarangmy

Fixes #848

### CODE REVIEW

**Comment by hwoarangmy** [comment]
code looks good to me

**Comment by hwoarangmy** [comment]
Testing right now

**Comment by akien-mga** [comment]
@hwoarangmy What do you think about making a dev snapshot once this one is merged?

**Comment by hwoarangmy** [comment]
works well

**Pull request merged**
