### PR TITLE
Allow ranged creatures to attack rooms + fixes + Added Room and trap managers

### PR DESCRIPTION
**Pull request by hwoarangmy**

### CODE REVIEW

**Comment by Bertram25** [comment]
Nice change as for me. Needs testing as they might be regressions, like any structural changes.

**Comment by Bertram25** [comment]
I had this crash after a long play:

```
Computing turn 3075, timeSinceLastTurn=0.692865
SERVER - Adding rendered object RenderedMovableEntity_Crypt29_4434,MeshName=SmallSpider
SERVER - Adding rendered object RenderedMovableEntity_Crypt40_4435,MeshName=SmallSpider
SERVER - Removing Creature Orc205
SERVER - Removing rendered object RenderedMovableEntity_Dormitory22_[5,58]_2959,MeshName=OrcBed
*** Error in `./opendungeons': free(): invalid pointer: 0x00007f47e421e978 ***
```

No bt unfortunately. It may or may not be related to this PR. I can't tell.

**Comment by hwoarangmy** [comment]
This PR as not much to do with object deletion so I don't really see how it can come from this PR. I will also let some games play alone to test stability. I've already done that 1 time and seen no problem (after a bit more than 1 hour). I will try again

**Comment by Bertram25** [comment]
Then, I'll be bold enough to merge it. (Had two other parallel games running for more than an hour now without any problems.)
I'll rebase my own changes on this one. ;)

**Comment by hwoarangmy** [comment]
@Bertram25 FYI, I've let 3 games play during 1, 2 and 3 hours and got no crash so far. Strangely, it seems even more stable than it used to be (no crash with graphic drivers).

**Comment by Bertram25** [comment]
> @Bertram25 FYI, I've let 3 games play during 1, 2 and 3 hours and got no crash so far. Strangely, it seems even more stable than it used to be (no crash with graphic drivers).

I'm sure the code quality is increasing, but without even speaking about that, it might be rare enough to be uncatchable for now.
I'll add on my todo list to let games run with gdb on several machines so that we may maybe get lucky. The crashes could also come from player interactions, though.

**Pull request merged**
