### PR TITLE
 	Made creatures spawn according to configurable conditions

### PR DESCRIPTION
**Pull request by hwoarangmy**
I've used http://forum.freegamedev.net/viewtopic.php?f=37&t=5851&sid=e4b5e9f864223198e7338b4a0061c065

Tier 1 creatures need nearly nothing to spawn (except goblin the forge).
Tier 2 a little bit more (mostly dormitory)
Tier 3 rooms and hatchery
PitDemon : many rooms + 2 dragons (you won't see him as easily as you are used to ^^)

### CODE REVIEW

**Comment by Bertram25** [comment]
Nothing much to say about the code. It's plain good OO code doing what it is supposed to do AFAIK.
I've seen some other fixes on the camera manager that I'll test asap.

**Comment by Bertram25** [comment]
I've tested it and played a bit with the spawning conditions. AFAIK, everything is fine. :)
I'll let @akien-mga or @oyvindln test and I guess we'll be able to merge. :D 

It will be time for a new rolling release afterwards!! :)

**Comment by hwoarangmy** [comment]
> It will be time for a new rolling release afterwards!! :)

Yes. IMHO, we will have something we can call a game after integrating this PR ^^
Of course, we will need to balance creatures now but we finally have a game play.

Note that when this PR will be in, improving AI will be even more important since it actually doesn't build the usefull rooms and, so, it will always have only tier 1 units as it plays now...

**Comment by Bertram25** [comment]
AI or not, @Danimal696 won't have any excuses left to help balancing the game. ;P

**Comment by Danimal696** [comment]
so its alredy done?!?!

**Comment by Bertram25** [comment]
It is, waiting for @akien-mga review. ;)

**Comment by akien-mga** [comment]
> It is, waiting for @akien-mga review. ;)

I'm on it :-)

**Comment by akien-mga** [comment]
And suddenly, we got a gameplay! It's awesome to see different creatures incoming once you've built some rooms :-)

It's already great, if there are some issues, they can be fine-tuned later, let's merge the beast :-D

**Comment by Bertram25** [comment]
Now, the next task will be to create a rolling release ;)

**Pull request merged**
