### PR TITLE
In-game help adaptations + 12pt sized MedievalSharp font

### PR DESCRIPTION
**Pull request by akien-mga**
This is still kind of a WIP, I'd like to have your feedback on the help text and how it looks like in-game.

### CODE REVIEW

**Comment by Bertram25** [comment]
A small gift to fix a bit the help window: :)

``` diff
diff --git a/source/modes/GameMode.cpp b/source/modes/GameMode.cpp
index 77ff7b3..1a6f701 100644
--- a/source/modes/GameMode.cpp
+++ b/source/modes/GameMode.cpp
@@ -1343,18 +1343,17 @@ void GameMode::createHelpWindow()
     if (mHelpWindow != nullptr)
         return;

-    CEGUI::WindowManager* wmgr = CEGUI::WindowManager::getSingletonPtr();
     CEGUI::Window* rootWindow = CEGUI::System::getSingleton().getDefaultGUIContext().getRootWindow();

-    mHelpWindow = wmgr->createWindow("OD/FrameWindow", std::string("GameHelpWindow"));
+    mHelpWindow = rootWindow->createChild("OD/FrameWindow", std::string("GameHelpWindow"));
     mHelpWindow->setPosition(CEGUI::UVector2(CEGUI::UDim(0.2, 0), CEGUI::UDim(0.12, 0)));
     mHelpWindow->setSize(CEGUI::USize(CEGUI::UDim(0.6, 0), CEGUI::UDim(0.7, 0)));
     mHelpWindow->setProperty("AlwaysOnTop", "True");
     mHelpWindow->setProperty("SizingEnabled", "False");

-    CEGUI::Window* textWindow = wmgr->createWindow("OD/StaticText", "TextDisplay");
+    CEGUI::Window* textWindow = mHelpWindow->createChild("OD/StaticText", "TextDisplay");
     textWindow->setPosition(CEGUI::UVector2(CEGUI::UDim(0, 20), CEGUI::UDim(0, 30)));
-    textWindow->setSize(CEGUI::USize(CEGUI::UDim(1.0, -40), CEGUI::UDim(1.0, -30)));
+    textWindow->setSize(CEGUI::USize(CEGUI::UDim(1.0, -40), CEGUI::UDim(0.95, -40)));
     textWindow->setProperty("FrameEnabled", "False");
     textWindow->setProperty("BackgroundEnabled", "False");
     textWindow->setProperty("VertFormatting", "TopAligned");
@@ -1370,9 +1369,6 @@ void GameMode::createHelpWindow()
     childWindow = mHelpWindow->getChild("__auto_titlebar__");
     childWindow->setText("OpenDungeons Quick Help");

-    mHelpWindow->addChild(textWindow);
-    rootWindow->addChild(mHelpWindow);
-
     std::string formatTitleOn = "[font='MedievalSharp-12'][colour='CCBBBBFF']";
     std::string formatTitleOff = "[font='MedievalSharp-10'][colour='FFFFFFFF']";
     std::stringstream txt("");
```

**Comment by Bertram25** [comment]
Looks good otherwise. :)

**Comment by akien-mga** [comment]
> A small gift to fix a bit the help window: :)

It's in, thanks! :)

**Comment by Bertram25** [comment]
Nice work so far. After fixing @hwoarangmy 's requests, will it be mergeable, or are you willing to change more on the help window?

**Comment by akien-mga** [comment]
I've made the requested changes. If you're happy with it in can be merged IMO, it can always be improved in a second take later on.

**Comment by Bertram25** [comment]
Fine by me. Let's merge.

**Pull request merged**
