### PR TITLE
Added console commands to see visible tiles for a seat and to allow creatures to spawn at levels > 1

### PR DESCRIPTION
**Pull request by hwoarangmy**
To display visible tiles for seat 1:
seatvisdebug 1

To change level of creature BigKnight1 to 15:
setlevel BigKnight1 15

Note that it will also allow to downgrade creature level. This command might help us to balance, too.

### CODE REVIEW

**Comment by Bertram25** [comment]
Nice features. :)
I'll test asap and I have got a few comments, as usual. ;)

**Comment by akien-mga** [comment]
Fine to merge as far as I'm concerned.

**Comment by hwoarangmy** [comment]
@Bertram25 Tell me if you want me to disable visible tile computation before FOW is implemented.

I am currently having a look if it can be done on server side (that would be the best since it would avoid easy cheating by disabling FOW on client side).

**Comment by Bertram25** [comment]
> I am currently having a look if it can be done on server side (that would be the best since it would avoid easy cheating by disabling FOW on client side).

Ah, so here was your evil plan ;D I see why you let it computed now. My next question will be: What is the performance change because of this? If it is negligible, then it's great as it means computations for the FOW won't cost that much and then my comment can be ignored. I'll test asap and see what happens.

**Comment by hwoarangmy** [comment]
> What is the performance change because of this

Well, we go through all the tiles to check which are claimed by who and add them (and their neighboors) in the visible tiles list of the concerned seat if claimed. That can eventually be improved by changing the claim list only when a tile is claimed. But my guess is that it shouldn't be too costly. ANd the good point is that is pretty simple to implement.
Concerning the tiles the creatures sees, I've splitted the creature visible tiles computation to allow filling visible tiles at the same time. So there is almost no extra cost about it (just adding the tiles to the list).

**Comment by Bertram25** [comment]
> I am currently having a look if it can be done on server side (that would be the best since it would avoid easy cheating by disabling FOW on client side).

Oh yeah, I think it's a sub-goal handy to look for. :)

**Comment by Bertram25** [comment]
Btw, it seems to me you didn't added the new commands to the commands text file. This prevents auto completion when typing the command name using tab.

**Comment by hwoarangmy** [comment]
yep, i forgot. I will add it

**Comment by Bertram25** [comment]
Works like a charm, and the consequences on the FPS goes unnoticed on my side.
I think we can merge. Wanna add the missing commands before?

**Comment by hwoarangmy** [comment]
done ^^

**Comment by akien-mga** [comment]
Looks good, I merge.

**Pull request merged**
