### PR TITLE
Added support for new dig select, gold deposit, and cannon firing sounds...

### LINKED ISSUE #95: Addition of a few better sounds and musics.
Initially on Paul´s hands:

http://forum.freegamedev.net/viewtopic.php?f=35&t=5691
http://forum.freegamedev.net/viewtopic.php?f=39&t=5695

Basically making easier to add new music, a crossfading system between songs and adding sounds to creatures actions like walking, attacking, pain...

TODO Summary:
**Bertram**
- [x] Improved creature sound system Mk I  #94 
- [x] improved music system #23 - Done with #125 
- [x] Cross fade support #23 - Done with #125 
- [x] New battle music & Battle music triggered when there are skirmish: http://opengameart.org/content/the-dark-amulet-dark-mage-theme #23 - Done with #140 
- [x] Canon firing: http://opengameart.org/content/synthesized-explosion
- [x] Deposit coins on treasury: http://opengameart.org/content/coins-sounds
- [x] New dig select sound: http://forum.freegamedev.net/viewtopic.php?f=39&t=5695&p=59382#p59382

**Danimal696**
- [x] Optional: New default creatures pick-up sounds.
- [x] Optional: New default creatures drop sounds.

### PR DESCRIPTION
**Pull request by Bertram25**
....

I also normalized them, and made them mono, so they can be spatial sounds.

Fixes #95

### CODE REVIEW

**Comment by hwoarangmy** [comment]
Seems good. I will try tonight :)

**Comment by hwoarangmy** [comment]
I don't know if it is wanted but I have no sound when my workers dig.
I also don't know if it is wanted but there is no fighting music when canon fires.

**Comment by hwoarangmy** [comment]
Anyway, that's not related to this pull request so I merge

**Comment by Bertram25** [comment]
Heya :)

Nice point! :)

> I don't know if it is wanted but I have no sound when my workers dig.

It's true I never tested the sounds played for that. I'll check whether they are normalized and mono.

> I also don't know if it is wanted but there is no fighting music when canon fires. 

True also. I didn't come up to this point yet. I'll add that.

@akien-mga I'll review the remaining sounds according to their use in game, normalize them and make them mono if there are spatial ones.

**Comment by Bertram25** [comment]
Opened issue: https://github.com/OpenDungeons/OpenDungeons/issues/147

**Pull request merged**
