### PR TITLE
Implemented listeners on GameEntity

### PR DESCRIPTION
**Pull request by hwoarangmy**
That allows to listen to what happens to an entity and be notified when something happens. It can, for example, be used on missiles to notify the sender that the missile hit (for counting killed enemies for example).

### CODE REVIEW

**Comment by Bertram25** [comment]
Code looks good + some extra fixes if I saw well. ;)

I'll try asap.

**Comment by hwoarangmy** [comment]
> some extra fixes if I saw well

I had forgotten but seems like you saw well ^^

**Comment by Bertram25** [comment]
Works great! :) Mergeable as for me.

**Comment by akien-mga** [comment]
I don't see any obvious regression, so let's merge :)

**Pull request merged**
