### PR TITLE
Display MiniMap Camera in the minimap

### PR DESCRIPTION
**Pull request by hwoarangmy**
part of #530 

With this PR, I've let the camera minimap by default. If requested, I can restore the old one before we merge this PR.

### CODE REVIEW

**Comment by akien-mga** [comment]
It's awesome :-D
The minimap is a bit laggy, but it does impact the main window at all from what I could see, so it's a minor disagreement compared to the nice looking camera minimap :)

What would be your ideas to improve the performance even more? Would it help to ignore lighting in the camera minimap?

**Comment by Bertram25** [comment]
The code looks good. I'll test asap.

If the main game performance isn't hampered by the new camera (compared to the old one), I'd say let's drop the old one.
What we always wanted is this kind of minimap anyway.

**Comment by Bertram25** [comment]
> What would be your ideas to improve the performance even more? Would it help to ignore lighting in the camera minimap?

Correct me if I'm wrong but AFAIK, the objects and lights are managed (rendered) per scene.
This means we may have to create a new scene to display things differently.
I've no idea of how it would impact performance or if there is something else to do about the scene, though.

Maybe there is another trick?

**Comment by hwoarangmy** [comment]
Note that on my computer, the keeper hand blinks while on CEGUI windows while minimap is rendered (every 0.5 seconds). I guess that's the needed time to render the minimap.

> What would be your ideas to improve the performance even more?

To use custom LOD (Level Of Details - allows to display simpler meshes when the camera is far) and to display the whole map (as was the minimap camera before this PR)

> The minimap is a bit laggy

That's because it is refreshed every 0.5 seconds (that can be increased if performances allow - we might even add some config option about it).

> Maybe there is another trick?

I've seen something about implementing Ogre::RenderTargetListener. There is 1 function called before the minimap is rendered and another when it is done. The trick is to set unwanted stuff not visible before it is rendered and restore the state after.
I've seen that here:
http://www.ogre3d.org/tikiwiki/tiki-index.php?page=Intermediate+Tutorial+7

**Comment by hwoarangmy** [comment]
I've tried disabling light and it works. However, there is no visible improvement (Keeper hand is still blinking on CEGUI windows)

**Comment by Danimal696** [comment]
i demand a pic of it! or else no kobold!!!

**Comment by akien-mga** [comment]
od-minimap
It's small but hey, it's a minimap ;)

**Comment by hwoarangmy** [comment]
> i demand a pic of it! or else no kobold!!!

You will have a release during the week end so, give the kobold !!!!

**Comment by hwoarangmy** [comment]
BTW, I've tried the D3D renderer and the old minimap is buggy (seems like drawing do not work with this renderer). But the minimap camera works well ^^

**Comment by Danimal696** [comment]
i actually liked the old one, can they be toggled by user with an option (on config button, not while playing)? it would be nice to be able to choose between the two

**Comment by hwoarangmy** [comment]
Yes. I've not removed the old one

**Comment by Bertram25** [comment]
As far as I'm concerned, this is mergeable. Nice job. :)

> i actually liked the old one, can they be toggled by user with an option (on config button, not while playing)? it would be nice to be able to choose between the two

I think I'd rather have a key to switch between different minimaps and even hide it. Something like, using the M key to:
- 1. Show the minimap camera only a few tiles.
- 2. Show the minimap camera the whole map.
- 3. Show the old minimap.
- 4. Hide it
  ...

The old map will still have to die somewhen, IMHO, as we shouldn't support too much redundant functionalities.

WDYT?

**Comment by akien-mga** [comment]
@Bertram25's proposal sounds good to me :)

**Pull request merged**
