### PR TITLE
Imported new creature + allow battle royal in the arena + fix bug

### PR DESCRIPTION
**Pull request by hwoarangmy**
This time, I didn't replace any creature. The rat can be seen on the main screen.
I propose to replace the wyvern

@OpenDungeons/developers WDYT ?

### CODE REVIEW

**Comment by Bertram25** [comment]
Looks fine concerning the code. I'll test asap. :)

**Comment by hwoarangmy** [comment]
@Bertram25 @akien-mga I've rebased to integrate Elf/DarkElf weapons. It should be ok now.

**Comment by Bertram25** [comment]
Will be on it in an hour or so. :)

**Comment by Bertram25** [comment]
Testing...

**Comment by Bertram25** [comment]
The Elf/Dark Elf are looking great! :) the rest is working fine AFAIK. Let's merge.

**Pull request merged**
