### PR TITLE
Several updates to models and game balance...

### PR DESCRIPTION
**Pull request by Bertram25**

### CODE REVIEW

**Comment by hwoarangmy** [comment]
Everything seems good ^^
I will test tonight if @akien-mga doesn't merge before ^^

**Comment by akien-mga** [comment]
Boulder trap: the ball does not roll, it simply slides here.
I also find the trap's behaviour hard to predict and erratic, but that's for another issue.

**Comment by akien-mga** [comment]
Re boulder trap: when it triggers (not often, see #294), the "inactive trap" model is still shown on its initial tile, such as you see both the inactive trap and the rolling boulder (though it slides, as per my previous comment).

**Comment by akien-mga** [comment]
Hehe, if you play Scream in the dark, just above the player starting point, you have two neutral Dragons that provide a nice example of "Oh my God let's flee because we can" pathfinding, dancing in a synchronised manner on the lava :-D

**Comment by Danimal696** [comment]
Its because they now start with very little hp and flee by default ;) , about the boulder trap i can only say its animated, maybe its only played once instaed of looping?

**Comment by Bertram25** [comment]
> Boulder trap: the ball does not roll, it simply slides here.

Weird. It's working fine on my side. Note that this change requires recompilation, just in case.

> Its because they now start with very little hp and flee by default ;) , about the boulder trap i can only say its animated, maybe its only played once instaed of looping?

I made the animation triggered and looped. So it should be looking ok, and actually it looks fun to see enemy dying with the rolling boulder. :> Mwaha.

What I'd change but in another PR, would be to slightly increase the boulder move speed (to fit more the animation), and indeed maybe hide the boulder on the trap tile while it's rolling.

I would even hide the model until the trap is ready to be triggered or something like that. What do you think, guys?

**Comment by Bertram25** [comment]
> Its because they now start with very little hp and flee by default ;)

Same behaviour seen with the adventurer and knight in the 2vs2 small test map. Actually, the flee behaviour looks weird and maybe even broken in that case. Let's talk more about this in #290

**Comment by Danimal696** [comment]
can opacity be changed in code? i dont know if blender made semi transparent models will port and show fine, but it would be easier made on code to show a disarmed/planned trap

**Comment by Bertram25** [comment]
> can opacity be changed in code? i dont know if blender made semi transparent models will port and show fine, but it would be easier made on code to show a disarmed/planned trap

I've tried to answer this in #294. Hopefully, I'll come up with something sooner or later. Hiding the trap object could help in the meanwhile.

**Comment by hwoarangmy** [comment]
BTW, I confirm I can reproduce the flee bug only by increasing BigKnight HP in creatures.cfg.

@Bertram25 Concerning your PR, I confirm as @akien-mga said, the boulder do not roll for me :-(
Moreover, in console, when I write "listanims Boulder", no animation is displayed. I think you forgot the skeleton ;-)

**Comment by Bertram25** [comment]
Beginner's mistake on my side. I've forgotten to add the boulder skeleton file. I'll do it asap.

**Comment by Bertram25** [comment]
Should be ok now...

**Comment by hwoarangmy** [comment]
Hey, you changed your PR while I was testing ^^

**Comment by hwoarangmy** [comment]
Have you finished ?

**Comment by hwoarangmy** [comment]
Hey, that's the second time I'm going to merge and you add a commit. I will wait for tomorrow then ^^

**Comment by Bertram25** [comment]
> Hey, that's the second time I'm going to merge and you add a commit. I will wait for tomorrow then ^^

Oops, sorry, last commit for the week-end in this PR at least. I wanted to see that stuff in before some good action. :)

**Comment by akien-mga** [comment]
Oops, sorry for merging while you were still reviewing @hwoarangmy.

**Comment by hwoarangmy** [comment]
> Oops, sorry for merging while you were still reviewing @hwoarangmy.

No problem, I will open an issue as what @Bertram25 did is better than what we had.

**Pull request merged**
