### PR TITLE
Normaiized sounds & colored the in-game horizontal bar to the player color.

### PR DESCRIPTION
**Pull request by Bertram25**

### CODE REVIEW

**Comment by hwoarangmy** [comment]
Nothing to say about the code. I will test tonight

**Comment by Bertram25** [comment]
Thanks :) A big GUI overhaul is coming next. You'll love it ;)

**Comment by hwoarangmy** [comment]
^^

**Comment by hwoarangmy** [comment]
Ok for me. Don't really understand what is the horizontal pipe under the minimap.
But the rest is ok. I will wait for @akien-mga wants to test. If he can't, I will push

**Comment by Bertram25** [comment]
The horizontal pipe is the line on top of the in-game UI where is the gold amout, mana and tiles claimed numbers. It is now colored dynamically according to the seat color. This will the players abd us when debugging to know what color we have at a glance.

**Comment by akien-mga** [comment]
Sadly I won't be able to test for now, I couldn't solve my issue with starting a game yet. I'll probably investigate it more tomorrow or this week-end. In the meantime feel free to merge if it looks (and sounds!) good.

**Comment by Bertram25** [comment]
@akien-mga Sorry, I've been looking a bit blindly on internet but I just can't tell like that. ?? It will be interesting to know what it was, when you will have solved it, though. O.O'

**Comment by hwoarangmy** [comment]
ok. Let's merge then. And @akien-mga good luck for you problem :-(

**Comment by Bertram25** [comment]
@akien-mga Linux is usually handling sockets I/O using file descriptors. I remember people having problems logging to a local mySQL server because of file permission problems on socket for a reason I just can't remember. Maybe this can help?

**Pull request merged**
