### PR TITLE
Changed Research* to Skill*

### LINKED ISSUE #884: Rename the Research* to Skill*
The research manager, UI and so on, is in fact a skill thing.

This is a more generic name, fitting more a RPG-ish game and will make it clearer other skills obtained through magic and maybe gold, too? can go there.

### PR DESCRIPTION
**Pull request by Bertram25**
Fixes #884

Long time not done any PR. ;)

### CODE REVIEW

**Comment by hwoarangmy** [comment]
arg, this one will conflict with the one I'm currently on. I've splitted the Seat class with a base class SeatData allowing to use the seat data in the unit tests without having to get the Seat and its dependencies. Basically, that will allow to check if the expected mana/gold is used when building a room/casting a spell and such.
The good thing is that the conflicts should not be too hard to fix ^^

**Comment by Bertram25** [comment]
Oh my, I was waiting to push that between two of your PR not to get in the way. I hope it will be fine. :)

**Comment by hwoarangmy** [comment]
> Oh my, I was waiting to push that between two of your PR not to get in the way. I hope it will be fine. :)

No pb. Such a PR as yours is likely to conflict. Hopefully, you have not added other stuff that would make merging harder like I use to do ^^

**Comment by Bertram25** [comment]
> Hopefully, you have not added other stuff that would make merging harder like I use to do ^^

Nope. I must say, making everything clean was long enough to do. :S

**Comment by hwoarangmy** [comment]
> making everything clean was long enough to do

Neverending job ^^
But if you are back, I will try to create the PR ASAP so that we don't have too many conflicts if you go for something else

**Comment by Bertram25** [comment]
> But if you are back, I will try to create the PR ASAP so that we don't have too many conflicts if you go for something else

Don't worry too much about my pace. I cannot guarantee your speed. ;)
I'll make a PR for OD and VT alternatively, so that I can still officially work on both projects. :)

**Pull request merged**
