### PR TITLE
Material fixes

### PR DESCRIPTION
**Pull request by Danimal696**
if Ok, ill start fixing them all little by little

### CODE REVIEW

**Comment by Danimal696** [comment]
The bridges you can see are actually tentacles using bridge mesh, those are just for show, but since bridges will be some kind of extension of floor tiles i adapted claimed material for it, since it didnt go well i tried modding the claimed material to use the one for bridges, the result is that somehow the normal for claimed are applied instead my woodbridge normals, they are somehow hardcoded.
bridges

**Comment by Bertram25** [comment]
Bridges would need specific code to be testable but I no more have warnings on the materials.

**Comment by Danimal696** [comment]
then merge as you see fit, ill begin fixing the other materials lil by lil

**Comment by akien-mga** [comment]
Then I merge, but please give us the needed info to update the CREDITS for the bridge :)

**Comment by Bertram25** [comment]
Ah yes, the credits... I'll handle it if you want but yeah, we'll need them.
Nice catch @akien-mga

**Pull request merged**
