### PR TITLE
Added a spell manager to handle spells + small fixes

### PR DESCRIPTION
**Pull request by hwoarangmy**
@Bertram25 @oyvindln The spell manager allows to add spell just by adding the corresponding source file (and remove them by not compiling it).
Moreover, it won't compile if the spells do not define the required static functions.

I think it is a pretty elegant way to add spells. If you also like it, I might give a try at doing the same for missiles and, if possible, for the other entities.

### CODE REVIEW

**Comment by Bertram25** [comment]
Looks cool. I'll test now. :)

**Comment by Bertram25** [comment]
I like the pattern used to templatize the spells and thus make them easily added/removed.
I'll let @oyvindln tell whether he likes it or see improvement. :)

**Comment by Bertram25** [comment]
IMHO, ok to merge it.

**Comment by akien-mga** [comment]
Merging then, I'll keep #713 open for the last adjustment that was requested.

**Pull request merged**
