### PR TITLE
Moved source files in sub-folders according to their use.

### LINKED ISSUE #10: Move source/ files in sub-folders according to their subject.
E.g: Move all the entities speaking files into a Entities/ sub-folder. Move the game map related files into a GameMap/ subfolder, …

A precise list of what should move is to be done first, though,

### PR DESCRIPTION
**Pull request by Bertram25**
Fixes #10

### CODE REVIEW

**Comment by Bertram25** [comment]
@hwoarangmy I've rebased after the merge. It should be ok now.

**Comment by hwoarangmy** [comment]
I'm testing now

**Comment by hwoarangmy** [comment]
It's good ^^

**Comment by Bertram25** [comment]
Cool, if you see any improvement about that, we can do it from that point little by little. :)

**Pull request merged**
