### PR TITLE
Fixed Travis compilation + small improvements

### PR DESCRIPTION
**Pull request by hwoarangmy**

### CODE REVIEW

**Comment by Bertram25** [comment]
Excellent to see CI integration live here. :)

**Comment by hwoarangmy** [comment]
> Excellent to see CI integration live here. :)

Yes. And once we have decided how to do tests, I guess we will have done a great step to stability ^^

**Comment by Bertram25** [comment]
Ah, btw: http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

**Comment by hwoarangmy** [comment]
> Ah, btw: http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

I had seen that but honestly, I don't see how we can do anything without using sudo. The white repository list is really poor, only gcc 4.6 is installed (OD do not compile with it as it do not handle c++11 stuff), cmake also do not handle all the commands inside our makefile...
Maybe later, when they will get a default environment that is worth that name

**Comment by Bertram25** [comment]
Ah, I realize I wasn't that explanatory. I completely agree, their default environment is outdated to the least. I just wanted to mention their migration, but it means no additional work on (y)our side, of course. :)

**Comment by akien-mga** [comment]
Builds and works fine, and @Bertram25 seems happy with the code changes so let's merge :)

Currently the gold is displayed "2437 / 5000" while the creatures number is "4/10", we might want to homogenise this :) (either spaces around the slash like for gold, or none like for creatures).

**Comment by hwoarangmy** [comment]
I would say none as it takesless space (and it may be pretty high for gold) ^^

**Comment by Bertram25** [comment]
Yup, I'm fine with no spaces before and after '/'

**Pull request merged**
