### PR TITLE
More space for the caged lions + portal and temple

### PR DESCRIPTION
**Pull request by akien-mga**
Quick fix as requested in #597 :)

### CODE REVIEW

**Comment by hwoarangmy** [comment]
There is a problem in the portal definition. Since they are claimable, you need to add 2 more parameters:
- Claimed value (usually the number of tiles)
- number of creatures allowed by the portal

**Comment by akien-mga** [comment]
> There is a problem in the portal definition. Since they are claimable, you need to add 2 more parameters:
> - Claimed value (usually the number of tiles)
> - number of creatures allowed by the portal

I'll have a look. I added the portal with the map editor, so this probably means that we need to fix the editor function that creates portals.

**Comment by akien-mga** [comment]
Hm, I've tried adding "9<tab>5" at the end of the portal definition, but then I can't start the level anymore. I just mimicked what was in TestSingleplayerSmall.level, so I don't know what's wrong.

**Comment by hwoarangmy** [comment]
You need 2 numbers separated by tab. I've tested and it works ^^

Concerning portal creation,I will have a look and create an issue.

EDIT: I just tested and it works. You have probably created the portal with an older version of OD (since that's a pretty new feature).

**Comment by akien-mga** [comment]
> You need 2 numbers separated by tab. I've tested and it works ^^

Strange, that's what I use, but it doesn't work. Here is my git diff:

```
diff --git a/levels/skirmish/TestModelsFair.level b/levels/skirmish/TestModelsFair.level
index 8a28448..adbb791 100644
--- a/levels/skirmish/TestModelsFair.level
+++ b/levels/skirmish/TestModelsFair.level
@@ -921,6 +921,7 @@ Spider12    16  13  0
 5  16
 5  17
 5  18
+9  4
 [/Room]
 [Room]
 3  Treasury1   1   11
```

(well nevermind GitHub displays tabs as spaces...)

**Comment by akien-mga** [comment]
Ah lol, we're talking about a feature that has not been merged yet :-D

**Comment by akien-mga** [comment]
> Ah lol, we're talking about a feature that has not been merged yet :-D

Er actually yes, it was merged yesterday. But most likely I haven't rebuilt the binary of my fork :)

**Comment by hwoarangmy** [comment]
> Ah lol, we're talking about a feature that has not been merged yet :-D

I always test with the PR branch rebased with OD repository ;-)
I don't know git patches well enough to test live patches ^^

**Comment by akien-mga** [comment]
> I always test with the PR branch rebased with OD repository ;-)

Yeah, my branch is rebased too, but my binary was not up-to-date :-)

**Comment by hwoarangmy** [comment]
> Yeah, my branch is rebased too, but my binary was not up-to-date :-)

No problem, that happens ;-)

**Comment by akien-mga** [comment]
> Concerning portal creation,I will have a look and create an issue.

This is also a false alert, I just checked with the proper binary and the portals are created with the good parameters.

**Comment by hwoarangmy** [comment]
That's what I had tested yesterday so I merge

**Pull request merged**
