### PR TITLE
Normal and fixes for training room objects and library

### PR DESCRIPTION
**Pull request by Danimal696**

### CODE REVIEW

**Comment by akien-mga** [comment]
It looks great :-)

**Comment by Danimal696** [comment]
Put a normal in your game, you will never repent ;-)

**Comment by Danimal696** [comment]
With this the rooms and objects have fixed materials and normals added;
the only exception are the knigth statues and coffin from Crypt that
didnt benefit at all from normals.
From now on its creatures that are final and their beds

**Comment by Bertram25** [comment]
Wow, looking really great now. Especially the doll in the training room, the library objects, too. :D 
Fine to me to be merged.

**Pull request merged**
