### PR TITLE
Turned the Forge into the Workshop + Work on the Research GUI

### LINKED ISSUE #459: Turn the forge into the workshop
The current forge should be turned into the workshop.

The workshop will still be used to craft traps, but its models have to be changed as the forge models will be reused to create the new forge, where creature equipment will be forged.

Also the workshop logic will have to be upgraded so that traps are crafted only when needed and not at random. More info at: http://forum.freegamedev.net/viewtopic.php?p=61975#p61975 (and on)

### PR DESCRIPTION
**Pull request by Bertram25**
And changed every reference in the code, in levels and in config accordingly.

For I left the forge wall items in place i the wait for new ones from Danimal.

Fixes #459

### CODE REVIEW

**Comment by Bertram25** [comment]
@Danimal696 As I badly wrote in the commit message above, I left the forge wall objects for now on the Workshop. The beast looks good in game. :)
I wonder whether you want the table to be rotated to 45° though. Just tell me what you prefer and I'll adapt accordingly. 

Do you think for instance it would look better if the creatures are rotated 45° also and placed so that we think they're facing the tables when working on traps?

**Comment by hwoarangmy** [comment]
> Shouldn't we remove the cannon trap from the starting skills and add it to the research to be done instead?

ok, I see no problem. The reason was more to test than to have the final behaviour. Now that the research logic is tested, you can go on with what is more logical

> Do you think for instance it would look better if the creatures are rotated 45° also and placed so that we think they're facing the tables when working on traps?

If the tables are rotated, it would be better to rotate the creatures, yes.

**Comment by Bertram25** [comment]
> ok, I see no problem. The reason was more to test than to have the final behaviour. Now that the research logic is tested, you can go on with what is more logical

That said, we should maybe let it as is in test maps since they're here for that.

> If the tables are rotated, it would be better to rotate the creatures, yes.

Depends on whether people prefer to have tables not rotated but I think I'll rotate the creatures if nobody else minds. ;)

**Comment by hwoarangmy** [comment]
> Depends on whether people prefer to have tables not rotated but I think I'll rotate the creatures if nobody else minds

Anyway, that's easy to revert if players complain so...

**Comment by akien-mga** [comment]
> Depends on whether people prefer to have tables not rotated but I think I'll rotate the creatures if nobody else minds. ;)

Let's rotate then ;)

**Comment by Bertram25** [comment]
0.5.0 will be cool guys. :sunglasses: Can't wait to have a lan with you all. ;)

**Comment by Danimal696** [comment]
yeah, it will be a nice touch to rotate creatures along with tables

**Comment by Bertram25** [comment]
Research Gui upgraded! :)

**Comment by akien-mga** [comment]
It's awesome! The new research GUI is really great. :-)

Some remarks on the workshop:
- The tables are properly rotated, but I think they are not positioned via their geometrical center, so they are now offset to the top and mess with wall objects:
  od-workshop
- If I may, how about rotation the tables by 30° instead of 45°? I think it could give a nice feel if they were not aligned on the diagonal.
- I haven't seen any creature go to the workshop by themselves to work, I just managed to get an orc working for one second by dropping him on the workshop. Is the logic already in place for that, or are creatures still looking for the forge?

**Comment by Bertram25** [comment]
Heya :)

@Danimal696 Btw, while I see it, the Grimoire, the Workshop ground and machine1 materials are all three triggering warnings. Same thing than #529 

@akien-mga 

> The tables are properly rotated, but I think they are not positioned via their geometrical center,

Yeah, you must be right.

> If I may, how about rotation the tables by 30° instead of 45°? I think it could give a nice feel if they were not aligned on the diagonal.

Sure, I'll try that and push something if it turns out well. :)

> I haven't seen any creature go to the workshop by themselves to work, I just managed to get an orc working for one second by dropping him on the workshop. Is the logic already in place for that, or are creatures still looking for the forge?

During my tests, I was able to make the creature produce several traps (when they are not hungry, not sleepy and not brooding - Man, those minions still believe it's a democracy -, and that at least a trap has been placed on map waiting for its crafted counterpart.)
So normally, it should be fine. I'll test again though, just in case.

Btw, your (dark) picture makes me think that we may want to try to later create a simple light source per room centered on the room latest shape, now that @oyvindln has fixed the light problem quite well using sane parameters for them.

**Comment by Danimal696** [comment]
Materials again? ok, ill fix it...

**Comment by hwoarangmy** [comment]
> Materials again? ok, ill fix it...

I think @oyvindln said he will handle the materials. But it would be nice to not add new materials with warnings again because he might not see them.

**Comment by akien-mga** [comment]
The buttons unlocked through research (rooms, traps, spells) are not reset when quitting a game, see #559.

**Comment by Bertram25** [comment]
Ok, I'm on it. Thanks for the feed-back. :)

**Comment by Bertram25** [comment]
Ah, btw, @Danimal696 didn't you say that the grimoire had animations?

**Comment by Danimal696** [comment]
yes, its called "Loop"

**Comment by Bertram25** [comment]
> yes, its called "Loop"

Ok, then I'll make it call that animation. :)

**Comment by hwoarangmy** [comment]
Works well. I merge

**Pull request merged**
