### PR TITLE
Allow to use the old minimap or the new one in the user settings

### PR DESCRIPTION
**Pull request by hwoarangmy**
The minimap can be changed in the settings. The new minimap will be chosen at the start of the next new game (no need to reload the executable)

### CODE REVIEW

**Comment by tomluchowski** [comment]
hwoarangmy : I can write much simpler version of culling switcher between Main window or both. All you must do is to change the number of corners supplied to the algorithm . ( 4 vs 8 )

**Comment by hwoarangmy** [comment]
Well, that's what I've done. The rest is just adapting code to guidelines. And I also moved the culling manager to the gamemode to avoid a failing assert because culling was still ongoing when the gamemap was cleared (at game quit).
The only thing that may look a bit more complex is the use of a bit array to cull tiles. But since there might be more than 1 culling manager, it's the simplest I can think of.

**Comment by akien-mga** [comment]
Code looks good :)

**Comment by akien-mga** [comment]
I'll run codespell once to see if I catch some typos.

**Pull request merged**
