### PR TITLE
Swords, hero version

### PR DESCRIPTION
**Pull request by Danimal696**

### CODE REVIEW

**Comment by hwoarangmy** [comment]
I've tested but the image file "T2SwordGoodNormal.jpg" you uploaded is jpg while the one in the material is png. Thus, I get an exception. Could you please upload the png version ?

**Comment by Danimal696** [comment]
my bad, that was the original map

**Comment by hwoarangmy** [comment]
good

**Comment by akien-mga** [comment]
Also missing credits update here.

**Pull request merged**
