### PR TITLE
Remove unused models, materials and textures

### LINKED ISSUE #579: Spring cleaning in the materials/ folder
It is currently relatively hard to know which texture is linked to which material, and which material is used in game or not.

According to @oyvindln's input on #492, most material IDs (defined in the materials/script/*.material files by the `material` tag) are referenced directly in the binary meshes. The we reference the meshes in the config/ files.

So basically to know the status for each material/model, we can:
- Check that every texture is used in a material script
- Extract the material IDs from the scripts
- Check the meshes against those material IDs to know if they're using them
- Check the meshes against the config files (and the code if there are some hardcoded meshes) to know which are used

We don't necessarily have to do exactly this for each step, since the data folders are not so huge so for most models we know if we see them in game already.
I'm just trying to single out the textures/models that we might not be using actually.

### PR DESCRIPTION
**Pull request by akien-mga**
As discussed extensively in #579.

This needs of course to be well tested to make sure it does add regressions if I removed textures that were needed in other materials, but normally I was careful.

I still have to check the logs for potential warnings or errors.

### CODE REVIEW

**Comment by akien-mga** [comment]
For the reference, comparing gz-compressed archives of the source repo we go from 89 MB before this PR to 76 MB after, so that's quite some space saved for distribution and installation.

**Comment by akien-mga** [comment]
Note that I kept local copies of all removed meshes and will make a PR to the media-source repo once we've settled on this one.

**Comment by akien-mga** [comment]
I've compared the logs between my branch and the current development branch, and I don't see anything new introduced by this PR, apart from the scripts that I removed and that are therefore not parsed when starting OD.

For the reference, to be able to use `diff` to compare two logs, you need to remove the time info with something like `sed -i 's/^.\{10\}//' ~/.local/share/opendungeons/opendungeons.log{,.1}`

**Comment by akien-mga** [comment]
I readded one of the materials in 54d21cf to fix a merge conflict with @Danimal696's PR, since I don't want him to panic over conflict resolution ;-)
Therefore I'll ask that my PR is merged first.

**Comment by oyvindln** [comment]
This seems to work fine for me at least, merging.

**Pull request merged**
