### PR TITLE
Add Roach, the new creature

### PR DESCRIPTION
**Pull request by Danimal696**
Shoulndt conflict with other PR´s, needs an entry to be created in
config file once the Creature skill PR is merged; spider one can be
copied but mesh size needs to be 0.15 in all 3 values.

### CODE REVIEW

**Comment by Bertram25** [comment]
Cool, eager to test that! :)

**Comment by Bertram25** [comment]
Looks good as far as I'm concerned. :)

**Comment by Danimal696** [comment]
unrelated to this, ill creepy-fy the Prison next, i got an artist hangover after finishing this and want to do something simple.

**Comment by akien-mga** [comment]
Merged, I'll do a PR to add it in-game (unless @hwoarangmy beats me to it, as I guess he has some commits waiting to be pushed already).

**Comment by akien-mga** [comment]
What would be suitable for the roach bed?

_Edit:_ I used the GoblinBed (hay bed).

**Pull request merged**
