### PR TITLE
Made the server tells clients what level to load...

### LINKED ISSUE #70: In multiplayer games, the clients should not choose the map. The server should tell them
The clients should check if they have the good map, maybe test some checksum, notify the server if everything is OK and disconnect if it is not the case.

### PR DESCRIPTION
**Pull request by Bertram25**
I also added:
- A check on the client nickname encoding.
- Checks and feedback against empty or too long nicknames, empty ip, empty selection.
- The server also checks the client version now before accepting it.

Fixes #70

### CODE REVIEW

**Comment by hwoarangmy** [comment]
I won't be there this week end so I will probably not be able to test this patch. From what I've read, everything seems ok. If @akien-mga tests and thinks it is correct, he can push :)

**Comment by Bertram25** [comment]
> I won't be there this week end

I won't likely be either (need some fresh air before winter. ;]).

**Comment by akien-mga** [comment]
@Bertram25 Should I wait for you to do the couple of changes that @hwoarangmy requested, or merge it as is and you'll do the changes later?

**Comment by Bertram25** [comment]
Let me do the change first. It's rather trivial. :)

**Comment by akien-mga** [comment]
I tested the new feature, it works as expected. I'll merge when the changes have been done.

**Comment by akien-mga** [comment]
Ah sorry I did not merge it sooner, I was expecting an email from github to tell me that a new commit as done :-)

**Comment by hwoarangmy** [comment]
no problem :)

**Comment by Bertram25** [comment]
This is true there is no mail in that case. Next time, I'll add a comment. Sorry. :)

**Pull request merged**
