### PR TITLE
Walls models for training hall

### PR DESCRIPTION
**Pull request by Danimal696**
these will replace the punching dummy, that should be converted to central
spots along the others.
Also its a sneak-peek at the weapons we will get when forge is coded.

### CODE REVIEW

**Comment by akien-mga** [comment]
It works great, I merge and I'll update the mesh format.

**Comment by Danimal696** [comment]
im using scite, i suppose i havent cheked all options needed

**Comment by akien-mga** [comment]
IIRC my Windows days 10+ years, Scite was quite good to edit code files, so it should have an option to use a monospace font indeed.

**Comment by Bertram25** [comment]
@Danimal696 Yes, there is an option to use a monospaced font, the option to use spaces instead of tabs is next to it, btw:
scite
Scite does exist for linux, while we're speaking about it.

**Pull request merged**
