### PR TITLE
Shared common code between rooms & traps + crash when quitting game with creatures in hand + fixed range fighters buggy behaviour

### PR DESCRIPTION
**Pull request by hwoarangmy**

### CODE REVIEW

**Comment by akien-mga** [comment]
I can confirm that the crash is fixed, I tested both skirmish and multiplayer games. As for the rest I don't see any obvious regression, I'll let @Bertram25 and @oyvindln review the code changes :-)

**Comment by Bertram25** [comment]
I have some:

Computing turn 956Removing object Room_Object_Farm6_507 in Building=Farm6
ERROR: Assert failed file /home/yohann/Projets/opendungeons/source/RoomHatchery.cpp line 248 info : tile=[94,85]
ERROR: Assert failed file /home/yohann/Projets/opendungeons/source/RoomHatchery.cpp line 248 info : tile=[82,85]
ERROR: Assert failed file /home/yohann/Projets/opendungeons/source/RoomHatchery.cpp line 356 info : tile=[94,85]
ERROR: Assert failed file /home/yohann/Projets/opendungeons/source/RoomHatchery.cpp line 356 info : tile=[82,85]

Again and again. I was playing in scream in the dark. Linked to that failed assertion, I had chicken coming from the bottom left of the map. XD
odscreenshot_1412296862

**Comment by hwoarangmy** [comment]
> I have some:

I don't think this is related to this PR. I've already seen asserts fail when the hatchery is destroyed. I couldn't see the root while reading code, through.
In you case, do you know if the chicken was in an attacked hatchery ?

**Comment by Bertram25** [comment]
The hatchery wasn't attacked as it was near the beginning of the game. Also, I am pretty sure it was my own hatchery as the other ones were having normal behaving chicken while my own remained empty.

Btw, I remember building a 3x3 hatchery and complete it with a 1x3 at the bottom to get a 3x4.

If this isn't to this PR, I believe you, though.
I'll open an issue and we'll merge, if you're ok with it. :)

**Comment by hwoarangmy** [comment]
I've already opened the issue. I confirm it is not linked to this PR as @Danimal696 reported it in the release. I think it is related to the RoomObject handling PR I've done previously. I will have a look ASAP.

**Comment by Bertram25** [comment]
Ok.:) but the warning is probably linked to the issue, right?
I'll add it there. Do you want to merge before investigating? :)

**Comment by hwoarangmy** [comment]
No, the failed assert was already there. I've already seen that when I let the game play alone to check for stability. But I was waiting for room destruction support to really have a look as it seems random and not easy to reproduce when enemy fighters are needed to attack the hatchery. Now that I've added support for that, I will have a deeper look.
I've also seen that if you destroy hatchery tiles where a chicken is (but not the one it is associated to), he will get stuck. I'll deal with that too.

**Comment by Bertram25** [comment]
Ok. But, lol, do you want me to merge this one? ;)

**Comment by hwoarangmy** [comment]
too late, I'll do it myself !!!
;)

**Pull request merged**
