### PR TITLE
Fixed compilation MSVS2013+MinGW and Traps crafting only when needed

### PR DESCRIPTION
**Pull request by hwoarangmy**

### CODE REVIEW

**Comment by Bertram25** [comment]
I had a game to test the trap change. To me it's working like a charm. :)

Once this PR will be in, the next thing needed will to make seeking dropped gold, crafted traps and corpse at a higher priority, but apart from that, it looks professional. :D

**Comment by hwoarangmy** [comment]
Don't hesitate to open an issue if you feel like it. It will avoid to forget (and I forget easily ^^)

**Comment by Bertram25** [comment]
Yep, I'll do it asap. :)

**Comment by Bertram25** [comment]
Done in #475

**Comment by hwoarangmy** [comment]
Since @Bertram25 tested it, I take the (big) responsability of merging because otherwise, I cannot test other PRs without changing the sources with MinGW.

**Comment by Bertram25** [comment]
Eh eh.

**Pull request merged**
