### PR TITLE
Speed up creature pickup/drop/marking tiles/build room/build trap

### LINKED ISSUE #103: Speed up server acknowledge when player ask pickup/drop creature or mark tiles

### PR DESCRIPTION
**Pull request by hwoarangmy**
@Bertram25 @akien-mga Please test a little bit more this one as usual because I changed some sensible stuff (see details in the commit). But it seems pretty stable as I let the game play alone during 3 hours and I had no crash (I stopped it turn 12517). I also tried quitting the mission and restarting it and fixed the related bug I've seen (mostly about treasury room)
fixes #103

### CODE REVIEW

**Comment by hwoarangmy** [comment]
BTW, now that creatures are not removed from the gamemap when picked up, they move (idle action) while in hand. I let this behaviour because I thought it was funny. If you prefer, I can make them stop. But, in some far away version, we could have some different animation for creatures in hand :)

**Comment by akien-mga** [comment]
> BTW, now that creatures are not removed from the gamemap when picked up, they move (idle action) while in hand. I let this behaviour because I thought it was funny. If you prefer, I can make them stop. But, in some far away version, we could have some different animation for creatures in hand :)

I like this! We could have animations of creatures kicking and roaring because they're angry that they're being grabbed :-D

**Comment by akien-mga** [comment]
> Speed up creature pickup/drop/marking tiles/build room/build trap

That's a huge improvement! All those actions are now done instantly in singleplayer, I'm looking forward to testing it in LAN :-)

**Comment by akien-mga** [comment]
I got a crash when expanding the existing treasury room on TestSingleplayer.level:

```
During this turn there were 92 calls to GameMap::path().Processing deletion queues on turn 187
Server sends newturn=187
ERROR: Assert failed file /home/akien/Projects/opendungeons/OpenDungeons/source/ODClient.cpp line 559 info : name=Treasury_2
signal 11 (Segmentation fault), address is 0x34 from 0x5c50b2

[bt]: (1) ./OpenDungeons.bin : ODClient::processOneClientSocketMessage()+0x752 [0x5c50b2]
[bt]: (2) ./OpenDungeons.bin : ODClient::processOneClientSocketMessage()+0x752 [0x5c50b2]
[bt]: (3) ./OpenDungeons.bin : ODClient::processClientSocketMessages()+0x20 [0x5dceb0]
[bt]: (4) ./OpenDungeons.bin : ODFrameListener::frameStarted(Ogre::FrameEvent const&)+0x192 [0x5e1f72]
[bt]: (5) /lib64/libOgreMain.so.1.9.0 : Ogre::Root::_fireFrameStarted(Ogre::FrameEvent&)+0x44 [0x7f1b5e2f8f04]
[bt]: (6) /lib64/libOgreMain.so.1.9.0 : Ogre::Root::_fireFrameStarted()+0x21 [0x7f1b5e2fa7e1]
[bt]: (7) /lib64/libOgreMain.so.1.9.0 : Ogre::Root::renderOneFrame()+0x9 [0x7f1b5e2fa8d9]
[bt]: (8) /lib64/libOgreMain.so.1.9.0 : Ogre::Root::startRendering()+0x2d [0x7f1b5e2fa92d]
[bt]: (9) ./OpenDungeons.bin : ODApplication::ODApplication()+0x3fc [0x5c3efc]
[bt]: (10) ./OpenDungeons.bin : main+0x1e [0x4682de]
[bt]: (11) /lib64/libc.so.6 : __libc_start_main+0xf0 [0x7f1b5b1eaf90]
[bt]: (12) ./OpenDungeons.bin() [0x4696f4]
```

It's easy to reproduce: just try to expand the treasury room.

**Comment by hwoarangmy** [comment]
> It's easy to reproduce: just try to expand the treasury room.

Stupid me, I forgot to test after my lastest changes. I see what's happening. Patch incoming soon. Like RoomObjects, I will change room absorption so that the new room absorbs treasury indicators instead of destroying/redoing all.

> I'm looking forward to testing it in LAN :-)

From what I've seen on the last lan, I would guess that should be nice :)

> We could have animations of creatures kicking and roaring because they're angry that they're being grabbed

Yes, that's also what I had in mind :)

> It could have been nice to split this commit into two or three functional commits

The problem is that they were linked. Every change there is the result of what I had to do to make the same logic for every

**Comment by hwoarangmy** [comment]
> Are they still doing their turn logic, animation apart?

When picked up, they are removed from the tile they were on. So they should not fight.Concerning their turn, nothing is done if the creature is not on map (a boolean set when pickup) :
https://github.com/hwoarangmy/OpenDungeons/blob/development/source/Creature.cpp#L539

But that's the main reason why I asked if it was possible to make some tests. I'm sure about the most obvious cases (creature turn and fighting) but there might be something more tricky that I didn't see...

**Comment by hwoarangmy** [comment]
> The question is: Are there cases where we do not want to "force" the name of a creature/trap/room?
> The boolean forceName sounds like a temporary solution for me, unless there are cases where the creature name shouldn't be touched, while the 'name' parameter isn't empty?

Generally speaking, there are 3 cases :
- Entity creation on server (during portal/dungeon temple turn for creature, for example) : the name is automatically set
- Entity creation on client side (when message is received) : the name has to be the same as the server's
- Entity created temporary : used for refreshing the entity (used for tile, creature, ...)

I don't really like the boolean solution either. But I couldn't think of something better. If you have an idea, please tell me. I will also think about it myself

**Comment by Bertram25** [comment]
> I don't really like the boolean solution either. But I couldn't think of something better. If you have an idea, please tell me. I will also think about it myself

Well, to be honest, I wondered whether simply forcing the entity name when the name is not empty would suffice, just like you implicitly did here for instance:
https://github.com/hwoarangmy/OpenDungeons/commit/11b384799a3b3fd0569a78a555843ef32dd14578#diff-ffe96aa9f153c9d8901adcfe3dd1d3dcR173

> But that's the main reason why I asked if it was possible to make some tests. I'm sure about the most obvious cases (creature turn and fighting) but there might be something more tricky that I didn't see...

Np, playing, err I mean testing is here for that. ;)
Seems not a lot of things can happen when they haven't got any position tiles anyway:
https://github.com/hwoarangmy/OpenDungeons/blob/development/source/Creature.cpp#L588

Regards,

**Comment by hwoarangmy** [comment]
> Seems not a lot of things can happen when they haven't got any position tiles anyway

There is something tricky. When you remove the creature from the tile, positionTile can not return NULL as you also need to set an invalid value in position because :
https://github.com/hwoarangmy/OpenDungeons/blob/development/source/Creature.cpp#L2652

**Comment by hwoarangmy** [comment]
From the start, looking at the treasury room, I've been thinking why treasures are not room objects ? Is that because they were static so it was not usefull to have the whole animated objects mecanisms ?

**Comment by Bertram25** [comment]
> From the start, looking at the treasury room, I've been thinking why treasures are not room objects ? Is that because they were static so it was not usefull to have the whole animated objects mecanisms ?

I think yes, and also because it was likely the oldest room coded explaining the code roughness there, maybe.
Note that there is no reason for them not to be room objects  (plus not-technically speaking they are), so they can become ones without any regret, IMHO.

> There is something tricky. When you remove the creature from the tile, positionTile can not return NULL as you also need to set an invalid value in position because :
> https://github.com/hwoarangmy/OpenDungeons/blob/development/source/Creature.cpp#L2652

Ah, of course, silly me. :)
If it happens to be needed, I wonder whether we could readd the boolean telling whether the creature "is on map", without actually removing it from the game map object, to disable a few things and clearly show its state. If bugs happen, I'd suggest we keep this in mind.

Good evening guys :)

**Comment by hwoarangmy** [comment]
> I wonder whether we could readd the boolean telling whether the creature "is on map", without actually removing it from the game map object

It exists (and I used him to stub doTurn when the creature is picked up). I also removed the creature from the tile it is in (from what I've seen, it will avoid enemy creatures to try to attack it). That's all I've seen. But there might be something hidden that I missed. Even as I said, we will have time to debug when the bug comes :) Anyway, it seems more logical to me to let a picked up creature in the gamemap as it is still part of it.

**Comment by Bertram25** [comment]
> It exists (and I used him to stub doTurn when the creature is picked up). I also removed the creature from the tile it is in (from what I've seen, it will avoid enemy creatures to try to attack it). That's all I've seen. But there might be something hidden that I missed. Even as I said, we will have time to debug when the bug comes :)

Ah? Sure, nevermind then. :)

> Anyway, it seems more logical to me to let a picked up creature in the gamemap as it is still part of it.

Agreed. And I'm sure less complicated to handle.

**Comment by hwoarangmy** [comment]
> Ah? Sure, nevermind then. :)

Yep :
https://github.com/hwoarangmy/OpenDungeons/blob/development/source/Creature.h#L337

> Agreed. And I'm sure less complicated to handle.

Yes. I reminded having seen somewhere where we checked for creatures in the gamemap and then in every player hands but I couldn't find it. I thought I had dreamed or something had been removed but I found it. It is in the goal keeping a creature alive. It's much simpler now :)

I made a new commit that uses room objects for treasury indicators. I think the bug is fixed. Please fill free to try :)
The other good thing is that if an artist wants to make effects (like having a gold bag that grows instead of removing the bag and adding a new one), it is possible

**Comment by akien-mga** [comment]
Crash fixed :-)
That's a nice code simplification. I'll let @Bertram25 do the final review before merging.

On a side note, the wall-claiming algorithm seems somewhat strange, creatures claim a wall, then go 10 tiles away to claim another one, then back, then to another location... But I'll open another issue for that (unless it's per design).

**Comment by Bertram25** [comment]
The question on whether we should get rid of the forceName boolean is still left to be seen, but i Think in another commit. :)

I'll merge.

**Pull request merged**
