### PR TITLE
Made the chat use a more readable font + The usual misc stuff ;)

### LINKED ISSUE #642: Monospace font for in-game chat
Monospace font for in-game chat since i think its better to read when you're playing, and not lot of time to read.

### PR DESCRIPTION
**Pull request by Bertram25**
I used LiberationBold.ttf - Red Hat - OFL License.

I also grouped the font files under the same folder.

Actually fixes #642

### CODE REVIEW

**Comment by akien-mga** [comment]
It works great, LiberationBold is a good choice and UTF-8 support seems pretty functional :)

I got a segfault in my server instance when a client (different instance of OD) disconnected:

```
Computing turn 24
During this turn there were 5 calls to GameMap::path().miscUpkeepTime=3125
Spawning a creature class=Kobold, name=Kobold12, seatId=5
SERVER - Adding Creature Kobold12, seatId=5
Server sends newturn=24
Client (eé&à^þ) received turnStarted=24
ERROR : Could not receive data from client status=2
Client (æ«€¶œþđðß) disconnected state=ready

Computing turn 25
During this turn there were 4 calls to GameMap::path().miscUpkeepTime=3557
Server sends newturn=25
signal 11 (Segmentation fault), address is 0x8 from 0x59cd50

Client (eé&à^þ) received turnStarted=25
[bt]: (1) ./opendungeons : ODSocketClient::send(ODPacket&)+0 [0x59cd50]
[bt]: (2) ./opendungeons : ODSocketClient::send(ODPacket&)+0 [0x59cd50]
[bt]: (3) ./opendungeons : ODServer::sendMsg(Player*, ODPacket&)+0xfe [0x5777fe]
[bt]: (4) ./opendungeons : ODServer::processServerNotifications()+0x336 [0x58de06]
[bt]: (5) ./opendungeons : ODServer::serverThread()+0x284 [0x58e944]
[bt]: (6) /lib64/libsfml-system.so.2.2.0 : +0x9478 [0x7f7951d27478]
[bt]: (7) /lib64/libpthread.so.0 : +0x75bd [0x7f79504f45bd]
[bt]: (8) /lib64/libc.so.6 : clone+0x6d [0x7f795101c5ed]
```

I don't think it's related to the funky UTF-8 names, but that might be worth checking :)

**Comment by Bertram25** [comment]
@akien-mga Is it reproducable without UTF-8 names? I had the similar thing once but couldn't reproduce and it was before adding that patch. (I'm still turning round it. Maybe I'll catch that one later on.)

**Comment by Bertram25** [comment]
@akien-mga I could reproduce your issue with 'Guest' and 'Host' as nickname in Scream in the Dark...

When Guest was on Seat 5 and Host on Seat1. I'll open an issue, but it seems not related to this PR.

**Comment by akien-mga** [comment]
> Is it reproducable without UTF-8 names?

It is, I just reproduced it with "Bob" and "Alice" as client names :)

**Comment by Bertram25** [comment]
Ok, I opened https://github.com/OpenDungeons/OpenDungeons/issues/662

**Comment by Bertram25** [comment]
Was a long time since I've heard of Bob and Alice again. XD

**Comment by hwoarangmy** [comment]
I will review that tomorrow. That's too late for turning the brain on ^^

**Comment by hwoarangmy** [comment]
Changes look good. I will test ASAP

**Comment by hwoarangmy** [comment]
I confirm the segfault is not related to this PR. Concerning the length not being accurate, that can be fixed in another PR. This one is already an improvement so I merge

**Comment by hwoarangmy** [comment]
@Bertram25 I will take care of the lenght bug seen by @akien-mga now that I have a PR to do

**Pull request merged**
