### PR TITLE
New creature definition and parser

### PR DESCRIPTION
**Pull request by Bertram25**

### CODE REVIEW

**Comment by hwoarangmy** [comment]
Seems interesting. I cannot test tonight but I will tomorrow :)

**Comment by hwoarangmy** [comment]
> We should still have a level or two having "weird" spawn pools to show spawn pools can be overridden

I completely agree. I think we should have test levels for each specific case (that's what I've tried to do so far). IMO, we should even keep them to test eventual regressions (maybe move them to some specific folder when we will have too many levels).

**Comment by hwoarangmy** [comment]
Resolving conflicts seems really complex with GitHub when the PR already exists...

**Comment by Bertram25** [comment]
> Resolving conflicts seems really complex with GitHub when the PR already exists...

Strange. I never had problems before?

Usually, in a given PRed branch, I do:

`git pull --rebase git://github.com/OpenDungeons/OpenDungeons.git development`
Resolve possible conflicts, and then:
`git push -f origin <my_branch>`

This usually does the trick for me.

I'll redo it as it seems needed...

**Comment by hwoarangmy** [comment]
> Strange. I never had problems before?

Yes but as you can see, many commits that where on the main repo have been added to your PR. Now, it lists 20 commits where there should be 3...

**Comment by Bertram25** [comment]
> Yes but as you can see, many commits that where on the main repo have been added to your PR. Now, it lists 20 commits where there should be 3...

Yep, I'm on it. :)

**Comment by Bertram25** [comment]
It's done, I cleaned up the branch. (Had to summon a bit of interactive rebasing.)

**Comment by hwoarangmy** [comment]
Interesting. Can you tell me how you removed the unwanted commits ?

BTW : I'm gonna test your patch right now

**Comment by hwoarangmy** [comment]
You have added a mandatory file in the config folder but the link is not automatically created as it is for the other folders. Could you add it in CMakeCache.txt ?

BTW, I was thinking that it could be nice to have a starting HP (ie at level 1). That would allow to have weaker creatures with good evolution (bad at level 1, good at level 30) and others at the opposite. It's just a thought, nothing to do with your PR.

Apart from the link, it works well and I could see the creatures stats as expected (according to the definition file). Good job ^^

**Comment by Bertram25** [comment]
> Interesting. Can you tell me how you removed the unwanted commits ?

Step by step, from the local new_parser branch, I did:
git pull --rebase git://github.com/OpenDungeons/OpenDungeons.git development

Due to the intertwined nature of our patches, there was a patch from oln giving conflicts, for no apparent reason (Probably because of a merge point getting in the way, IMO).
I fixed the conflicts by hand so that the code was as in the development branch, used git add to state the files as resolved, and did git rebase --continue 

Once all that was done, I had my three commits + one due to the conflict. As this one was unnecessary (since it was differences left between my branch and the development one that I left by mistakes), I did a git rebase -i with the commit hash before that one.
And then removed it when the text editor asked what to do with the commits.

The rebase went on and I had only my three commits.
I did: git push -f origin new_parser
and it was done.

> You have added a mandatory file in the config folder but the link is not automatically created as it is for the other folders. Could you add it in CMakeCache.txt ?

Oops, you're right,  I'll do it.

> BTW, I was thinking that it could be nice to have a starting HP (ie at level 1). That would allow to have weaker creatures with good evolution (bad at level 1, good at level 30) and others at the opposite. It's just a thought, nothing to do with your PR.

AFAIK I'm almost sure that's planned in #152 already :) Feel free to check there if you see something needing discussion.

> Apart from the link, it works well and I could see the creatures stats as expected (according to the definition file). Good job ^^

Cool :)

**Comment by Bertram25** [comment]
It should be ok now. :)

**Comment by hwoarangmy** [comment]
Thanks for the explanation. I'll test tonight

**Comment by hwoarangmy** [comment]
> The rebase went on and I had only my three commits.

All the commits attached to the PR were gone ?

**Pull request merged**
