### PR TITLE
Move removal of some warnings to the OD_OPT_FLAGS variable on MinGW

### PR DESCRIPTION
**Pull request by akien-mga**
As discussed on https://github.com/OpenDungeons/OpenDungeons/commit/8299752bf611159a5f9d7dedc974d470349786b6#commitcomment-7948989

### CODE REVIEW

**Comment by Bertram25** [comment]
Is fine for me. @hwoarangmy will surely have a closer look. :)

**Comment by akien-mga** [comment]
Yes I would like to know if those warnings should be disabled only for MinGW (as done previously), or if it would also be relevant to disable them on all GCC platforms.

**Comment by Bertram25** [comment]
I'll try a full compile shortly. :)

**Comment by Bertram25** [comment]
I've got the same root making @hwoarangmy request for disabling certain warnings. I'd say yes for every gcc, at least for now.

**Comment by Bertram25** [comment]
> I've got the same root making @hwoarangmy request for disabling certain warnings. I'd say yes for every gcc, at least for now.

@akien-mga Nevermind what I said, I'm fixing all reordering warnings + some bonus. ;)

**Comment by Bertram25** [comment]
I've added the reordering fix in #190 
For GCC, I think you can let -Wall alone. Only the AS strict-aliasing warnings are left AFAIK.
(And those can't be removed like that IIRC.)

**Comment by hwoarangmy** [comment]
Ok, I had not seen the discussion on the warning philosophy, sorry for using a non suited flag. If you feel it's better like this, I have nothing to say.

**Comment by Bertram25** [comment]
Np, :) Merging...

**Pull request merged**
