### PR TITLE
Improve quick help and update release notes

### PR DESCRIPTION
**Pull request by akien-mga**
In the end there wasn't much to do for the quick help, as the version for 0.5.0 already mentioned the need for a library to research spells, etc.. We just made the concept evolve a lot and become way cooler, but the basic instructions remain similar :)

### CODE REVIEW

**Comment by akien-mga** [comment]
I've also changed the funny "Lan Solo" to something more boring, but that should be more international. After discussing it with @alketii, it seems that the use of the name "Lan" to refer to any kind of multiplayer game with friends is particularly French ;)

"LAN" is only "Local Area Network", so it doesn't accurate refer to "playing online with acquaintances". Actually "WAN" would already be more accurate ("Wide Area Network"), but also less understandable IMO. So I'm using "Multiplayer Levels" instead, though I liked the Star Wars reference better :p

**Comment by akien-mga** [comment]
I've also reduced the inactive doors opacity, as I found it hard to see the difference between active and inactive doors during our LAN... er, WAN game I mean :p

**Comment by hwoarangmy** [comment]
Works well. I will let @Bertram25 review and merge. Congrats for the text, it's nice ^^

**Comment by Bertram25** [comment]
Let's merge :)

**Pull request merged**
