### PR TITLE
Several cleanups and improvements

### PR DESCRIPTION
**Pull request by Bertram25**
- Improved music handling and added cross-fade support.
- Made the level music loaded from a level parameter.
- Improved the sound handling code to better handle future interface sounds and creature states.
- Added menu click sounds.
- While seeing it, removed the creature mana, mana per level, and max mana stat.

### CODE REVIEW

**Comment by Bertram25** [comment]
@hwoarangmy @akien-mga Feel free to have a look guys. :)

**Comment by akien-mga** [comment]
Later today hopefully :-)
Now's the last rush for my internship memoir :-D

**Comment by Bertram25** [comment]
> Now's the last rush for my internship memoir :-D

Best of luck :D

**Comment by hwoarangmy** [comment]
The game compiles. I cannot really test sounds but I trust you. Concerning map info, you say it is displayed in level loading screen. Where is it displayed ?

EDIT : Sorry, I missread your post. This PR is about sound. I merge then

**Pull request merged**
