### PR TITLE
Added support to optionally select lan levels from the skirmish menu.

### PR DESCRIPTION
**Pull request by Bertram25**
Based on the idea of @akien-mga ;)

Part of #696 and #383

What's left for #696 is to merge the redundant levels now.

### CODE REVIEW

**Comment by hwoarangmy** [comment]
I will try tonight

**Comment by akien-mga** [comment]
Works great! :)

**Comment by hwoarangmy** [comment]
Seems like there is a difference with the combo box I used in the lobby. In the lobby, the selected element starts highlighted and the elements get highlighted when hovered. In the skirmish, it doesn't work. However, the combos are created in code IIRC so I don't know what's the difference

**Comment by Bertram25** [comment]
> Seems like there is a difference with the combo box I used in the lobby. In the lobby, the selected element starts highlighted and the elements get highlighted when hovered. In the skirmish, it doesn't work. However, the combos are created in code IIRC so I don't know what's the difference

AFAIK, in your comboboxes, you added a selectionbrush. I didn't because I thought it didn't matter, but I will have a look now.

**Comment by hwoarangmy** [comment]
> AFAIK, in your comboboxes, you added a selectionbrush

Now that you talk about it, that's correct, I added it ^^

**Comment by Bertram25** [comment]
Should be fixed now. :)

**Comment by hwoarangmy** [comment]
testing

**Comment by hwoarangmy** [comment]
perfect. I merge

**Pull request merged**
