### PR TITLE
Added support to play sounds + small fixes

### PR DESCRIPTION
**Pull request by hwoarangmy**
Now, sounds are loaded at game start and creature sound and interface sounds are played randomly depending on the path they are.

For creatures, I've used the same sounds for all. I've also added at least 1 sound per possible event and checked that they are triggered.

@Danimal696 Now, you can play with sounds as it is configurable through creatures.cfg

### CODE REVIEW

**Comment by akien-mga** [comment]
Christmas coming early! It builds and seems to run fine, I'll test it more thoroughly later today or tomorrow.

**Comment by hwoarangmy** [comment]
I've fixed requested changes

> I'll test it more thoroughly later today or tomorrow.

Do not hesitate to create new directories (1 to 3 levels) and to check that sounds are correctly played. If you have any doubts, note that you can check in the logs the sounds that were loaded at game load (with the corresponding path)

**Comment by Danimal696** [comment]
Nice ;D

**Comment by Bertram25** [comment]
Looks really cool! :D 
The overall change looks fine (@akien-mga has done most of the review job btw. ;])

I'll test all that asap, and I guess the next job is to populate the creature folder with new sounds and that's really awesome!

**Comment by akien-mga** [comment]
I've played a longer game to test the new sounds, it's really cool! It opens tons of possibilities to give personalities to our creatures and to add sounds for cannons, etc. Of course the config will have to be fine-tuned, right now tentacles dying with a human "Aaaargh" is a bit weird ;-)

**Comment by Bertram25** [comment]
I tried a game with custom (completely non-fitting) sounds last night. So far, it was working as for me.
I didn't have the time to properly test the other fixes though, but if @akien-mga is ok with the changes, let's merge.

**Comment by akien-mga** [comment]
Let's merge then. The only remaining question is about the dig confirmation sound that I don't hear anymore, but we'll sort it out later.

**Pull request merged**
