### PR TITLE
Improved a bit the keeper's portal vortex look.

### PR DESCRIPTION
**Pull request by Bertram25**
I also prepared vortexes for the two faction so they can later be used
with the next-gen portals.

### CODE REVIEW

**Comment by akien-mga** [comment]
It looks fine. I'm not so fond of our portal overall though, a flat 2D vortex in such a massive stone building doesn't look that great. Depending on the camera view, either you don't see the portal because it's too thin or it's hidden by the portal building.

Could we maybe replace the flat vortex by a spherical vortex? It would instantly give a better impression IMO, since it would look fine under all angles. WDYT @Danimal696 ?

**Comment by Danimal696** [comment]
we could make a textured, transparent orb and animate its texture. do you have any concept art or image of what you would like?

**Comment by Bertram25** [comment]
> It looks fine. I'm not so fond of our portal overall though, a flat 2D vortex in such a massive stone building doesn't look that great. Depending on the camera view, either you don't see the portal because it's too thin or it's hidden by the portal building.

Glad you tested it, even if it didn't win your heart. ;)

> Could we maybe replace the flat vortex by a spherical vortex? It would instantly give a better impression IMO, since it would look fine under all angles. WDYT @Danimal696 ?

Good idea while doesn't the temple already has such sphere concept? (Or maybe the temple is planned for a change?)
What about this sphere type?
http://vignette3.wikia.nocookie.net/bleachfanfiction/images/8/81/3752709-magic-sphere.jpg/revision/latest?cb=20121216215317
http://michaelmalpass.com/wp-content/gallery/sphere-gallery/mark-welded-bronze-rod-18-d-1988-version-2.jpg

Best regards, :)

Btw, I think I'll close this PR once we have decided how to proceed...

**Comment by akien-mga** [comment]
IMO we can merge your PR, and work on improving the model afterwards. Your PR is already an improvements, it's the general model that I'm complaining about ;)

**Comment by hwoarangmy** [comment]
@Bertram25 Needs rebasing ^^

**Comment by Bertram25** [comment]
Ok, I'll rebase tomorrow morning. :)

**Comment by akien-mga** [comment]
If you want to play with OgreXMLConverter, you can have a look at fixing the material name in the PortalObject.mesh:

```
$ OgreXMLConverter -e PortalObject.mesh
$ YOUR_EDITOR PortalObject.mesh.xml   // Change "Portalvortex" to "PortalVortex"
$ OgreXMLConverter -e PortalObject.mesh.xml
```

**Comment by Bertram25** [comment]
Rebased, added only one portal type since it will be replaced and adapted the mesh file so that the material name is Portal**V**ortex.

**Comment by akien-mga** [comment]
Looks good, I merge :-)

> and adapted the mesh file so that the material name is PortalVortex.

Thanks for the maniac that I am :-P

**Pull request merged**
