### PR TITLE
Fixed lava and water tiles animation

### PR DESCRIPTION
**Pull request by hwoarangmy**
I will upload the blender source file as soon as I've downloaded the media repo to create a PR.

@Bertram25 @Danimal696 How should I update the media repo ? By merging the PR myself ? Or waiting for someone to do it ?

Note that as I've said in the forum, I've re-made the water/lava tileset for this PR. But I've also upgraded one of the tiles from the old one where the black holes were not fixed.

### CODE REVIEW

**Comment by Danimal696** [comment]
i dont think it would be wise anyone checking my incoming huge pack upload, ill trust you on this one, just merge yourself

**Comment by Bertram25** [comment]
+1 we both trust you on such simple matter.

**Comment by hwoarangmy** [comment]
> i dont think it would be wise anyone checking my incoming huge pack upload, ill trust you on this one, just merge yourself

ok. But please don't erase my tileset then. And if want to work on it, please us my version once it is online

**Comment by hwoarangmy** [comment]
I've uploaded the tileset on the media repo

**Comment by akien-mga** [comment]
Awesome work @hwoarangmy, this is a really nice fix for 0.6.0.

**Comment by hwoarangmy** [comment]
thanks

**Pull request merged**
