### PR TITLE
small fixes

### PR DESCRIPTION
**Pull request by hwoarangmy**

### CODE REVIEW

**Comment by Bertram25** [comment]
I confirm the overlay changes are working great.
The settings workaround is unfortunate while necessary, but hopefully I'll fix that somewhen. ;)
As for the other fixes, well, I can only trust you upon them. :) To me, it's mergeable.

**Comment by Bertram25** [comment]
> Note that I'm running OD with CEGUI 0.8.4, Ogre 1.9, SFML 2.3.1, boost 1.55 (BTW, it might be a good thing to add something about it in the release notes, no ?)

About the deps? Yes, even if the readme is the most common place for that usually.

**Comment by hwoarangmy** [comment]
@Bertram25 I'm done with this PR. If you see no problem, I will build a RC2 once it is in ^^

**Comment by Bertram25** [comment]
k. Let's merge! :)

**Pull request merged**
