### PR TITLE
Allow portal wave to be more configurable.

### PR DESCRIPTION
**Pull request by hwoarangmy**
It allows:
- To add a range. The portal wave will attack players that claimed a tile within range only
- To add a strategy. It can be closest dungeon, random or fixed team. Note that if fixed team, the strategy will be to attack the closest dungeon of the given team.

@akien-mga I didn't change your new level so that you can update it as you wish. I guess you know the code well enough now to understand how to configure the portal ^^

### CODE REVIEW

**Comment by Bertram25** [comment]
Code looks good. I'll have one game more and try to see whether there are differences but I guess the real test can only be done once @akien-mga has changed the wave strategy in his level. (Maybe I'll try to change it myself, too, to test.)

**Comment by akien-mga** [comment]
Looks like a present for me :-D I'll test it and try adapting my level right now :)

**Comment by hwoarangmy** [comment]
> I guess the real test can only be done once @akien-mga has changed the wave strategy in his level

You can also test o the 2v2 skirmish small test map by using a really small radius and see nobody getting attacked or a radius = 3 and see you will get attacked when you claim the wall nearby ^^

**Comment by Bertram25** [comment]
> You can also test o the 2v2 skirmish small test map by using a really small radius and see nobody getting attacked or a radius = 3 and see you will get attacked when you claim the wall nearby ^^

Ah, yes, an even better one. I'll try all that tonight.
I've done a second pass on the code just now. I noticed a big if but I think it is justified in the current code form for now. The rest of the logic looks straightforward and good to me. :)

Once tests are done, this mergeable as for me. :) Great stuff.

**Comment by akien-mga** [comment]
It works great :-) To test it on the new map, this seems sufficient:

```
diff --git a/levels/multiplayer/RuinsOfTheConfluent.level b/levels/multiplayer/RuinsOfTheConfluent.level
index 360ad8d..9a6cd13 100644
--- a/levels/multiplayer/RuinsOfTheConfluent.level
+++ b/levels/multiplayer/RuinsOfTheConfluent.level
@@ -1953,7 +1953,7 @@ ProtectDungeonTemple      NULL
 30     28
 30     29
 30     30
-9      250     0       0       -
+9      250     1       0       -
 [Waves]
 [Wave]
 SpawnTurnMin   0
```

**Comment by Bertram25** [comment]
Let's merge then. :)

**Pull request merged**
