### PR TITLE
Fix too many parameters for some lighting values + upgrade meshes

### LINKED ISSUE #606: Too many parameters for material light values in material files
```
Compiler error: fewer parameters expected in Hammock.material(21): ambient must have at most 4 parameters
```

This happens for a lot of materials. 
From #593.
Please check log before merging next time.

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #606

### CODE REVIEW

**Comment by akien-mga** [comment]
BTW I've had a look at the warnings about outdated format, like:
`18:47:04: WARNING: Defender.mesh is an older format ([MeshSerializer_v1.41]); you should upgrade it as soon as possible using the OgreMeshUpgrade tool.`

But OgreMeshUpgrade does not seem to work on our meshes (or on my system), I get:

```
$ OgreMeshUpgrader models/WorkshopMachine1.mesh 
Creating resource group General
Creating resource group Internal
Creating resource group Autodetect
Registering ResourceManager for type Material
Registering ResourceManager for type Skeleton
Registering ResourceManager for type Mesh
Exception caught: Unexpected error while reading file models/WorkshopMachine1.meshUnregistering ResourceManager for type Mesh
Unregistering ResourceManager for type Skeleton
Unregistering ResourceManager for type Material
```

Anyone manages to use OgreMeshUpgrader?

**Comment by oyvindln** [comment]
I have the same issue with OgreMeshUpgrader, I think it's a bug. Using ogreXmlConverter to and back from xml does work though.

**Comment by akien-mga** [comment]
I've tried converting to and back from XML with OgreXMLConverter, it works fine and the warnings disappear, but the files seem to have changed a lot:

```
$ git diff --stat
 models/Bookcase.mesh         | Bin 115354 -> 257024 bytes
 models/Bookshelf.mesh        | Bin 28584 -> 52569 bytes
 models/CaveHornet.mesh       | Bin 173304 -> 501417 bytes
 models/Defender.mesh         | Bin 758944 -> 2130624 bytes
 models/Goblin.mesh           | Bin 470012 -> 1228316 bytes
 models/GoblinBed.mesh        | Bin 6888 -> 24917 bytes
 models/PortalObject.mesh     | Bin 148652 -> 337547 bytes
 models/RangerBed.mesh        | Bin 26820 -> 84099 bytes
 models/SmallSpider.mesh      | Bin 29143 -> 76384 bytes
 models/Spider.mesh           | Bin 121552 -> 342853 bytes
 models/Spiderbed.mesh        | Bin 7332 -> 13622 bytes
 models/TrainingDummy4.mesh   | Bin 76176 -> 126519 bytes
 models/TrollBed.mesh         | Bin 57112 -> 152441 bytes
 models/Workshop.mesh         | Bin 418 -> 684 bytes
 models/WorkshopMachine1.mesh | Bin 64322 -> 121935 bytes
 15 files changed, 0 insertions(+), 0 deletions(-)
```

I don't know if that's the right solution, or if the tool messes up the files. For example it always complains that it can't find the .skeleton file even though it's in the same folder.

**Comment by hwoarangmy** [comment]
Well, I guess that if you test and see no regression on animations or on the models, it should be good. Usually, that's the kind of thing that works or breaks everything.

**Comment by akien-mga** [comment]
Well it works and the models seem to look good, but I wonder why they would be twice as big or more after the change, so I wonder if using OgreXMLConverter back and force does a clean job or adds junk metadata to the model.

Could you try with the Windows OgreMeshUpdater.exe to see if it works better than the Linux version?

**Comment by hwoarangmy** [comment]
I have tried OgreMeshUpgrader and it works. I have the same message telling the skeleton is missing (even if in the same folder) but it works. I tried on Spider.mesh and I have the same result as you do (119kb -> 335kb). However, the warning message disappears.

**Comment by hwoarangmy** [comment]
After googleing a bit, I've found that OgreMeshUpgrader creates an "edge list" by default. If you disable it, (by using -e), you will get a mesh with the same size ^^
It seems like the edge list is used for stencil shadows. As we don't use shadows, that might not be needed.

**Comment by akien-mga** [comment]
> After googleing a bit, I've found that OgreMeshUpgrader creates the "edge list" by default. If you disable it, (by using -e), you will get a mesh with the same size ^^

Nice, well spotted! I'll use -e for now then, we can see later on if we want to make use of these edge lists (the help says it's used for "stencil shadows").

**Comment by akien-mga** [comment]
Here is the new diff, basically the upgrade removed one byte from every model, and that's all :-)

```
$ git diff --stat
 models/Bookcase.mesh         | Bin 115354 -> 115353 bytes
 models/Bookshelf.mesh        | Bin 28584 -> 28583 bytes
 models/CaveHornet.mesh       | Bin 173304 -> 173303 bytes
 models/Defender.mesh         | Bin 758944 -> 758943 bytes
 models/Goblin.mesh           | Bin 470012 -> 470011 bytes
 models/GoblinBed.mesh        | Bin 6888 -> 6887 bytes
 models/PortalObject.mesh     | Bin 148652 -> 148651 bytes
 models/RangerBed.mesh        | Bin 26820 -> 26819 bytes
 models/SmallSpider.mesh      | Bin 29143 -> 29142 bytes
 models/Spider.mesh           | Bin 121552 -> 121551 bytes
 models/Spiderbed.mesh        | Bin 7332 -> 7331 bytes
 models/TrainingDummy4.mesh   | Bin 76176 -> 76175 bytes
 models/TrollBed.mesh         | Bin 57112 -> 57111 bytes
 models/Workshop.mesh         | Bin 418 -> 417 bytes
 models/WorkshopMachine1.mesh | Bin 64322 -> 64321 bytes
 15 files changed, 0 insertions(+), 0 deletions(-)
```

**Comment by akien-mga** [comment]
So, I added a commit to upgrade the models. No warnings anymore, and they still look fine in game from what I could see.

**Comment by oyvindln** [comment]
> It seems like the edge list is used for stencil shadows. As we don't use shadows, that might not be needed.

It takes like one line of code to turn them on though, if we want to.

**Comment by hwoarangmy** [comment]
> It takes like one line of code to turn them on though, if we want to.

My feeling is that it might decrease significantly the FPS. But after all, why not if it is not the case and it renders well... We will see when we will get there ^^

**Comment by Bertram25** [comment]
Once @akien-mga 's PR is merged, I'll work on improving the portal vortex look a bit. :)

**Comment by hwoarangmy** [comment]
Testing right now

**Comment by Bertram25** [comment]
Works fine IMHO.

**Comment by hwoarangmy** [comment]
I have no more error in the logs. I merge

**Pull request merged**
