### PR TITLE
Room trap config files

### PR DESCRIPTION
**Pull request by hwoarangmy**

### CODE REVIEW

**Comment by akien-mga** [comment]
And he just opened issue 300! This... is... hwoarangmy!

Note that this PR is based off @hwoarangmy's #298, so the latter should be pushed before the former I guess.

**Comment by Bertram25** [comment]
> Note that this PR is based off @hwoarangmy's #298, so the latter should be pushed before the former I guess.

In fact, if we merge this one, #298 will be obsolete. But if we merge #298 this one will have to be rebased.

**Comment by hwoarangmy** [comment]
> In fact, if we merge this one, #298 will be obsolete. But if we merge #298 this one will have to be rebased.

Ok. I wanted to see what happened if I create a branch (that's the first time I try). Seems like I should have started from my original repo ^^

> @hwoarangmy I will definitely not play against you tonight. You're in Chuck Norris mode!

That's a pretty straight forward PR this time (but I agree, not the #298). As you said, if the former one is ok, please integrate it so I can rebase this one ^^
I prefer to not have obsolete PR.

**Comment by akien-mga** [comment]
> Ok. I wanted to see what happened if I create a branch (that's the first time I try). Seems like I should have started from my original repo ^^

Here I defined an "upstream" remote that points to the official development branch, and I checkout and update this branch before creating a custom branch, this way I'm in sync with the current OpenDungeons/development.

Of course if you second pull request impacted some files that are part of the first one, it won't prevent from having merge conflicts, and you will be working on potential self-obsoleted code :-)

**Comment by Bertram25** [comment]
#298 has been merged. You can rebase :)

**Comment by hwoarangmy** [comment]
It's done ^^

**Comment by Bertram25** [comment]
Nothing to say. Ready to be merged IMHO.
I'll let @akien-mga give his word, too.

**Comment by akien-mga** [comment]
Testing now, and merging afterwards.

**Comment by akien-mga** [comment]
I love how easy to configure OD is becoming :-D
Modders will love us ;-)

**Pull request merged**
