### PR TITLE
New workbench

### PR DESCRIPTION
**Pull request by Danimal696**
i messed up my repository so i had to close the last commit, this should
be fine

### CODE REVIEW

**Comment by Danimal696** [comment]
this material is based on the ones corrected by a script in another patch, so that could be a big problem

**Comment by akien-mga** [comment]
> this material is based on the ones corrected by a script in another patch, so that could be a big problem

I guess you mean based on my PR #611.
Actually WorkshopMachine1.material was not changed in this PR, but indeed it has 4 parameters for all lighting values. Can you fix WorkshopMachine1 and WorkshopMachine2 at the same time?

**Comment by Bertram25** [comment]
I'm still freshly catching up here, but from the Ogre doc:
http://www.ogre3d.org/docs/manual/manual_16.html

```
Format: ambient (<red> <green> <blue> [<alpha>]| vertexcolour)
Format: diffuse (<red> <green> <blue> [<alpha>]| vertexcolour)
Format: specular (<red> <green> <blue> [<alpha>]| vertexcolour) <shininess>
Format: emissive (<red> <green> <blue> [<alpha>]| vertexcolour)
```

So, only the specular can have a potential 5th parameter. Btw, the specular format is making ambiguous at whether the fourth value is an alpha value or an sininess value, since the alpha value is not mandatory, but that's another problem. So, to make it simple, I'd propose you stick to this format @Danimal696 :

```
ambient <red> <green> <blue> <alpha>
diffuse <red> <green> <blue> <alpha>
specular <red> <green> <blue> <alpha> <shininess>
emissive <red> <green> <blue> <alpha>
```

WDYT everyone?

**Comment by Danimal696** [comment]
OK

**Comment by hwoarangmy** [comment]
I think it usually is a good thing to write all values as it makes obvious it is not a forgotten parameter

**Comment by Bertram25** [comment]
Agreed. I know this is all obvious stuff but it can't hurt being described once. @Danimal696 Mind fixing it now you have a working format above?

**Comment by Danimal696** [comment]
later, not thrilled up at all to fix 40+ materials, tomorrow ill fix this one at least

**Comment by akien-mga** [comment]
I think he meant fixing the new workbench (and the first one), I already fixed many of the other materials.

**Comment by Bertram25** [comment]
Yes, only fixing the two materials, not the other ones. :)

**Comment by Bertram25** [comment]
If you want, one of us can fix the materials. On the other hand, we'll need the new files licensing. ;)

**Comment by Danimal696** [comment]
you can have all the merits, just spare me the pain... :,(

**Comment by akien-mga** [comment]
> you can have all the merits, just spare me the pain... :,(

I guess @Bertram25 was referring to the CREDITS and not to the merits for the work done ;-)
But I'll spare you the pain and merge this one, I will handle the needed material fixes and CREDITS update in my PR (your previous branch CREDITS change were lost for this PR but they can still be seen here: https://github.com/Danimal696/OpenDungeons/commit/12ca53af56b3e453a6dc1317031f226f68b9c512 ).

**Comment by Danimal696** [comment]
thanks

**Comment by Bertram25** [comment]
> >  you can have all the merits, just spare me the pain... :,(
> 
> I guess @Bertram25 was referring to the CREDITS and not to the merits for the work done ;-)
> But I'll spare you the pain and merge this one, I will handle the needed material fixes and CREDITS update in my PR (your previous branch CREDITS change were lost for this PR but they can still be seen here: Danimal696@12ca53a ).

Eh eh. Don't worry @Danimal696 :) For all the models you permitted us to see live in game, I don't doubt about your merit or anyone's merit in the team, btw.

And yeah, technical and boring stuff about materials (and credits) is a necessary discipline to get things working. It's cool @akien-mga got your back about that. :D 
I'll try to open a wiki page about that (how to use tools to edit meshes links, what is a good material, ...) if nobody else does before me.

**Pull request merged**
