### PR TITLE
Allow changing renderer in the settings window + integrate HLSL D3D renderer for windows

### LINKED ISSUE #799: Cannot change to D3D renderer
By default, OpenGL renderer is selected (which is fine). But when we go to the settings and choose D3D renderer, nothing happens and after restarting, OpenGL renderer is selected again.

### PR DESCRIPTION
**Pull request by hwoarangmy**
fixes #799

### CODE REVIEW

**Comment by Bertram25** [comment]
About the code, I think it's a way to handle that right away, but in term of user experience, I'd rather make it so OD ask the user whether he agrees to restart right away before restarting.
I can have a go at adding a pop up after your change if you're ok with it.

We'd still have to develop a custom config setting IMHO as sound settings and one day keys, etc will need that.

**Comment by Bertram25** [comment]
I can't test on linux but it compiles fine and the D3D renderer isn't available on linux as expected, so I'll merge.

**Comment by hwoarangmy** [comment]
> in term of user experience, I'd rather make it so OD ask the user whether he agrees to restart right away before restarting.

I agree. I just didn't feel like doing it ^^

> I can have a go at adding a pop up after your change if you're ok with it.

Yes, please.

> We'd still have to develop a custom config setting IMHO as sound settings and one day keys, etc will need that.

Indeed

**Comment by Bertram25** [comment]
> I agree. I just didn't feel like doing it ^^

Don't worry, you don't have to do everything. I know I'm slow but I'll stick around killing my tasks little by little. :)
Ok, I'll add a popup.

Then, I'll be on user config support.

**Pull request merged**
