### PR TITLE
Started dealing with #91

### PR DESCRIPTION
**Pull request by Bertram25**
- Added missing copyright headers. The issue milestone can be set to Later, afterwards.
- Also cleaned up the prefix tree class and fixed the DummyArrayClass variable name.

Part of #91

### CODE REVIEW

**Comment by akien-mga** [comment]
It builds fine (I wanted to make sure since you removed some includes), no obvious regressions.

**Comment by hwoarangmy** [comment]
> It builds fine (I wanted to make sure since you removed some includes), no obvious regressions.

It is always good to try to build the game and launch it. Sometimes, it is hard to see the consequences of a patch. But I believe the less we could expect from a repository, even the development branch, is to compile and launch
Akien, I let you deal with that :)

**Comment by Bertram25** [comment]
> It builds fine (I wanted to make sure since you removed some includes)

Yep, but I only removed includes in the cpp file that were already in the header, in fact.
I also tested the prefix tree on linux by opening the console, type the start of a command listed in:
https://github.com/OpenDungeons/OpenDungeons/blob/development/config/console_commands.txt
and press tab several times to see it completed by the possible commands.

Feel free to merge whenever you think this is ok. :)

**Comment by akien-mga** [comment]
I've proofread the code (that was interesting since I don't know C++, but I did not spot any obvious issue in the little I could understand with general programming languages knowledge). Let's merge :-)

I shall take some time to learn the basics of C++ to be more confident reading OD code. I'm on Lua for now though :-)

**Comment by Bertram25** [comment]
> I shall take some time to learn the basics of C++ to be more confident reading OD code. I'm on Lua for now though :-)

Beware, you're becoming more and more a developer every passing day.

@hwoarangmy ^ What have we done, we might have created a monster. O.O' ;)

**Comment by akien-mga** [comment]
Don't you worry, I'm still _Akien the Archlich, evil torturer of the shallow devs_ (i.e. lead bug hunter in the team) ;-)

**Comment by Bertram25** [comment]
> leader bug hunter in the team

Joke apart, this is very true. I saw that also on VT, btw. ;)

**Comment by hwoarangmy** [comment]
> What have we done, we might have created a monster. O.O' ;)

lol

> lead bug hunter in the team

Yes, and we have to say you do that well :)

> I shall take some time to learn the basics of C++ to be more confident reading OD code

If you already know another language, as it seems to be the case, it should be fast as c++ is the root of most languages...

**Pull request merged**
