### PR TITLE
Texture fixes and replacements

### PR DESCRIPTION
**Pull request by Danimal696**
Fixes Claimed wall 1111 top texture; replacements for creatures moods,
since i couldnt really tell what the old ones meant. they are remixes of
the original ones plus a few touches of my own

### CODE REVIEW

**Comment by Danimal696** [comment]
I fixed (i think) the water tiles, find them here: 
http://forum.freegamedev.net/viewtopic.php?f=38&t=6380#p64668

@hwoarangmy your turn now ;)

**Comment by Danimal696** [comment]
The gems are gold tiles that never depletes, but give less gold, related to:
#735

**Comment by akien-mga** [comment]
That's a really cool update, I love the new creature mood overlays, good job!
The new rock texture is cool too, though it shows pretty dark in the game, maybe we should tweak its material lighting a bit.

**Comment by Bertram25** [comment]
> before SOMEONE says anything...

Who? :angel:

**Comment by Bertram25** [comment]
Mergeable as for me.
It's a real good improvement. :D

**Comment by hwoarangmy** [comment]
Seems like pretty cool. I'm rebasing and will have a look

> @hwoarangmy your turn now ;)

Ok, I wil have a look ^^

**Pull request merged**
