### PR TITLE
AI should try to help its own creatures to get to their bed/hatchery when they are tired/hungry

### PR DESCRIPTION
**Pull request by hwoarangmy**

### CODE REVIEW

**Comment by hwoarangmy** [comment]
@Bertram25 @akien-mga as requested, I've splitted the function

**Comment by akien-mga** [comment]
It builds and runs fine. I'm now idling in Stonekeep Siege with `togglefow` on to see if the AI will pick up the two Pit Demons blocked by gold once they are tired/hungry :)

**Comment by akien-mga** [comment]
Damn, they were freed by kobolds :p

**Comment by hwoarangmy** [comment]
@akien-mga ^^ Note that if you want to go faster, edit the level to set their awakness to 30 and they should be picked up when they get to 20

**Comment by Bertram25** [comment]
> @Bertram25 @akien-mga as requested, I've splitted the function

Thanks for following my advice. :) (Again, you were not forced to, but my selfish part appreciate the move. ;])
I'll be testing asap.

**Comment by Bertram25** [comment]
Tested after changing sleepines of enemy creatures. Works fine. :) Mergeable as for me.

**Pull request merged**
