### PR TITLE
Research Visual Cooldown upgrades + spell cooldowns.

### PR DESCRIPTION
**Pull request by Bertram25**

### CODE REVIEW

**Comment by hwoarangmy** [comment]
I just tried and the progressbar effect looks really nice. Congrats ^^
Concerning the PR, appart from my comment, it is mergeable to me. Another nice improvement for the 0.6.0.

**Comment by Bertram25** [comment]
> I just tried and the progressbar effect looks really nice. Congrats ^^

Thanks. Still I wondered whether you wanted me to maybe color the lit part? I could make it become more grayish, redish, or whatever-ish you'd rather want it to be.
(I would simply add a color parameter.)
Just tell me guys. :)

**Comment by akien-mga** [comment]
The progress bar and cooldown bar look really cool, as @hwoarangmy said, that's a really nice addition. As for the color, I don't have a strong opinion (currently most of the UI elements are white), but I'd like to see some mockups ;)

**Comment by Bertram25** [comment]
> As for the color, I don't have a strong opinion (currently most of the UI elements are white), but I'd like to see some mockups ;)

k. :) I'll add a color parameter asap and will make a few screenies. ;)

**Comment by hwoarangmy** [comment]
Well, honestly, it is already really nice. If you play with colors and find something better, please feel free to update your PR but IMHO, that's already great...

**Comment by Bertram25** [comment]
Ok, I'll a color param and turn the spell function into a lambda alla listAllResearches tonight.
After what @hwoarangmy said on the ResearchManager, I'll move that there to have the same kind of logic at the same location, despite the user logic.

Note to self:
- Disable spell buttons when cooldown > 0
- Have a look at whether it is possible to make the progress updates be smooth, using the secondPerTurn value to compute a speed.

**Comment by hwoarangmy** [comment]
> Have a look at whether it is possible to make the progress updates be smooth, using the secondPerTurn value to compute a speed.

That would be even better. Cool to worry about such details. That means the game is improving well ^^

**Comment by Bertram25** [comment]
I didn't finish yesterday due to sleepiness but it will be done by the end of the week hopefully. :)

**Comment by akien-mga** [comment]
IMO we can merge this one and get possible improvements in the next PR :)

**Pull request merged**
