### PR TITLE
Made OD use standard paths for Windows and Linux and follow XDG specific...

### LINKED ISSUE #25: Made OD follow paths policies on Windows, Mac and Linux.
At the moment, the game app is writing log files and shader debug data in the same place that it is running.

While this is useful when debugging, this should not happen on release mode and follow system standard data paths instead.
User saved games should also do the same.

### LINKED ISSUE #171: Prettify screenshot names
At the moment and thanks to latest @oyvindln's patch, screenshot names gets a serial number based on the time value added as a suffix on their filenames.

This permits to prevent making them overwritten between two sessions of OD.

Since this serial number is based on time, we should prettify the time given and make it human readable, such as:
OD_screenshot_YYMMDD_HHMMSS.png instead of OD_screenshot_NNNNNNNN.png

Nothing urgent, of course. :)

### PR DESCRIPTION
**Pull request by Bertram25**
...ations.

More thorough windows testing is also requested.
I may also have fixed the user data folder detection on OSX but I can't test.

While on it, I also prettified the screenshots names.

Fixes #25
Fixes #171

### CODE REVIEW

**Comment by Bertram25** [comment]
It should be ok now. :)

**Comment by akien-mga** [comment]
Works great :-)

The screenshot name is indeed nicer: ODscreenshot_2014-Oct-21 13:16:22_6.png

**Comment by hwoarangmy** [comment]
I have a problem. OD cannot load ogre.cfg. If I look in explorer, the path exists but ..\opendungeons\cfg is empty :-(

**Comment by Bertram25** [comment]
Dang. I must have forgotten something. I'll reboot on windows asap.

**Comment by hwoarangmy** [comment]
OK, it's my fault. You have changed the path where ogre.cfg is and the debugger breaks because it cannot find the file. But it is not a fatal crash. I've tried to let it continue and it has created the file correctly.
Sorry for the trouble and to apologize, I merge ;-)

**Comment by Bertram25** [comment]
> OK, it's my fault. You have changed the path where ogre.cfg is and the debugger breaks because it cannot find the file. But it is not a fatal crash. I've tried to let it continue and it has created the file correctly.
> Sorry for the trouble and to apologize, I merge ;-)

Np, it's good to know :)

**Pull request merged**
