### PR TITLE
Hopefully fixed a few glitches with settings.

### LINKED ISSUE #830: Fix problems around config handling...
From @hwoarangmy 
- [x] Problems when destroying certain children windows in the window settings.

I've had a deeper look and it is because when we click cancel, there is a call to `SettingsWindow::initConfig`

In this function, `mCustomVideoComboBoxes` is cleared. The problem is that we try to remove them from `mSettingsWindow` while their real parent should be `mSettingsWindow->getChild("MainTabControl/Video").`

Note that there is something similar with `mCustomVideoTexts.`
- [x]  There are error on empty config param found with new config and when initing the config in the settings window.
- [x] Upgrade user config getters to support value existence check and potential error reporting. + Merge user config maps into one.

### PR DESCRIPTION
**Pull request by Bertram25**
Should fix #830

### CODE REVIEW

**Comment by Bertram25** [comment]
@hwoarangmy Please tell me whether it improves things for you. :)

**Comment by Bertram25** [comment]
@hwoarangmy Should be ok now. :)

@akien-mga The audio displayed value should be fixed, too. :)

**Comment by hwoarangmy** [comment]
I will test that tonight ^^

**Comment by akien-mga** [comment]
Works fine as far as I can tell :)

**Comment by hwoarangmy** [comment]
Works well, no more warning in logs

**Pull request merged**
