### PR TITLE
Added a new room object for casino + fire particle effect

### PR DESCRIPTION
**Pull request by hwoarangmy**

### CODE REVIEW

**Comment by Bertram25** [comment]
Will test now. :)

**Comment by hwoarangmy** [comment]
ok, I will do corresponding fixes

**Comment by hwoarangmy** [comment]
@Bertram25 It should be good now ^^

**Comment by Bertram25** [comment]
Lol, why 2 commits? I'll test in any case.

**Comment by hwoarangmy** [comment]
> Lol, why 2 commits? I'll test in any case.

Because on non case sensitive OS, there is no choice for changing sensitiveness ^^
git sees no difference unless the file is renamed

**Comment by Bertram25** [comment]
> Because on non case sensitive OS, there is no choice for changing sensitiveness ^^
> git sees no difference unless the file is renamed

Arg, soo true.

**Comment by Bertram25** [comment]
Ah btw, I do think you could replace the fire spell particle effect with that new one right away. Just my two cents, though.

**Comment by hwoarangmy** [comment]
> I do think you could replace the fire spell particle effect with that new one right away

I have another use for this one ;-)

**Comment by Bertram25** [comment]
Merging!

**Comment by akien-mga** [comment]
In such cases it might be nice to merge the two renaming commits into their parent with git rebase -i. :)

**Comment by Bertram25** [comment]
> In such cases it might be nice to merge the two renaming commits into their parent with git rebase -i. :)

This might not work either on case insensitive OS, but I don't remember trying, though.

**Comment by hwoarangmy** [comment]
> In such cases it might be nice to merge the two renaming commits into their parent with git rebase -i. :)

I've not tried but I would bet git would detect no difference between the files and would cancel the change

**Comment by akien-mga** [comment]
I'm pretty sure it would work when merging commits B and C into A at once :)

**Comment by hwoarangmy** [comment]
> I'm pretty sure it would work when merging commits B and C into A at once :)

OK, I will try next time ^^

**Pull request merged**
