### PR TITLE
Reworked the spatial sound playing algorithm.

### PR DESCRIPTION
**Pull request by Bertram25**
- To avoid spamming sounds with setPosition()
- And add sound culling handling.

Now only sounds near you point of view will be heard.
I also made it so if you you go higher, you can hear more far away sounds...

Main part of #147

### CODE REVIEW

**Comment by akien-mga** [comment]
@Bertram25 is in a coding spree!

**Comment by Bertram25** [comment]
Yeah :D

**Comment by hwoarangmy** [comment]
ok. Then I merge

**Comment by Bertram25** [comment]
I'm testing it, it should be done in a few minutes. :)

**Pull request merged**
