### PR TITLE
Fixed the portals idle and spawn animation used.

### LINKED ISSUE #390: Check the portal animations
@Danimal696 reported that the portal animation wasn't done properly some time ago, and it seems the 'Triggered' animation isn't used.
(TODO: try to find the link back to the original discussion.)

### PR DESCRIPTION
**Pull request by Bertram25**
I also fixed a bug making the portal not triggering the Idle animation again
after spawning.

Fixes #390

### CODE REVIEW

**Comment by akien-mga** [comment]
Works fine here.

**Comment by Bertram25** [comment]
Ok, the D3D renderer support has been readded :)

**Comment by hwoarangmy** [comment]
I confirm it is ok with the portal. I cannot test D3D because I've not compiled the required ogre modules but it is mergeable for me.
@Bertram25 Have you tried the D3D renderer ?

**Comment by Bertram25** [comment]
> @Bertram25 Have you tried the D3D renderer ?

I just did (Tried both the D3D9 and D3D11 renderer).
With the D3D11 renderer, Ogre triggers an exception about the fact we didn't provide custom shaders.

With the D3D9 renderer, the game starts, but once you click on Start game, you can see the ingame GUI, a broken minimap, and then, this is shown in the log before the app quits:

```
13:55:57: OGRE EXCEPTION(3:RenderingAPIException): Cannot assemble D3D9 high-level shader 11677f8e-a8bd-1668-5716-467659f5519a_VS Errors:
OpenDungeons\memory(159,2): error X5629: Invalid register number: 12. Max allowed for o# register is 11.
 in D3D9HLSLProgram::loadFromSource at ..\..\..\..\..\RenderSystems\Direct3D9\src\OgreD3D9HLSLProgram.cpp (line 284)
13:55:57: High-level program 11677f8e-a8bd-1668-5716-467659f5519a_VS encountered an error during loading and is thus not supported.
OGRE EXCEPTION(3:RenderingAPIException): Cannot assemble D3D9 high-level shader 11677f8e-a8bd-1668-5716-467659f5519a_VS Errors:
OpenDungeons\memory(159,2): error X5629: Invalid register number: 12. Max allowed for o# register is 11.
 in D3D9HLSLProgram::loadFromSource at ..\..\..\..\..\RenderSystems\Direct3D9\src\OgreD3D9HLSLProgram.cpp (line 284)
13:55:57: OGRE EXCEPTION(2:InvalidParametersException): Could not create gpu programs from render state  in ProgramManager::acquireGpuPrograms at ..\..\..\..\..\Components\RTShaderSystem\src\OgreShaderProgramManager.cpp (line 108)
13:55:57: Internal Ogre3D exception: OGRE EXCEPTION(2:InvalidParametersException): Could not create gpu programs from render state  in ProgramManager::acquireGpuPrograms at ..\..\..\..\..\Components\RTShaderSystem\src\OgreShaderProgramManager.cpp (line 108)
```

@oyvindln I know you've been somewhat grumpy with me removing this (and you'll have to explain why), but AFAIK, this has never worked fine, at least since Ogre 1.9 and on intel drivers.
That said, I can let this in and create a Win32 build so that someone with a nvidia card can have a go, but I must say I don't believe in it.

So, now, either I remove this, or someone is willing to test a win32 build using the D3D9 renderer.

**Comment by hwoarangmy** [comment]
IMHO, if we see a bug, no need to try to fix it. We should just remove D3D renderer and that's solved. If it worked out of the box, I wouldn't say that. But I think we have better things to do than fixing that.

**Comment by Bertram25** [comment]
Ok, as said on the forums, I've uploaded the RC1 release with my PR but without the D3D9 renderer.

I'll update this PR shortly to remove the D3D9 renderer (again) ;)

**Comment by Bertram25** [comment]
Done! :)

**Comment by akien-mga** [comment]
Looks good, merging then since the changes are quite limited and I already tested them :-)

**Comment by Bertram25** [comment]
Now it's done. Time for a merge to stable and retag.

**Comment by Bertram25** [comment]
branches + tag updated. :)
We're officially ready for a release!!

**Comment by oyvindln** [comment]
@Bertram25 The D3D renderer used to work in the past at least. The error you are getting seems to be a lack of support for something, so it may work on a different system.

**Comment by Bertram25** [comment]
@oyvindln Can you have a go at trying this on a Windows? This is just a matter of getting the renderer dlls from a former build and tweaking a bit the plugins/resources.cfg files AFAIK.

**Comment by oyvindln** [comment]
I will once I get back home in January

**Pull request merged**
