### PR TITLE
Add support for chat

### LINKED ISSUE #31: Add support for chat message in game
When ingame, if the user presses enter, he should be able to send a message to the connected players.
The messages sent that way should be displayed on all players screen (support for teams will come later).

### PR DESCRIPTION
**Pull request by hwoarangmy**
fixes #31

### CODE REVIEW

**Comment by hwoarangmy** [comment]
@Bertram25 can you have a look?

**Comment by Bertram25** [comment]
I haven't tested it yet. (Sorry to late for me tonight.)
But the code looks fine, my small renaming request apart. :)

It will be cool to send each other some nice japes. ;)

**Comment by hwoarangmy** [comment]
Yes, I guess inspiration was not on my side when I chose the name. It's renamed :)

**Comment by Bertram25** [comment]
Cool :) I'll test it asap.

**Comment by Bertram25** [comment]
Tested it. It's cool and well done. :)

**Pull request merged**
