### PR TITLE
 	Add support to allow creatures/rooms to drop objects (ie Treasuries) + small fixes

### PR DESCRIPTION
**Pull request by hwoarangmy**

### CODE REVIEW

**Comment by akien-mga** [comment]
Just saying that I won't be much available until Wednesday or so, I'm enjoying some holiday with friends (the privilege of being jobless :-P )

**Comment by Bertram25** [comment]
I'm eager to test that one. :D 
Those are some cool additions and will make objects very easy to add.
I'll test asap.

**Comment by Bertram25** [comment]
> Just saying that I won't be much available until Wednesday or so, I'm enjoying some holiday with friends (the privilege of being jobless :-P )

Good, wednesday was yesterday. ;P
Have nice holidays. ;)

**Comment by hwoarangmy** [comment]
> Just saying that I won't be much available until Wednesday or so, I'm enjoying some holiday with friends (the privilege of being jobless :-P )

Nice holidays ^^

**Comment by hwoarangmy** [comment]
> Those are some cool additions and will make objects very easy to add.

That's the purpose ^^
BTW, that's why I was saying in a previous PR that we should think of a better name for RoomObject. In reality, I used it because the rendering was already done (so that, TreasuryObject only have specialized code ^^).
Can you think of something better than DisplayableObject or RenderableObject ?

**Comment by Bertram25** [comment]
> Can you think of something better than DisplayableObject or RenderableObject ?

So we have Entity, GameEntity, Creature, Building, Trap, Room, and RoomObject, right? (Did I miss one of this family?)
To be honest, somehow I don't like Object here, since we're always speaking of objects, making it rather meaningless to me, but it's a matter of taste, of course. :)
What about RenderedGameEntity, RenderedEntity, VisualEntity?

Whatever you choose, I trust you. :)

**Comment by hwoarangmy** [comment]
I like RenderedEntity. I will do a PR for that (and only that) when this one will be merged.

**Comment by Bertram25** [comment]
Is working fine :) I'm merging... :)

**Pull request merged**
