### PR TITLE
Use of polymorphism for render manager instead of huge switch case.

### LINKED ISSUE #137: Use polymorphism for render requests instead of a huge switch/case?
Everything is in the title.

IIRC, this was discussed on the forums and started by @tomluchowski .

If tom doesn't want/ can't do it anymore, someone else may want to bite this one.
Let's give @tomluchowski a week or two to answer. Afterwards, the task should be considered free to take again.

### PR DESCRIPTION
**Pull request by hwoarangmy**
fixes #137

### CODE REVIEW

**Comment by Bertram25** [comment]
The code looks fine. I'll test asap. :)

Out of curiosity, why did you keep the render manager after all?

**Comment by hwoarangmy** [comment]
Because it manages the scene nodes

**Comment by Bertram25** [comment]
Ah sure. I'm building atm. It's crowded tonight in the PR tab, isn't it? ;)

**Comment by hwoarangmy** [comment]
seems like you worked well ^^

**Comment by Bertram25** [comment]
> seems like you worked well ^^

Yeah, my motivation was like crazy today. :)

**Comment by Bertram25** [comment]
Works well. I'm merging.

**Pull request merged**
