### PR TITLE
Kept on working on the GUI

### PR DESCRIPTION
**Pull request by Bertram25**

### CODE REVIEW

**Comment by hwoarangmy** [comment]
I will try to test that tonight. If @akien-mga can give a try, it can be merged for me after testing ^^

**Comment by Bertram25** [comment]
Ah, btw, the static frame borders are now metal gray instead of black.
This means there will be a small grey outline to the objective window, minimap and such.
Feel free to tell whether it's ok for you of whether you want something else.

I also have plans to improve a bit more, normal, hover, and selection tab buttons and content panes.

**Comment by akien-mga** [comment]
> This means there will be a small grey outline to the objective window, minimap and such.
> Feel free to tell whether it's ok for you of whether you want something else.

I like it this way :-)
Our GUI is starting to look quite good :-D

**Comment by Bertram25** [comment]
Thanks for all the feedback. :)

**Comment by akien-mga** [comment]
Merging :-)

**Pull request merged**
