### PR TITLE
Add support for seats and MiniMap in Map Editor + small fixes

### LINKED ISSUE #157: Add support to handle claimed tiles in editor
It should be possible to add claimed tiles associated with a seat (ground or wall)

### PR DESCRIPTION
**Pull request by hwoarangmy**
fixes #157

### CODE REVIEW

**Comment by hwoarangmy** [comment]
To test it :
press Y to switch seats. Selected seat can be seen in the top of the editor. Rooms/traps/claimed tiles (wall or ground) are affected by seat.

**Comment by Bertram25** [comment]
Fixes also #146 :)

**Comment by Bertram25** [comment]
A few trivial stuff in code. I'll be testing it in a few minutes...

**Comment by Bertram25** [comment]
3 things noticed while using it:
- Makes the single player game crash when selecting the map 'Dungeon siege':

```
[bt]: (1) ./OpenDungeons.bin : GameMap::addRoom(Room*)+0x3f [0x58e28f]
[bt]: (2) ./OpenDungeons.bin : GameMap::addRoom(Room*)+0x3f [0x58e28f]
[bt]: (3) ./OpenDungeons.bin : MapLoader::readGameMapFromFile(std::string const&, GameMap&)+0x173b [0x5b9a4b]
[bt]: (4) ./OpenDungeons.bin : GameMap::loadLevel(std::string const&)+0x3d [0x586ffd]
[bt]: (5) ./OpenDungeons.bin : ODServer::startServer(std::string const&, bool, ODServer::ServerMode)+0x133 [0x5ed0d3]
[bt]: (6) ./OpenDungeons.bin : MenuModeSkirmish::launchSelectedButtonPressed()+0x6fd [0x5c539d]
[bt]: (7) ./OpenDungeons.bin : Gui::mSKMLoadButtonPressed(CEGUI::EventArgs const&)+0x55 [0x59c465]
[bt]: (8) /home/yohann/Projets/cegui-0.8.3/lib/libCEGUIBase-0.so.2 : CEGUI::Event::operator()(CEGUI::EventArgs&)+0x2e [0x7fae701dc2ae]
[bt]: (9) /home/yohann/Projets/cegui-0.8.3/lib/libCEGUIBase-0.so.2 : CEGUI::PushButton::onMouseButtonUp(CEGUI::MouseEventArgs&)+0xdf [0x7fae70311fff]
[bt]: (10) /home/yohann/Projets/cegui-0.8.3/lib/libCEGUIBase-0.so.2 : CEGUI::GUIContext::injectMouseButtonUp(CEGUI::MouseButton)+0xfe [0x7fae7027fbee]
[bt]: (11) ./OpenDungeons.bin : MenuModeSkirmish::mouseReleased(OIS::MouseEvent const&, OIS::MouseButtonID)+0x3c [0x5c428c]
[bt]: (12) /usr/lib/x86_64-linux-gnu/libOIS-1.3.0.so : OIS::LinuxMouse::_processXEvents()+0xe0 [0x7fae707055b0]
[bt]: (13) /usr/lib/x86_64-linux-gnu/libOIS-1.3.0.so : OIS::LinuxMouse::capture()+0x22 [0x7fae70705902]
[bt]: (14) ./OpenDungeons.bin : ODFrameListener::frameStarted(Ogre::FrameEvent const&)+0x10e [0x5ebf8e]
[bt]: (15) /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0 : Ogre::Root::_fireFrameStarted(Ogre::FrameEvent&)+0x54 [0x7fae71147264]
[bt]: (16) /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0 : Ogre::Root::_fireFrameStarted()+0x31 [0x7fae711477f1]
[bt]: (17) /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0 : Ogre::Root::renderOneFrame()+0x9 [0x7fae71147939]
[bt]: (18) /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0 : Ogre::Root::startRendering()+0x35 [0x7fae71147995]
[bt]: (19) ./OpenDungeons.bin : ODApplication::ODApplication()+0x3fc [0x5cf36c]
[bt]: (20) ./OpenDungeons.bin : main+0x1e [0x468dce]
[bt]: (21) /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main+0xf5 [0x7fae6de93b45]
[bt]: (22) ./OpenDungeons.bin() [0x46a364]
```

Reproducible by selecting dungeons siege each time on linux at least. The map TestSinglePlayerSmall is working for instance.
I didn't test the multiplayer one but it might be the same.
- You can make the editor crash when selecting the dungeons siege map (This leve doesn't like your patch, it seems. ;]), and then pressing escape. While the screen is freezing (unloading data), click on screen several time, and you'll get this:

```
[bt]: (1) ./OpenDungeons.bin : Tile::setSelected(bool, Player*)+0x7 [0x62cd07]
[bt]: (2) ./OpenDungeons.bin : Tile::setSelected(bool, Player*)+0x7 [0x62cd07]
[bt]: (3) ./OpenDungeons.bin : EditorMode::mouseReleased(OIS::MouseEvent const&, OIS::MouseButtonID)+0xaf [0x5830af]
[bt]: (4) /usr/lib/x86_64-linux-gnu/libOIS-1.3.0.so : OIS::LinuxMouse::_processXEvents()+0xe0 [0x7f6c09c175b0]
[bt]: (5) /usr/lib/x86_64-linux-gnu/libOIS-1.3.0.so : OIS::LinuxMouse::capture()+0x22 [0x7f6c09c17902]
[bt]: (6) ./OpenDungeons.bin : ODFrameListener::frameStarted(Ogre::FrameEvent const&)+0x10e [0x5ebf8e]
[bt]: (7) /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0 : Ogre::Root::_fireFrameStarted(Ogre::FrameEvent&)+0x54 [0x7f6c0a659264]
[bt]: (8) /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0 : Ogre::Root::_fireFrameStarted()+0x31 [0x7f6c0a6597f1]
[bt]: (9) /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0 : Ogre::Root::renderOneFrame()+0x9 [0x7f6c0a659939]
[bt]: (10) /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0 : Ogre::Root::startRendering()+0x35 [0x7f6c0a659995]
[bt]: (11) ./OpenDungeons.bin : ODApplication::ODApplication()+0x3fc [0x5cf36c]
[bt]: (12) ./OpenDungeons.bin : main+0x1e [0x468dce]
[bt]: (13) /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main+0xf5 [0x7f6c073a5b45]
[bt]: (14) ./OpenDungeons.bin() [0x46a364]
```
- In the editor, when placing rooms tiles, you can't place them on tiles where there is a creature, while you can move temporarily the creature, create the room, and place the creature back to its former place. The seat changing option is working fine. :)

Just to be sure, it is used only for claimed type tiles, right?

Best regards,

**Comment by hwoarangmy** [comment]
> Just to be sure, it is used only for claimed type tiles, right?

No. For rooms and traps too :)

**Comment by hwoarangmy** [comment]
> Makes the single player game crash when selecting the map 'Dungeon siege':

Nice catch. I had made a mistake in Room::getRoomTypeFromMeshName. MeshName for hatchery is Farm, not Hatchery. I've changed that but I had not seen a level was already using it :)

> In the editor, when placing rooms tiles, you can't place them on tiles where there is a creature, while you can move temporarily the creature, create the room, and place the creature back to its former place

That's the wanted behaviour. If anything uses a tile, we cannot change it. Don't know if it is worth changing it right now or if we should wait for creatures and room destruction

> You can make the editor crash when selecting the dungeons siege map

Interesting. Is it the same in GameMode ? I would expect the same. I'm gonna test

**Comment by hwoarangmy** [comment]
> While the screen is freezing (unloading data), click on screen several time, and you'll get this:

I cannot reproduce but I would guess it is due to the fact that the game is shut down while EditorMode is still active. I'm gonna do something to make sure the mode is unloaded at the same moment as the ressources are released. For the differences between GameMode or EditorMode, it might be due to the fact that in game mode, the mode is shutdown by the Gui. I guess that in this case, we shutdown the mode before dispatching mouse events to modes. But as in editor mode, we unload it in the keypressed routine, if mouse/key events are queued, it might crash...

**Comment by Bertram25** [comment]
Sounds relevant, indeed.

**Comment by hwoarangmy** [comment]
BTW, I've seen that within ModeManager, modes are used in a variable called mGameMode. I'm going to take the opportunity that I'm there to rename it to mApplicationMode as it contains not only game modes but also editor or menus (which are application modes)

**Comment by Bertram25** [comment]
Fine by me :)

**Comment by hwoarangmy** [comment]
@Bertram25  Could you test if you can still reproduce the bug ?

**Comment by Bertram25** [comment]
Both crashes are fixed with latest patch for any mode. :D 

I've noted a few things though: ;)
- Building a room on a tile where a creature is, is still not possible.
- I also noticed that when you select a tile type or a room and you click next to a creature, you take it. It is not really expected, even if not part of your pull request.
- I've realized it is impossible to put teamless (team_id == 0) claimed tiles/walls now.
- You should allow to place teamless rooms and traps as well, because:
  - Teamless traps should shoot any creatures, except the teamless ones. Team 0 is a team somehow, anyway.
  - Teamless rooms will later be used as room you can claim for interesting strategical effects.

You may want to do that in another PR. Yours to tell. :)

Best regards,

**Comment by hwoarangmy** [comment]
> Building a room on a tile where a creature is, is still not possible

I will change that

> I also noticed that when you select a tile type or a room and you click next to a creature, you take it. It is not really expected, even if not part of your pull request.

I've fixed that for tiles. I can't reproduce with rooms. Are you sure ?

> I've realized it is impossible to put teamless (team_id == 0) claimed tiles/walls now.

In fact, it is. I've not tried but in my mind, it would just be a matter of adding a seat with faction = "none" and add stuff for it. This way, we could even use a team id so that the traps will fire on everything (if team id different from every other) or on specific teams :)

**Comment by hwoarangmy** [comment]
I have checked and I confirm adding a seat with faction "none" works. Creatures attack everybody, claimed tiles are claimed, ...
The only thing is that seatId = 0 is a forbidden value. If you really want to use that (because of the color), I can check the consequences (by setting the forbidden value to -1).
Concerning the PR, if you see no more problem, please merge :)

**Comment by Bertram25** [comment]
> I have checked and I confirm adding a seat with faction "none" works. Creatures attack everybody, claimed tiles are claimed, ...
> The only thing is that seatId = 0 is a forbidden value. If you really want to use that (because of the color), I can check the consequences (by setting the forbidden value to -1).

Adding a independent Seat for feral creatures/traps is completely ok to me. :) I don't think it's really needed to bother with adding non-seat creatures if it's breaking things uselessly.

I'll merge.

**Comment by hwoarangmy** [comment]
@Bertram25 Sorry, I forgot to ask something from you because you know Ogre better than I do. I've added code to release ressources for the MiniMap when changing mode. But I'm not very comfortable with Ogre and I just did what my instinct told, which may not be correct. I'm talking about this :
https://github.com/hwoarangmy/OpenDungeons/commit/3564b4d7aa055d413f065a44c8ccd03fea95d58d#diff-01a504647075ad1f1c29cc6366e73e74R73

Thanks

**Comment by Bertram25** [comment]
Actually, you did quite fine, even if, to be honest, I think we're still not done with this because of #29 
The fact that you're deleting the ogre texture before freeing it on CEGUI is the way to go from what I've seen.

**Comment by Bertram25** [comment]
> because you know Ogre better than I do

I'll be honest: I'm also rather new in this area, even if I'm much more at ease than a few months ago so take what I say with the usual bit of salt, even I really try hard not to say dumb things. ;)

**Comment by hwoarangmy** [comment]
ok, cool. Thanks

**Pull request merged**
