### PR TITLE
Fixed creature vision + chat message when no treasury available + fighter logic outside battle

### PR DESCRIPTION
**Pull request by hwoarangmy**
To test the creature vision fix, one can use the console command:
creaturevisdebug creatureName
and check that the tiles which the creature has vision on are correct

### CODE REVIEW

**Comment by Danimal696** [comment]
Whoa, talking about big commits :D

**Comment by Bertram25** [comment]
Compiling :)

**Comment by hwoarangmy** [comment]
I've just seen that by rebasing, I've removed all the discussion in this PR :-(

**Comment by Bertram25** [comment]
> I've just seen that by rebasing, I've removed all the discussion in this PR :-(

Funny, usually they are kept. ?

**Comment by akien-mga** [comment]
> I've just seen that by rebasing, I've removed all the discussion in this PR :-(

IIRC comments that were made on specific commits are lost, and comments that were made on the PR itself are preserved. I'm not sure though, it's a bit unpredictable. Maybe we should do a test PR to try different cases :-)

**Comment by Bertram25** [comment]
> IIRC comments that were made on specific commits are lost, and comments that were made on the PR itself are preserved. I'm not sure though, it's a bit unpredictable. Maybe we should do a test PR to try different cases :-)

Or ask github's staff. They're cool. :)

**Comment by Bertram25** [comment]
So far:
- Creature vision working great now. No more cannon cheat.
- Pay day... well working great :S
- Treasury hint working. :)

Regressions:
- Dropping gold onto treasury doesn't add it to gold count.
- Gold amount is acting funny. I had 1600 gold, bought one treasury tile and dropped to 0. Happened twice in a row.

**Comment by Bertram25** [comment]
I'll be on fighters activity now.

**Comment by Bertram25** [comment]
Ah, the gold bug happens on any map when I add exactly one treasury tile next another one. The other rooms seem not triggering the bug.

**Comment by Bertram25** [comment]
Nooo, my moneyyyyyy. My creatures are sucking on my gold. Ahhh

**Comment by hwoarangmy** [comment]
> IIRC comments that were made on specific commits are lost, and comments that were made on the PR itself are preserved

Yep, that's the feeling I have. And in this PR case, all the comments were on the commits :-(

**Comment by hwoarangmy** [comment]
> Dropping gold onto treasury doesn't add it to gold count.

hmm, strange, I had tested that. I will have a look.

EDIT: I can reproduce. I'm fixing it
EDIT2: I've seen what was going on. Bad copy/paste of mine

**Comment by hwoarangmy** [comment]
Seems like the bug is from my previous PR (wrong copy/paste when simplifying the treasury rooms iterators). It should fix the regressions seen by @Bertram25 
Nice catch

**Comment by Bertram25** [comment]
Wow, tested a few combination and it's working fine :D I'm merging.

**Pull request merged**
