### PR TITLE
Misc fixes...

### PR DESCRIPTION
**Pull request by Bertram25**
Enjoy :)

### CODE REVIEW

**Comment by akien-mga** [comment]
We awoke the never-sleeping @Bertram25! I guess he didn't like being crushed by @hwoarangmy and I after @lowerthanred got a segfault :-)

**Comment by hwoarangmy** [comment]
You work well at night ^^

**Comment by akien-mga** [comment]
It works well, there's only the logged nickname part that I haven't tested yet.

**Comment by hwoarangmy** [comment]
> Ok I'll add a log in setNick as well. :)

Thanks ^^

**Comment by Bertram25** [comment]
Should be done. :)

**Comment by hwoarangmy** [comment]
testing

**Comment by hwoarangmy** [comment]
works well. I merge

**Pull request merged**
