### PR TITLE
Allow creatures to spawn with a weapon + "max" hp in level file + fixed regression on creature definition modifications + network fixes

### PR DESCRIPTION
**Pull request by hwoarangmy**

### CODE REVIEW

**Comment by akien-mga** [comment]
Looks fine to me, I did not experience any regression, and I can confirm that the BigKnight in the 2v2 test level has a rusty sword and low hp.

Edit: I can also confirm that the stun knights are no longer stunned (I hadn't seen this before, but I checked @Bertram25's branch and indeed they seem completely out of order :-P ).

**Comment by hwoarangmy** [comment]
I forgot to test my rule: try to save an unchanged level in the editor and check it is not modified ^^
Now, it's done

**Comment by Bertram25** [comment]
Give me 5-10 minutes and I'll be on IRC :)

**Comment by hwoarangmy** [comment]
Sorry I cannot connect right now, ill childs are the priority :-(
If you are still there, I will try to connect asap.

**Comment by Bertram25** [comment]
> Sorry I cannot connect right now, ill childs are the priority :-(
> If you are still there, I will try to connect asap.

Np. We are there :) Ill child first whatever happens

**Comment by hwoarangmy** [comment]
I think it will be enough for this PR unless review says otherwise ^^

**Comment by akien-mga** [comment]
Hehe, I guess we could have merged this PR yesterday and let you do a network related PR afterwards, but let's hit two birds with one stone :-)
I won't have much time to actually play in LAN, but I'm more or less always around on IRC if one of you wants to do a quick connection test.

**Comment by Bertram25** [comment]
Code is fine, and nothing seems broken in single player.
I'll drop randomly on IRC so we can officially try a connection test + try to pick up gold.

**Comment by Bertram25** [comment]
Tested with @akien-mga. OD is officially playable through lan again :D

**Comment by akien-mga** [comment]
Tested live with @Bertram25, he destroyed the base of the two enemies in no time while I was playing around in my base :-p

**Comment by Bertram25** [comment]
> Tested live with @Bertram25, he destroyed the base of the two enemies in no time while I was playing around in my base :-p

@akien-mga didn't play for real. He doesn't want me to see his strategies before we compete ;)

**Comment by akien-mga** [comment]
I quote (more or less): "Thanks for playing the first OpenDungeons LAN with me."
This is historic! :-)

BTW chat messages should be added to the log ;-)

**Comment by hwoarangmy** [comment]
> BTW chat messages should be added to the log ;-)

You want to keep track of @Bertram25 's bullshits ?

**Comment by akien-mga** [comment]
Indeed! :-)
And my live "Oh I found a bug" comments :-)

**Comment by Bertram25** [comment]
> You want to keep track of @Bertram25 's bullshits ?

Meh. :(

**Comment by hwoarangmy** [comment]
> Meh. :(

I'm joking ;-)

**Comment by Bertram25** [comment]
Of course, you are. Are you? ;)

**Pull request merged**
