### PR TITLE
Fixed Hero AI issue with Kobold + fixed faction names added/listed twice + other tweaks

### LINKED ISSUE #470: Hero faction AI do not build rooms
To dig tiles, the code searches for the first available kobold (in the GameMap class - hardcoded). Since the PR about changing the worker per faction, the hero faction do not have kobolds anymore and, thus, cannot dig.

### PR DESCRIPTION
**Pull request by Bertram25**
Fixes #470

### CODE REVIEW

**Comment by hwoarangmy** [comment]
eh, stop adding commits, I'm testing !!! ;-)

**Comment by hwoarangmy** [comment]
since you seem to be working here, I will test the whole tomorrow.
But the seat color is pretty nice and moving the goals to a dedicated window is a good idea (it gives space for rooms/traps).
Our UI is really beginning to look nice ^^

**Comment by Bertram25** [comment]
Thanks and sorry for the disturbance. I'll add one or two more but I'll stop there. (for now ;])

**Comment by hwoarangmy** [comment]
> sorry for the disturbance

I'm not stupid enough to complain that you work too much on OD ;-)

**Comment by akien-mga** [comment]
Needs rebasing now :)

**Comment by akien-mga** [comment]
@Bertram25 When you rebase, could you also add a commit to fix the target CEGUI version in gui/OD.project ?

It should be `CEGUIVersion="0.8"` and not `CEGUIVersion="1.0"` (that was actually the reason for my problem using CEED, and not a broken default config parameter).

**Comment by Bertram25** [comment]
Ok. :) But I won't be able available until tuesday at best. Have a nice Week-End !

**Comment by Bertram25** [comment]
I've rebased. I've other things ready but won't push there for now. ;)

**Comment by hwoarangmy** [comment]
I will try that tonight ^^

**Comment by akien-mga** [comment]
Sorry @Bertram25, merging @hwoarangmy's PR re-broke yours, hopefully you are still around to rebase it :-)

**Comment by Bertram25** [comment]
Np, I'll rebase now. :) 0.5.0 is overwhelmingly doing good already. :D

**Comment by Bertram25** [comment]
Ah, a quick question. I added the orthogonal and isometric views through keys. Do you want me to add a key to get back the default starting view point?

**Comment by hwoarangmy** [comment]
> Ah, a quick question. I added the orthogonal and isometric views through keys. Do you want me to add a key to get back the default starting view point?

I will tell you after testing ^^

**Comment by Bertram25** [comment]
> I will tell you after testing ^^

k, :) I've rebased. Just quick checking if I dumbly broke something and I'll push.

**Comment by Bertram25** [comment]
Rebased :) I added the latest requested fixes (about the break) and squashed a typo commit.

**Comment by akien-mga** [comment]
Testing now before anything PR gets merged :-P

**Comment by hwoarangmy** [comment]
testing ^^

**Comment by akien-mga** [comment]
Finally I did not have the time to test the beast, but I'll do it tomorrow morning :)

**Comment by hwoarangmy** [comment]
> I added the orthogonal and isometric views through keys. Do you want me to add a key to get back the default starting view point?

After testing, yep, it would be nice to switch views by pressing I

**Comment by Bertram25** [comment]
> After testing, yep, it would be nice to switch views by pressing I

Just to be sure. The I key is for isometric, the O one for Orthogonal. Do you want me to add a, let's say P key for the default view or add only one key cycling between the three?
(I would then assume you want the default - starting - view available also.)

**Comment by hwoarangmy** [comment]
Well, as you want. As a player, I usually like when you can toggle things by pressing a key (btw, it would be nice to be able to close help/objectives by pressing their key while displayed).
But if you want to use 2 keys, I've nothing against it ^^

**Comment by Bertram25** [comment]
> Well, as you want. As a player, I usually like when you can toggle things by pressing a key (btw, it would be nice to be able to close help/objectives by pressing their key while displayed).
> But if you want to use 2 keys, I've nothing against it ^^

You've sold the idea :) I'll add toggle/cycling support. + the new view in the next PR. :)

**Comment by hwoarangmy** [comment]
> You've sold the idea :)

sorry ^^

I've had a look at the code and spotted nothing wrong. I've tested workers walling and it works as expected as well as the windows you've added. IMHO, we can merge ^^
I will let @akien-mga since he seems to be testing

**Comment by Bertram25** [comment]
Cool, let's wait for @akien-mga review, then. We're not far from something really great as a game, IMHO. :D

**Comment by hwoarangmy** [comment]
Yep. Once we have the research tree and a start of campaign, we will have an interesting game (even if lacking content) ^^

**Comment by hwoarangmy** [comment]
I've also tested the window toggling and it works well

**Comment by akien-mga** [comment]
Awesome PR! Viewports, kobolds claiming behaviour... settings :-D
So many great changes!

**Comment by Bertram25** [comment]
Thanks :) Let's make it so we never want to play 0.4.9 again. ;)

**Pull request merged**
