### PR TITLE
Fixed editor and added a screen to choose the level to edit

### PR DESCRIPTION
**Pull request by hwoarangmy**
- Editor can be launched
- Skirmish and multiplayer levels can be edited
- When F8 is pressed to save map, a chat message is sent to display if it worked
- When the map is saved, a backup of the old one is made

### CODE REVIEW

**Comment by Bertram25** [comment]
I tested it and it's cool to be able to select one level :D 

I've seen two things but I don't think it's related to the current PR:
1. It is impossible to put a claimed wall:
   -> Set the fullness to 100%, choose Claimed tiles and you'll still place claim flat ground tiles. Other 100% fullness types work fine.
2. A crash when pushing escape:

```
[bt]: (1) ./OpenDungeons.bin : Tile::setSelected(bool, Player*)+0x7 [0x626547]
[bt]: (2) ./OpenDungeons.bin : Tile::setSelected(bool, Player*)+0x7 [0x626547]
[bt]: (3) ./OpenDungeons.bin : EditorMode::mouseReleased(OIS::MouseEvent const&, OIS::MouseButtonID)+0xaf [0x58285f]
[bt]: (4) /usr/lib/x86_64-linux-gnu/libOIS-1.3.0.so : OIS::LinuxMouse::_processXEvents()+0xe0 [0x7f7bbd01e5b0]
[bt]: (5) /usr/lib/x86_64-linux-gnu/libOIS-1.3.0.so : OIS::LinuxMouse::capture()+0x22 [0x7f7bbd01e902]
[bt]: (6) ./OpenDungeons.bin : ODFrameListener::frameStarted(Ogre::FrameEvent const&)+0x10e [0x5e828e]
[bt]: (7) /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0 : Ogre::Root::_fireFrameStarted(Ogre::FrameEvent&)+0x54 [0x7f7bbda60264]
[bt]: (8) /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0 : Ogre::Root::_fireFrameStarted()+0x31 [0x7f7bbda607f1]
[bt]: (9) /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0 : Ogre::Root::renderOneFrame()+0x9 [0x7f7bbda60939]
[bt]: (10) /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0 : Ogre::Root::startRendering()+0x35 [0x7f7bbda60995]
[bt]: (11) ./OpenDungeons.bin : ODApplication::ODApplication()+0x3fc [0x5cbacc]
[bt]: (12) ./OpenDungeons.bin : main+0x1e [0x4686de]
[bt]: (13) /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main+0xf5 [0x7f7bba7acb45]
[bt]: (14) ./OpenDungeons.bin() [0x469c74]
```

I don't know yet how to reproduce, but the crash didn't happen right when pushing escape, but rather a few seconds later, as if the tiles where being unloaded first.
I'll investiguate more.

**Comment by hwoarangmy** [comment]
> It is impossible to put a claimed wall: -> Set the fullness to 100%, choose Claimed tiles and you'll still place claim flat ground tiles. Other 100% fullness types work fine.

Ok, I will have a look. I've not spent too much time on claimed tiles/walls as it is not possible to chooses the color AFAIK.

> A crash when pushing escape

That's exactly the crash I was talking about in your pull request. The problem is a call to the gamemap before the tiles are created. I used to reproduce that by pressing escape and loading another map in the editor. Strange, I couldn't reproduce since I copied your code about map start (switching to editor mode after the client loads the map). I will check more.

**Comment by Bertram25** [comment]
@hwoarangmy Both points don't prevent me from merging. It depends more on you I think.
I'll also try to reproduce.

Regards,

**Comment by hwoarangmy** [comment]
ok, please merge then. I will make another pull request to allow choosing tile color when i will have done the needed for allied multiplayer support (In fact, I will use the seat id instead of the color).

**Comment by Bertram25** [comment]
k :)

**Pull request merged**
