### PR TITLE
Working on fixing #367 + misc stuff

### PR DESCRIPTION
**Pull request by Bertram25**

### CODE REVIEW

**Comment by oyvindln** [comment]
Are you sure about removing the possibility to use D3D on windows?

**Comment by akien-mga** [comment]
Looks fine as far as I'm concerned.

**Comment by hwoarangmy** [comment]
I will try with windows/mingw tonight

**Comment by hwoarangmy** [comment]
I've tried and there are problems...
The tiles you can see in the screenshot are only normal claimed tiles (I've built nothing)
odscreenshot_2014-12-14_221440_1

**Comment by akien-mga** [comment]
Is it better if you readd `materials/RTShaderLib/Cg` in resources.cfg?

**Comment by hwoarangmy** [comment]
I've made some tries. From what I've seen, its not about materials/RTShaderLib/Cg.

If I remove materials/RTShaderLib/GLSL150, I see no more glitches.

**Comment by Bertram25** [comment]
> Are you sure about removing the possibility to use D3D on windows?

@oyvindln While it is true that the HLSL shaders + the possibility to use the Direct X renderer is handled by Ogre on Windows, I wondered why we would like to keep it.
I mean if we're going cross-platform, there is a point where we'll definitely use more precise shaders to improve the visuals, and using two different renderers will be twice the cost in test and development.

That said, I'm not willing to be blunt here and if you have good reasons to keep it, I can readd it back.

> If I remove materials/RTShaderLib/GLSL150, I see no more glitches.

Ok, then the GLSL150 should be removed and disabled, I guess. It was before and it seems nobody complained about OD not starting so far.

> Is it better if you readd materials/RTShaderLib/Cg in resources.cfg?

@akien-mga As far as I've seen, the Cg is required as a dependency on Windows for some reasons. (Ogre does complain about some files from it being missing), but doesn't seem to be needed in the resource data directly somehow.

I don't want to play with fire here, just removing what's actually not used, so here is what I'll do:
- Readd Cg/ in the resources file to stay logical with what is used.
- Remove GLSL150 files and from the resources list to force the GLSL folder to be used, even when GLSL150 support exists on the hardware/driver.

The question open is: Should I readd HLSL shaders and Direct X renderer support on windows?

**Comment by akien-mga** [comment]
> As far as I've seen, the Cg is required as a dependency on Windows for some reasons. (Ogre does complain about some files from it being missing), but doesn't seem to be needed in the resource data directly somehow.

It sounds like Ogre tries to load it even though we don't use it, that's probably something that we should look into in the future. For now it's no big deal, those files are not heavy and I guess they are not nonfree like Cg :-)

> The question open is: Should I readd HLSL shaders and Direct X renderer support on windows?

I don't know much about shaders technologies, so I can't really comment. But your point about being cross-platform makes me think that we can let go of DirectX and focus on the OpenGL renderer. OpenGL is well established even in the Windows gaming sphere now, and unless their is a real gain in implementing DirectX support, I'd say let's focus on the open source and cross platform one :-)

**Comment by Bertram25** [comment]
Ok, the DirectX question remains. The rest is done. :)

**Comment by hwoarangmy** [comment]
That's ok with me ^^

**Comment by Bertram25** [comment]
Hi there, :)

I added 'King of the Hill' yesterday. It is playable but I'm still rather unhappy with it.
As is, the map will fit more a Human vs Human battle, while I should add a few more twists.

I'll also make it smaller for the single-Player version to make it more interesting and let the AI react better.

**Comment by akien-mga** [comment]
Awesome, I'll try it out and make sure that I don't design a similar map (I was planning on making one today). Note that the map in your commit is named "The Bridge", is it the same as "King of the Hill"?

**Comment by akien-mga** [comment]
Since yours is 1v1, I plan to go for a medium to small-sized (80x80 or something) 1v1v1 map (like a triangle).

**Comment by Bertram25** [comment]
> Awesome, I'll try it out and make sure that I don't design a similar map (I was planning on making one today). Note that the map in your commit is named "The Bridge", is it the same as "King of the Hill"?

Oops, s/King of the Hill/The Bridge/

The King of the Hill map, is another idea for later. ;)

Cool to see you're on your own map. :) Once my PR is in, I guess we'll be able to go on with the RC.

**Comment by akien-mga** [comment]
What is the easiest way to generate an empty level of X*Y dimensions?
I think a "Create new level" button which lets you type in X and Y dimensions and generates a level filled with dirt would be a nice feature for 0.5.0, I'll open an issue :-)

_Edit:_ Already part of #22

**Comment by Bertram25** [comment]
Yeah, all that should be discussed in #22 :)

**Comment by hwoarangmy** [comment]
> What is the easiest way to generate an empty level of X*Y dimensions?

IMHO, the easiest is to copy a map (the smallest), remove all the tiles (within [Tiles][/Tiles]) and change the map size (also within [Tiles][/Tiles]). Then, remove the rooms (so you can add them where you want).
Because in the editor, it is not possible to add dungeon heart/portal, I would add another room, like a crypt, and then edit the level manually to replace the crypt by dungeon heart/portal.

**Comment by akien-mga** [comment]
> Because in the editor, it is not possible to add dungeon heart/portal, I would add another room, like a crypt, and then edit the level manually to replace the crypt by dungeon heart/portal.

Thanks for the tip, that saves some time :-)

**Comment by akien-mga** [comment]
About the Bridge: I seem to win instantly when I start it in singleplayer.

**Comment by Bertram25** [comment]
> About the Bridge: I seem to win instantly when I start it in singleplayer.

Ah? weird. I'll have a look.

**Comment by hwoarangmy** [comment]
> Thanks for the tip, that saves some time :-)

Welcome ^^

**Comment by hwoarangmy** [comment]
Concerning the winning problem, I confirm I also have it. I guess it's coming from the fact that the goal is to kill every creature and at game start, there are none...
Might be cool to add "Destroy all ennemy buildings"

**Comment by Bertram25** [comment]
> Might be cool to add "Destroy all ennemy buildings"

Yep, was thinking the same. I'll do that. Has anyone news from @oyvindln concerning the Direct X question?

**Comment by Bertram25** [comment]
> Might be cool to add "Destroy all ennemy buildings"

After thinking about this, I do believe the Kill all enemy objectives should take in account enemy rooms spawning creatures, I'll add that.

**Comment by Bertram25** [comment]
N.B.: Adding the objective to destroy every room as a separate issue is a good idea. I may create it if everyone agrees.

**Comment by Bertram25** [comment]
The "You won" bug is fixed.

**Comment by Bertram25** [comment]
I will also take the time to tweak the level size a bit to make it more active. :)

**Comment by hwoarangmy** [comment]
ok. I will test when you are done

**Comment by Bertram25** [comment]
Ok, I should be done both for the map and the Objective text.

**Comment by Bertram25** [comment]
May I request we merge this even if @oyvindln hasn't answered yet, since IMHO, we're going on the OpenGL way. I'll be able to move on with the RC, then.

**Comment by akien-mga** [comment]
Looking good overall, merging.

**Comment by Bertram25** [comment]
Good, my turn to bring the RC and corresponding git stuff now :)

**Pull request merged**
