### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by hwoarangmy**

### CODE REVIEW

**Comment by Bertram25** [comment]
@hwoarangmy You're just unstoppable. ;) I'll have a look asap.

**Comment by akien-mga** [comment]
"Small fixes", but so many of them that's a "big improvement" :-D
Trying it right now.

**Comment by akien-mga** [comment]
As far as I'm concerned, this is good to merge :)

**Comment by Bertram25** [comment]
Let's merge then. @hwoarangmy will be able to tell us about the bit array and maybe fix this later on. It's trivial IMHO.

**Pull request merged**
