### PR TITLE
Small improvements + gem tile + better fighting logic + new damage type

### PR DESCRIPTION
**Pull request by hwoarangmy**

### CODE REVIEW

**Comment by hwoarangmy** [comment]
@Bertram25 Second chance if you want to test a PR ;-)

**Comment by Bertram25** [comment]
yes, ok, on it!

**Comment by Bertram25** [comment]
Code reviewed and nothing seen so far. I'll have a game or two tonight and tomorrow to test all that. :)

**Comment by Bertram25** [comment]
The beast is working so far. I love the new dynamic of fights. :D 
The only I haven't tested so far is gem tiles. I will now.

**Comment by Bertram25** [comment]
Btw, I had a segfault while playing. Here is the bt:

> Server sends newturn=1101
> Client (Bertram) received turnStarted=1101
> CLIENT (Bertram) - Removing Creature Roach37
> CLIENT (Bertram) - Adding Creature Roach37, seatId=4
> CLIENT (Bertram) - Adding Creature DwarfWorker163, seatId=5
> CLIENT (Bertram) - Adding rendered object RenderedMovableEntity_Dojo13_[25,26]_14,MeshName=WeaponShield2
> CLIENT (Bertram) - Adding rendered object RenderedMovableEntity_Dojo13_[26,26]_13,MeshName=TrainingDummy3
> CLIENT (Bertram) - Adding Creature Knight169, seatId=5
> CLIENT (Bertram) - Removing rendered object RenderedMovableEntity_Cannon_9_23,MeshName=Cannon
> CLIENT (Bertram) - Adding rendered object RenderedMovableEntity_Cannon_9_23,MeshName=Cannon
> CLIENT (Bertram) - Adding rendered object RenderedMovableEntity_Wizard166_933,MeshName=Cannonball
> CLIENT (Bertram) - Adding rendered object RenderedMovableEntity_Treasury__698,MeshName=GoldstackLv1
> CLIENT (Bertram) - Removing rendered object RenderedMovableEntity_Cannon_12_22,MeshName=Cannon
> CLIENT (Bertram) - Adding rendered object RenderedMovableEntity_Cannon_12_22,MeshName=Cannon
> CLIENT (Bertram) - Adding rendered object RenderedMovableEntity_Dormitory9_[30,34]_918,MeshName=Bed
> CLIENT (Bertram) - Removing rendered object RenderedMovableEntity_Cannon_10_20,MeshName=Cannon
> CLIENT (Bertram) - Adding rendered object RenderedMovableEntity_Cannon_10_20,MeshName=Cannon
> Computing turn 1102, timeSinceLastTurn=0.700984
> SERVER - Adding rendered object RenderedMovableEntity_Wizard167_934,MeshName=Cannonball
> 20 loops in Creature::doUpkeep name:Wyvern174 seat id: 2. Breaking out..
> SERVER - Adding rendered object RenderedMovableEntity_Dormitory_13_[1,14]_935,MeshName=GoblinBed
> signal 11 (Segmentation fault), address is 0x80 from 0x4f8763
> [bt]: (1) ./opendungeons : MissileObject::doUpkeep()+0x233 [0x4f8763]
> [bt]: (2) ./opendungeons : MissileObject::doUpkeep()+0x233 [0x4f8763]
> [bt]: (3) ./opendungeons : GameMap::doMiscUpkeep(double)+0x3a8 [0x568768]
> [bt]: (4) ./opendungeons : GameMap::doTurn(double)+0x436 [0x568d86]
> [bt]: (5) ./opendungeons : ODServer::startNewTurn(double)+0x2f7 [0x5fac27]
> [bt]: (6) ./opendungeons : ODServer::serverThread()+0x29d [0x5fb22d]
> [bt]: (7) /usr/lib/x86_64-linux-gnu/libsfml-system.so.2.3 : +0x8628 [0x7f2bf172e628]
> [bt]: (8) /lib/x86_64-linux-gnu/libpthread.so.0 : +0x80a4 [0x7f2bf360c0a4]
> [bt]: (9) /lib/x86_64-linux-gnu/libc.so.6 : clone+0x6d [0x7f2bf09b706d]

**Comment by Bertram25** [comment]
Tested the gem tiles. It makes it ready for longer battles :D 
the thing is, shouldn't we set a maximum workers per selected gem tiles?

Also had another idea: Should the gold info also tell the maximum gold you can get? like "5400 / 16000" for instance?

**Comment by Bertram25** [comment]
Should be mergeable to me, if @hwoarangmy can tell the bt isn't linked to latest changes, I guess?

**Comment by hwoarangmy** [comment]
> the thing is, shouldn't we set a maximum workers per selected gem tiles?

Clearly, yes. ATM, all your workers would go to dig it so we definitely need to do something. Moreover, we should decide how the AI should handle gem tiles (ATM, I guess it doesn't care about gem tiles)
BTW, note that this should be done in #565 as it is probably related

> Also had another idea: Should the gold info also tell the maximum gold you can get? like "5400 / 16000" for instance?

Sounds like a good idea. Worth an issue ?

Concerning the segfault, I guess its something we already saw so it is probably not linked to this PR. However, from looking at the code, I didn't see what can segfault in the missile doupkeep. DO you have an idea of what happened and what can have caused the segfault ? Do you think you can reproduce it ?

**Comment by Bertram25** [comment]
> Clearly, yes. ATM, all your workers would go to dig it so we definitely need to do something. Moreover, we should decide how the AI should handle gem tiles (ATM, I guess it doesn't care about gem tiles)
> BTW, note that this should be done in #565 as it is probably related

Indeed, it is completely related to #565 . Depending on the workers numbers, maybe the creature AI should check which % is doing this and that, and make workers do something else if that percentage is too high on something. This logic is clearly blown up when you have only one or two workers, so that need more thinking.

> > Also had another idea: Should the gold info also tell the maximum gold you can get? like "5400 / 16000" for instance?
> 
> Sounds like a good idea. Worth an issue ?

Ok, it's done :) #972 

> Concerning the segfault, I guess its something we already saw so it is probably not linked to this PR. However, from looking at the code, I didn't see what can segfault in the missile doupkeep. DO you have an idea of what happened and what can have caused the segfault ? Do you think you can reproduce it ?

Sincerely, I wish I could. Since it's based on missile, maybe a map full of wizards and cannons could help?

**Comment by Bertram25** [comment]
Let's merge that beast, and focus on what's next since no big regressions are there.

**Pull request merged**
