### PR TITLE
Removed non-existing user parameter warnings as it is a possibility.

### PR DESCRIPTION
**Pull request by Bertram25**

### CODE REVIEW

**Comment by Bertram25** [comment]
> Are you sure there is no way to avoid requesting non-existing values ?

I'm on limiting the cases, and I'll turn the error into an info.

**Comment by hwoarangmy** [comment]
@Bertram25 If the values are not mandatory, why don't you add some:
bool ConfigManager::hasVideoValue(const std::string& param) const
for optional values ?

**Comment by Bertram25** [comment]
Good idea. I'm still trying to limit other cases, though.

**Comment by hwoarangmy** [comment]
> I'm still trying to limit other cases, though.

Yeah, IMHO, it's always better to not remove error logs too fast. It saved me lot of time debugging thanks to those errors when you are sure to have written correctly the parameter name but forgot an upper char ^^

**Comment by Bertram25** [comment]
eh eh. So true. :)

**Pull request closed without merging**
