### PR TITLE
Implemented Arena + some code cleaning

### PR DESCRIPTION
**Pull request by hwoarangmy**
ATM, no creature will go to the arena by itself. However, they can all be dropped there.

### CODE REVIEW

**Comment by Danimal696** [comment]
Fantastic! what kind of models will it need? also, could you provide me with the blender version of summoner war skeleton? im going to use for the prison walls

**Comment by hwoarangmy** [comment]
> what kind of models will it need?

ATM, there is no central active spot. For wall active spots, I've used the same as training room (which are not bad IMO).
For the ground, I've used the same texture as crypt with some blood spots (also not too bad IMO).
I think what is currently used is acceptable so you can focus on something else ^^

> could you provide me with the blender version of summoner war skeleton

From what @fusion44 said, they used maya, not blender. I will have a look if we can import the models into blender but I don't know if it will be nice.

**Comment by Bertram25** [comment]
Great. I'll review all that asap :)

**Comment by hwoarangmy** [comment]
@Danimal696 For you to have a look ^^

odscreenshot_2015-11-14_112758_0

odscreenshot_2015-11-14_112811_1

**Comment by Danimal696** [comment]
maybe darker blood? nevermind, ill try something once its in my hands ;)

**Comment by hwoarangmy** [comment]
In any case, if you want to give a try from the blood texture I used, the link is in the credit file ^^

**Comment by Danimal696** [comment]
while we are at it, possible icons:
http://game-icons.net/lorc/originals/sword-clash.html
http://game-icons.net/lorc/originals/all-for-one.html
http://game-icons.net/delapouite/originals/aqueduct.html

I have no favourite at all

**Comment by hwoarangmy** [comment]
@Danimal696 I've already used aqueduct has we said in the issue

**Comment by Bertram25** [comment]
@hwoarangmy Nice work. I'll test asap.
Just the usual comments on takeDamage() and the bool parameter.

Btw, and it's the most important, I'm glad you're doing well in regard to what happened this week-end.

**Comment by Bertram25** [comment]
> I've achieved what I wanted in using the factories ie only have functional code in the room/trap and the building part in the corresponding factory :)

I do believe it's a very good investment, as the code looks slick now.

**Comment by hwoarangmy** [comment]
> Btw, and it's the most important, I'm glad you're doing well in regard to what happened this week-end.

Thanks. I was not in Paris when it happened.

> Just the usual comments on takeDamage() and the bool parameter.

Concerning takeDamage, I will try to remove the booleans and use another damage type "no defense" that will deal the specified damage no matter the target defense

**Comment by akien-mga** [comment]
I've played a bit with it and it seems to work fine, good to merge as far as I'm concerned (I haven't thoroughly reviewed the code changes though, but I believe @Bertram25 has). I'll let @Bertram25 push the button for once :p

**Comment by Bertram25** [comment]
Eh eh. Cool, I'll merge!

**Pull request merged**
