### PR TITLE
Use the keeper hand in the menus and in game + support creatures drop something on death + fixes

### PR DESCRIPTION
**Pull request by hwoarangmy**
I've removed the system cursor for windows

@akien-mga @Bertram25 I will let you handle the linux part in the InputManager to do the same if possible ^^

### CODE REVIEW

**Comment by oyvindln** [comment]
Do we really have to use the keeper hand in the menus?

**Comment by hwoarangmy** [comment]
> Do we really have to use the keeper hand in the menus?

Well, that's what was decided in the corresponding issue #420 and it was not easy to do. IMHO, it's better and it will allow to have a special hand animation when the player clicks a button.
But if you don't like it, we can add an entry in the configuration to allow to display it or to use the system cursor. Anyway, the setting menu is going to be one of he next most needed IMO.

**Comment by akien-mga** [comment]
> > Do we really have to use the keeper hand in the menus?
> 
> IMHO, it's better and it will allow to have a special hand animation when the player clicks a button.

I think it's quite nice to have the keeper hand in the menus, but we'll have to make sure that it's fitting for using our GUI. For now it must be pretty difficult on Windows to know precisely which level gets chosen if there is no OS cursor; on Linux we still have both so you know where the hand "clicks".

To make this better, we'll probably need a "hovering" animation where the hand points (with its index) to a specific button/combobox/etc.

**Comment by Bertram25** [comment]
+1 for the hand everywhere, with correct animations that said. :)

I will gladly test this BUT, eh, I think this should maybe not be part of 0.5.0 unless @Danimal696 tells us he can fix the missing hand animation for menus real soon.

I'm thus asking whether I should create a 0.5 branch now, before we merge this PR. WDYT?

**Comment by hwoarangmy** [comment]
I think we should let the hand everywhere. And probably let the system cursor as requested by @oyvindln.
WDYT ?

**Comment by Danimal696** [comment]
didnt hwoarangmy fix the new animation? or am i mistaken?

**Comment by Bertram25** [comment]
@Danimal696 I think you need to see it for yourself. We miss index finger pointing when hovering menus for the hand. It is looking really promising btw. :D 

@hwoarangmy I would let the cursor visible, at least for now. The feat is cool, while you still have the focal problem making the hand offset from the cursor depending on its screen position.
While the hand hasn't got a finger pointing animation and that the problem of camera focal isn't fixed for the hand overlay.

Apart from that, it looks great already and this is definitely what we want for the version 1.0!! :D

**Comment by Bertram25** [comment]
Ah, and should we add this feat to 0.5.0 guys? IMHO, with the cursor visible, it's good to go IMHO.

**Comment by hwoarangmy** [comment]
> didnt hwoarangmy fix the new animation? or am i mistaken?

Yes but it's hard to see what is really pointed when the system cursor is not there. You will see for the next release ;-)

**Comment by hwoarangmy** [comment]
IMHO, it should be in the 0.5.0

**Comment by Bertram25** [comment]
The focal problem is left but IMHO this is a real good improvement worth being part of the release.
the code is good and the feature is working for all the rest. I'd merge as well so that @Danimal696 can play with it, get annoyed and add a good hand animation for menus later. ;)

We might also get some help from outer players/devs with this feature in.

**Comment by Bertram25** [comment]
wow, didn't see all the new commits. I'll have a look. :)

**Comment by Bertram25** [comment]
I'll test now.

**Comment by Danimal696** [comment]
hwoarangmy you renamed the stock animations on blender, rigth? tell me their name so i can call them the same when adding extra animations

**Comment by Bertram25** [comment]
- Killed a Kobold transporting a research entity - Working fine.
- The map editor seems not to create tabs now when saving and looks like loading faster.
- The entity is indeed brought to the temple center.

IMHO, good to merge. :D

**Comment by hwoarangmy** [comment]
> hwoarangmy you renamed the stock animations on blender, rigth?

No I renamed them in the xml generated file. I was tired of fighting with blender and I didn't know how to see the different NLA tracks (and even less how to change their name).
If you open the console when launching OD, you can write "listanims KeeperHand" and you should see the list of all animations. We currently use "Idle", "Pickup", "Slap" and "Drop"

**Comment by hwoarangmy** [comment]
> Killed a Kobold transporting a research entity - Working fine.

That's not what I changed in this PR. Now, creatures can carry research entity you don't see (fighters). To test, you can launch the 2x2 skirmish small test map. There is a rogue wyvern in your dungeon. Once it is killed, it will release a research with room training room. The only way to make a creature carry such entity is to edit the level map (later, it will be possible to do that in the editor).

**Comment by Bertram25** [comment]
> That's not what I changed in this PR. Now, creatures can carry research entity you don't see (fighters). To test, you can launch the 2x2 skirmish small test map. There is a rogue wyvern in your dungeon. Once it is killed, it will release a research with room training room. The only way to make a creature carry such entity is to edit the level map (later, it will be possible to do that in the editor).

Ok, I'll test that. :)

**Comment by hwoarangmy** [comment]
@Bertram25 @akien-mga If everything goes well, I should have the portal claiming patch tonight or tomorrow. Could you please merge this one if there are no problems ?

**Comment by akien-mga** [comment]
I'll test the new PR inside the PR :)

**Comment by akien-mga** [comment]
For me this can be merged. I know that @hwoarangmy is eager to make a new PR, so I'll merge now :)

**Comment by Bertram25** [comment]
Cool thing in. :)

**Pull request merged**
