### PR TITLE
WarBanner - mesh for "Call to arms" spell

### LINKED ISSUE #836: Replacing mesh for "Call to arms spell"
Pretty soon
demo1

### PR DESCRIPTION
**Pull request by Danimal696**
Fixes #836.

with an animation called loop

### CODE REVIEW

**Comment by akien-mga** [comment]
It looks really nice in-game! :)
I'm not 100% convinced by the current Loop animation where the banner swings to the sides. But we can improve it later on :)

**Comment by akien-mga** [comment]
I'll do a pull request to make it used by the call to war spell.

**Comment by akien-mga** [comment]
What about the credits by the way? I can handle it in my pull request, but I'll need the name(s), license and link if there is one :)

**Comment by Danimal696** [comment]
ah, forgot those (strange, rigth?)

**Pull request merged**
