### PR TITLE
New forge objects & dropped tinyxml

### PR DESCRIPTION
**Pull request by Bertram25**
There is still an issue with Chimneys, so I'd request to merge only once @Danimal696 has fixed the model. :)

In the meanwhile, the new forge is looking awesome already. Apart from the chimney issue, feel free to comment. :)

### CODE REVIEW

**Comment by akien-mga** [comment]
Great :-D I'll test it tomorrow in the morning.

**Comment by akien-mga** [comment]
I've noticed that there are still a couple references to tinyxml and tinygettext in some files (README, FAQ.txt, od.cppcheck and OpenDungeons.cbp). Do you want to fix this in this PR?

There is:

```
$ ack -i tinygettext
FAQ.txt
328:TinyGetText

OpenDungeons.cbp
49:                     <Add directory="dependencies/tinygettext" />
164:            <Unit filename="dependencies/tinygettext/dictionary.cpp" />
165:            <Unit filename="dependencies/tinygettext/dictionary.hpp" />
166:            <Unit filename="dependencies/tinygettext/dictionary_manager.cpp" />
167:            <Unit filename="dependencies/tinygettext/dictionary_manager.hpp" />
168:            <Unit filename="dependencies/tinygettext/language.cpp" />
169:            <Unit filename="dependencies/tinygettext/language.hpp" />
170:            <Unit filename="dependencies/tinygettext/plural_forms.cpp" />
171:            <Unit filename="dependencies/tinygettext/plural_forms.hpp" />
172:            <Unit filename="dependencies/tinygettext/po_parser.cpp" />
173:            <Unit filename="dependencies/tinygettext/po_parser.hpp" />
174:            <Unit filename="dependencies/tinygettext/tinygettext.cpp" />
175:            <Unit filename="dependencies/tinygettext/tinygettext.hpp" />

od.cppcheck
6:              <dir name="dependencies/tinygettext"/>
10:             <dir name="dependencies/tinygettext"/>

README
33: |- tinygettext/ - Gettext alternative for multilang support
```

```
$ ack -i tinyxml
OpenDungeons.cbp
176:            <Unit filename="dependencies/tinyxml2/tinyxml2.cpp" />
177:            <Unit filename="dependencies/tinyxml2/tinyxml2.h" />
```

**Comment by Bertram25** [comment]
Ah, I should your habit of using ack. ;) Ok, I'll remove those. :)

> That's no big deal, but do we want to ensure the alphabetical order for the mesh names?

Ok, I'll reorder the beast.

**Comment by akien-mga** [comment]
> Ah, I should your habit of using ack. ;) Ok, I'll remove those. :)

It's pretty handy yes. In this case it only shows that you and @oyvindln did your job well, since there are absolutely no reference to tinygettext and tinyxml in the source code, only in some "additional" files.

**Comment by Bertram25** [comment]
Dang it, I wanted to write: "I should **steal** your habit..." Happens when I'm typing too fast I guess, eh.

Btw, I do think the cbp file is obsolete (since it is created by cmake normally). I'll remove it if @hwoarangmy is ok with it.

**Comment by Bertram25** [comment]
@akien-mga I rebased and applied the changes requested. I also finished #176 now the reordering part is done.

@hwoarangmy I'll also need your word on that PR, especially for the warnings part. :)

Once @Danimal696 has given me the fixed Chimney models, this one will be ready for a merge. :D

**Comment by Bertram25** [comment]
Ah, once I've added all the models, I'll squash together the commits to make those cleaner, and avoid doing duplicated iterations.

**Comment by Bertram25** [comment]
All the commits are now cleaned up. The beast is mergeable. :) The new models are awesome. ;)

**Comment by akien-mga** [comment]
The new map is great, and quite useful to have a quick look at our new models :-)

**Comment by Bertram25** [comment]
Thanks :)

**Comment by hwoarangmy** [comment]
Sorry, no time yesterday to test that. We will see when I will rebase if something happens :)

**Comment by Bertram25** [comment]
@hwoarangmy Don't be. I just hope it will be fine for you. :)
Hopefully, we're almost out of cmake/packaging problems. \o/ \o/ \o/

**Comment by Bertram25** [comment]
Btw, I've made the new level to test a few things on my own and later use it as a reference when we'll be working on the AI, and to test the editor usability. :)
(First thing I've forgotten, btw, is to add a spawn pool to team 5. I'll fix this.)

Just to say that even if the editor feels somewhat more experimental than the regular game, I was able to create this level within a hour. :D So it's definitely a great improvement.
Btw, now I've tested it more, I confirm the current backup system is just fine and shouldn't be changed.
Sorry for reporting false positives.

**Pull request merged**
