### PR TITLE
Add a script to retrieve materials corresponding to textures and meshes

### PR DESCRIPTION
**Pull request by akien-mga**
The original script from #579 is in cac6a01, then I improved it a bit based on @oyvindln's suggestions.
I put it in a tools/ directory and move my Linux portable binary creation scripts there too as it's more fitting.

I also moved Dm3d to past contributors since he's not active anymore.

### CODE REVIEW

**Comment by hwoarangmy** [comment]
The scripts seem pretty well done. I will let @Bertram25 or @oyvindln play with them as I don't have a linux machine to test ^^

**Comment by Bertram25** [comment]
Works great but beware you didn't check for ack existence. ;)
Ah, and I would tell the usual package name where Ogre tools and ack are found.

Mergeable in any case, IMHO. This can be added later.

**Comment by akien-mga** [comment]
> Works great but beware you didn't check for ack existence. ;)
> Ah, and I would tell the usual package name where Ogre tools and ack are found.

Done :-)

**Comment by akien-mga** [comment]
I keep adding stuff in there :-)

Next step will be to make a synthesis with something like:

```
[model filename]
 - [material name]  ([script filename])
    o [texture1 filename]
    o [texture2 filename]
    o ...
...
```

**Comment by Bertram25** [comment]
Cool! :D Will test asap. #579 and #492 will be trivial to fix now.

**Comment by Bertram25** [comment]
textures_unused.log:
Seems there is a bug on ack invocation.

```
[texture filename]: [files referencing it]

AdventurerBed.png:  ack v1.39 Copyright 1993,94 Ogasawara Hiroyuki (COR.)
usage: ack [-{e|s|j|c[c]}] [-{a|A|o<file>}] [-zCntud] [-{E|S}] [<file>..]
...
```

meshes_tree.log:
Seems the script is never told and no texture is listed as well.

```
[mesh filename]:
 - [material name] ([script filename])
     * [texture filename]

AdventurerBed.mesh
 - AdventurerBed ()
Adventurer.mesh
 - Adventurer ()
Anvil.mesh
 - Anvil ()
Axe1.mesh
 - axt ()
...
```

Tested on Debian Sid/Exp.

**Comment by akien-mga** [comment]
Hm indeed I have ack 2.14 and may have used functionalities that were not available in Debian's ack 1.39. I'll try to identify which ones and do without them :)

**Comment by Bertram25** [comment]
> Hm indeed I have ack 2.14 and may have used functionalities that were not available in Debian's ack 1.39. I'll try to identify which ones and do without them :)

Too bad Debian is lagging behind about this package, though.

**Comment by Bertram25** [comment]
@akien-mga Wait! Debian has both an ack and a newer ack-grep package. I'll test all that now.

**Comment by akien-mga** [comment]
> > Hm indeed I have ack 2.14 and may have used functionalities that were not available in Debian's ack 1.39. I'll try to identify which ones and do without them :)
> 
> Too bad Debian is lagging behind about this package, though.

I guess it's considered a core package like grep or awk and they have cold feet for new major versions in such software :-)
I found a nice description of what's new in ack 2.x, so I can already see that --ignore-file might be problematic: http://beyondgrep.com/ack-2.0/

**Comment by Bertram25** [comment]
My bad, ack is a kanji code converter, ack grep is the core util.

**Comment by akien-mga** [comment]
> My bad, ack is a kanji code converter, ack grep is the core util.

Hehe, indeed the kanji code converter probably won't do the trick ;-)
Is the binary still /usr/bin/ack (thus conflicting with the "ack" package from debports), or is it named differently?

**Comment by Bertram25** [comment]
> Hehe, indeed the kanji code converter probably won't do the trick ;-)

Yeah, plus it doesn't tell much when called from scripts and command line, easily misleading, IMHO.

> Is the binary still /usr/bin/ack (thus conflicting with the "ack" package from debports), or is it named differently?

I'll tell you after a reboot. ;)

**Comment by Bertram25** [comment]
> Is the binary still /usr/bin/ack (thus conflicting with the "ack" package from debports), or is it named differently?

Funnily, an ack-grep binary is added with an alias to ack. I'm testing the script atm. I'll test whether there is a conflict when you install both, though. There might be a bug. ;)

**Comment by Bertram25** [comment]
Works well now. Every scripts behave as expected. :)

ack has a conflict dependency to ack-grep on Debian as a side note. This is IMHO a kinda funny way to handle it but at least the packages aren't broken.

I'll merge now.

**Comment by Bertram25** [comment]
#492 and #579 can be dealt with easily now. I'd request to move the unused textures and potential models to the media repo, for instance in: models_unused and materials_unused/textures as a start.
The media repo can be cleaned up afterwards.

**Comment by akien-mga** [comment]
> I'd request to move the unused textures and potential models to the media repo, for instance in: models_unused and materials_unused/textures as a start.
> The media repo can be cleaned up afterwards.

Sounds good. I'll be on it for 0.5.0, the less unused stuff we ship, the smaller the source tarball and binary packages :)

**Comment by Bertram25** [comment]
Thanks :D

**Pull request merged**
