### PR TITLE
Drop FAQ, multiplayer The Bridge, improve seat colour

### PR DESCRIPTION
**Pull request by akien-mga**

### CODE REVIEW

**Comment by Bertram25** [comment]
I'll try asap.

**Comment by akien-mga** [comment]
To "test" the seat colours in game, I modified Scream in the Dark to use the colorIDs 1, 5, 6, 7 and 8, and then used togglefow to see everything.

BTW I've noticed that togglefow only takes like 1 s to load the entire map on my i5 CPU with Intel HD 4000 GPU, so the performance concerns that we discussed regarding #666 are maybe not that bad.

**Comment by akien-mga** [comment]
Feel free to tell me if there is stuff from FAQ.txt that I haven't ported to the wiki and that we should keep. I left on purpose the "Help!" stuff as I think it's mostly irrelevant now, CMake should make sure people don't build against the wrong Ogre or CEGUI version or stuff like that.
As for the gameplay description, there is already the in-game help and the gameplay wiki page, I did not check whether the FAQ.txt had info that those might be lacking though.

**Comment by Bertram25** [comment]
About the FAQ, I think you drop the obsolete chunks so I'm fine with what was added in https://github.com/OpenDungeons/OpenDungeons/wiki/FAQ

The rest was already part of the wiki anyway.

**Comment by akien-mga** [comment]
I've reworked the README a bit too.

**Comment by Bertram25** [comment]
Is fine. Can I merge?

**Comment by akien-mga** [comment]
Maybe we should add this to the coding guidelines?
http://xkcd.com/1513/
:-D

**Comment by Bertram25** [comment]
Eh eh. @hwoarangmy . Feel free to merge when you're ok with it. :)

**Comment by akien-mga** [comment]
I'll merge myself as I think it's not too disruptive. @Bertram25 Can you merge the current development branch in 0.5? Since neither @hwoarangmy nor @oyvindln's branches have been merged, there is no need to cherry-pick yet.

**Pull request merged**
