### PR TITLE
Added a popup when about to change the renderer + other related improvements

### PR DESCRIPTION
**Pull request by Bertram25**
- Added the aforementioned pop-up.
- Made the settings related windows modal.
- Save the renderer-independent options in any case.

### CODE REVIEW

**Comment by Bertram25** [comment]
@hwoarangmy Should be good now. :)

**Comment by hwoarangmy** [comment]
I'm trying

**Comment by hwoarangmy** [comment]
works well

**Comment by Bertram25** [comment]
Good :)

Now on the custom settings support.

**Pull request merged**
