### PR TITLE
Dropped tinygettext, fixed application exit

### PR DESCRIPTION
**Pull request by oyvindln**
This drops tinygettext as per #132 
I also found that the destructor in ODApplication was never called. I fixed this, as well as changing it to not be a singleton object. The game seems to exit fine but I am not completely sure everything is being deleted properly and in correct order. Ideally we would use less singletons so there was a more clear hierarchy.

### CODE REVIEW

**Comment by Bertram25** [comment]
Nice stuff :) Especially the fact to catch the OD application singleton as a problem when quitting. This was anything but obvious until one tells you, IMHO.

The whitespace can be trivially fixed later, btw.

I'll test this asap, and wait for @akien-mga and @hwoarangmy for more testing, especially on windows (sometimes different behaviour are encountered there.)

Thanks for the help. :)

**Comment by hwoarangmy** [comment]
I will also try it ASAP with Windows - MinGW :)

**Comment by akien-mga** [comment]
Thanks for dropping tinygettext :-)

Tested on Mageia, the PR is fine as far as I'm concerned.
Shutting down OD now seems to unload everything properly, that's great:

```
Closing down.
Remove listener registration
Window closed
*** Deinitializing Console ***
*** Destroying Input Manager ***
Deleting AS Wrapper
Frame listener uninitialization done.
Quitting main application...
Stopping server...
Processing deletion queues on turn -1
Disconnecting client...
Removing ODFrameListener from root...
Deleting ODFrameListener...
Deleting Ogre::OverlaySystem...
Unregistering ResourceManager for type Font
Deleting MusicPlayer...
Deleting TextRenderer...
Deleting Gui...
Deleting SoundEffectsManager...
Deleting ODServer...
Deleting ODClient...
Deleting ResourceManager...
Deleting LogManager and Ogre::Root...
DefaultWorkQueue('Root') shutting down on thread 7f1c64dad780.
DefaultWorkQueue('Root')::WorkerFunc - thread 7f1c55e51700 stopped.
DefaultWorkQueue('Root')::WorkerFunc - thread 7f1c55650700 stopped.
DefaultWorkQueue('Root')::WorkerFunc - thread 7f1c56652700 stopped.
DefaultWorkQueue('Root')::WorkerFunc - thread 7f1c54e4f700 stopped.
*-*-* OGRE Shutdown
Unregistering ResourceManager for type Compositor
Unregistering ResourceManager for type Skeleton
Unregistering ResourceManager for type Mesh
Unregistering ResourceManager for type HighLevelGpuProgram
Uninstalling plugin: Octree Scene Manager
Plugin successfully uninstalled
Unloading library /lib64/OGRE/Plugin_OctreeSceneManager
Uninstalling plugin: GL RenderSystem
Render Target 'OpenDungeons 0.4.9' Average FPS: 56.0147 Best FPS: 59.0551 Worst FPS: 41.2446
Unregistering ResourceManager for type GpuProgram
******************************
*** Stopping GLX Subsystem ***
******************************
Unregistering ResourceManager for type Texture
Plugin successfully uninstalled
Unloading library /lib64/OGRE/RenderSystem_GL
Unregistering ResourceManager for type Material
```

**Comment by hwoarangmy** [comment]
It's ok with MinGW. Good job :)
Could you fix the TODO and the space problem ?

**Comment by Bertram25** [comment]
It's fine. I've merged. App quit crash definitely fixed thanks to you. :)

**Pull request merged**
