### PR TITLE
Minor cleanups

### PR DESCRIPTION
**Pull request by oyvindln**
Finished moving events out of gui.cpp
Also fixed a potentional issue in minimap, due to a typo (& instead of %).

### CODE REVIEW

**Comment by Bertram25** [comment]
I'll test asap.

**Comment by akien-mga** [comment]
It builds and runs fine, and I did not notice any regression with the minimap.

**Comment by hwoarangmy** [comment]
Tesing now

**Comment by hwoarangmy** [comment]
Works well merging

**Comment by Bertram25** [comment]
great! :)

**Pull request merged**
