### PR TITLE
Fix for #87, #168, #172 and #183

### PR DESCRIPTION
**Pull request by Bertram25**

### CODE REVIEW

**Comment by Bertram25** [comment]
The forge models are lacking but this won't be for tonight. ;)

**Comment by Bertram25** [comment]
@hwoarangmy The TrainingDummy selection bug should be fixed now.

**Comment by hwoarangmy** [comment]
ok, I will try asap

**Comment by hwoarangmy** [comment]
ok, for me. I will let @akien-mga test and if he sees nothing, we can merge

**Comment by akien-mga** [comment]
> ok, for me. I will let @akien-mga test and if he sees nothing, we can merge

Tested, and I did see things: awesome new models and level names and descriptions :-D
I couldn't find the light indicator in the oldTest map, but the map is quite big, so I must have missed it.

**Pull request merged**
