### PR TITLE
New creature + lots of rebalancing 

### PR DESCRIPTION
**Pull request by Danimal696**
It seems there is garbage from my pulling practices, they erase each other so it should be fine, the one about the new creature and balancing is the real pull

### CODE REVIEW

**Comment by hwoarangmy** [comment]
cool. Can't wait to see what the defenser looks like in game ^^

**Comment by Bertram25** [comment]
To the whole team: Please do not merge this PR as it has got a lot of unnecessary stuff in it.
Once the last commit in this PR is accepted, I'll cherry-pick the last commit only and close the PR.

Btw, I'll have to delete the branch created in the main repo.

@Danimal696 For the next time, but only once this PR is closed, I think you will need to delete your local clone and start anew. All that said, it's cool to see you learning. :)

**Comment by Bertram25** [comment]
> cool. Can't wait to see what the defenser looks like in game ^^

Me too, me too. :)

**Comment by Danimal696** [comment]
ok, ill reclone it

**Comment by akien-mga** [comment]
@Danimal696 If you want to reclone it without losing your work, here is what you could do:
- In your current clone, run `git format-patch -1`. It should create a file named 0001-New-creature-+-lots-of-rebalancing.patch or something like that. Then you can move it to another place to save it for later.
- In another directory, clone your own fork with: `git clone https://github.com/Danimal696/OpenDungeons.git`. This way you won't change the main repo when doing modifications, and only use the PR system to move changes from your fork to the main repo.
- Then in the new clone, you can start by making it up-to-date with the main repo with: `git pull https://github.com/OpenDungeons/OpenDungeons.git development`
- Copy the 0001*.patch file you got earlier in your new clone, and reapply it with: `git apply 0001-New-creature-+-lots-of-rebalancing.patch` It should commit the changes, you can check them with `git log`
- If it's looking good (i.e. the second to last commit should be @Bertram25 merging PR #368, and the last commit should be your balancing changes + new model), you can push them to your repo with `git push`
- Then you can create a new PR (the web view of your fork should tell you that you are "1 commit ahead" of OpenDungeons:development.

**Comment by Bertram25** [comment]
@Danimal696 I don't mind if you reclone it only after the merge of the commit. I'll gladly cherry-pick the commit if necessary. :)

@akien-mga I don't know whether you already tested the formatting the patch and reapplying it, but I know it can somehow fail when including a mix between binray and text files. I just hope it will go well. :)
Thanks a lot for the how-to, btw.
Seems to me you're becoming some kind of git guru yourself. ;)

**Comment by Danimal696** [comment]
ill try and do something cleaner

**Comment by Danimal696** [comment]
What the hell!?! i didnt push that to the main! please someone revert it

**Comment by Bertram25** [comment]
Lol, yes you did. ;)

Either you kept the former folder which seemingly kept an upstream link to the main repo in the .git/ folder, or you cloned the main repo once again.

I guess next time you reclone, you should erase the former folder and do this:
`git clone git@github.com:Danimal696/OpenDungeons.git development`

This will create an OpenDungeons folder local clone of your own fork.

I'll undo the commit and delete the branch names created on the main repo.

**Comment by Danimal696** [comment]
thanks, im using git, not the console, but its as confusing or much more

**Comment by Bertram25** [comment]
> thanks, im using git, not the console, but its as confusing or much more

Yeah, I can understand that. That's a reason I usually use the console. It does hide less things usually.
When you say you're not using the console, I guess you're using github for windows, right?

**Comment by Danimal696** [comment]
yep

**Comment by Bertram25** [comment]
Ok, the main repo has been cleaned up. You can open a PR now. :)

**Pull request closed without merging**
