### PR TITLE
Add config manager + other fixes

### PR DESCRIPTION
**Pull request by hwoarangmy**

### CODE REVIEW

**Comment by akien-mga** [comment]
Be careful with your big PRs, GitHub watches you! :-P

**Comment by hwoarangmy** [comment]
yes, they might think I am a robot ^^

**Comment by Bertram25** [comment]
Woah, this rocks. :D 

The game config management feels professional now. Eager to test all that.

**Comment by akien-mga** [comment]
@hwoarangmy I'm getting this error when compiling on Mageia (GCC 4.9.2):

```
[akien@localhost build-hwo (hwo-dev)]$ make
[  1%] Building CXX object CMakeFiles/opendungeons.dir/source/utils/Helper.cpp.o
/home/akien/Projects/opendungeons/OpenDungeons/source/utils/Helper.cpp: In function 'bool Helper::readFileWithoutComments(const string&, std::stringstream&)':
/home/akien/Projects/opendungeons/OpenDungeons/source/utils/Helper.cpp:113:37: error: variable 'std::ifstream baseLevelFile' has initializer but incomplete type
         std::ifstream baseLevelFile(fileName.c_str(), std::ifstream::in);
                                     ^
/home/akien/Projects/opendungeons/OpenDungeons/source/utils/Helper.cpp:113:55: error: incomplete type 'std::ifstream {aka std::basic_ifstream<char>}' used in nested name specifier
         std::ifstream baseLevelFile(fileName.c_str(), std::ifstream::in);
                                                       ^
CMakeFiles/opendungeons.dir/build.make:3090: recipe for target 'CMakeFiles/opendungeons.dir/source/utils/Helper.cpp.o' failed
make[2]: *** [CMakeFiles/opendungeons.dir/source/utils/Helper.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/opendungeons.dir/all' failed
make[1]: *** [CMakeFiles/opendungeons.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2
```

Don't mind the `[ 1%]`, it just badly computed when restarting `make` on an incomplete build.

**Comment by hwoarangmy** [comment]
> I'm getting this error when compiling on Mageia

Since I moved this code from another file, I guess there is a problem with included files. Could you please try to add in the include section:
`#include <fstream>`

If it fixes your compilation problem, I will upload the fix tonight.

**Comment by akien-mga** [comment]
It fixes the compilation issue, thanks.

**Comment by hwoarangmy** [comment]
> It fixes the compilation issue, thanks.

Thanks for the feedback. I will upload the fix tonight

**Comment by hwoarangmy** [comment]
The bug seen by @akien-mga should be fixed. I've also added the possibility to extend a class asked by @Bertram25 in my previous PR ^^

@akien-mga Note that an interesting test when playing with code that changes creature definition handling is to open a level in the editor and saving it directly (not changing anything or changing almost nothing). When you do that, the level should be equal to its backup if nothing was broken ^^
Also note, if you try that, that the creaturedefinition and weapondefinition tags may be added in the levels they do not exist (even if they are empty).

**Comment by Bertram25** [comment]
Nice change. I've got nothing to say about the patch.
If everything goes well, I'll be able to test this evening. :)

**Comment by Bertram25** [comment]
OK,
Trap destruction working.
Config manager working (I tried changing the color + file names) + Colors retained through different games now color handling is centralized.
The base definition parameter is working.
And the You won messages are both working, even if it's rather hard to beat a game atm. XD
I think a message like: "Player X has lost" is missing but we'll talk about this later.

**Pull request merged**
