### PR TITLE
Enabled tests in appVeyor + added a test that ensures that game can be launched

### PR DESCRIPTION
**Pull request by hwoarangmy**
part of #578

### CODE REVIEW

**Comment by akien-mga** [comment]
I get a linking issue with boosttest-source_tests-Goal:

```
Linking CXX executable ../../boosttest-source_tests-Goal
CMakeFiles/boosttest-source_tests-Goal.dir/__/utils/LogManager.cpp.o: In function `LogManager::logMessage(LogMessageLevel, char const*, int, std::string const&)':
/home/akien/Projects/opendungeons/OpenDungeons/source/utils/LogManager.cpp:60: undefined reference to `boost::filesystem::path::stem() const'
/home/akien/Projects/opendungeons/OpenDungeons/source/utils/LogManager.cpp:83: undefined reference to `boost::filesystem::path::filename() const'
CMakeFiles/boosttest-source_tests-Goal.dir/__/utils/LogManager.cpp.o: In function `__static_initialization_and_destruction_0':
/usr/include/boost/system/error_code.hpp:222: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:223: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:224: undefined reference to `boost::system::system_category()'
collect2: error: ld returned 1 exit status
source/tests/CMakeFiles/boosttest-source_tests-Goal.dir/build.make:164: recipe for target 'boosttest-source_tests-Goal' failed
```

Same thing for the LaunchGame test with missing references to boost_system and boost_filesystem.

**Comment by akien-mga** [comment]
It builds fine with:

```
diff --git a/source/tests/CMakeLists.txt b/source/tests/CMakeLists.txt
index 6bacb78..d3a709e 100644
--- a/source/tests/CMakeLists.txt
+++ b/source/tests/CMakeLists.txt
@@ -30,6 +30,7 @@ add_boost_test(Goal
         "${SRC}/utils/LogManager.cpp"
         "${SRC}/utils/LogSinkConsole.cpp"
         LIBRARIES
+        ${Boost_LIBRARIES}
         ${SFML_LIBRARIES})

 add_boost_test(Pathfinding
@@ -50,4 +51,5 @@ add_boost_test(LaunchGame
         ${SRC}/utils/LogSinkConsole.cpp
         test_LaunchGame.cpp
         LIBRARIES
-        ${SFML_LIBRARIES})
\ No newline at end of file
+        ${Boost_LIBRARIES}
+        ${SFML_LIBRARIES})
```

I don't know though if linking against the whole pack of Boost_LIBRARIES leads to overlinking or if it's fine this way.

**Comment by hwoarangmy** [comment]
> I don't know though if linking against the whole pack of Boost_LIBRARIES leads to overlinking or if it's fine this way.

That's probably a bug introduced by the change in logging logic from @knight666 patch. We can always link against the needed libraries only. I think the whole thing will be fixed when we will enable unit test on appVeyor + Travis. I will have a look.

> Could you name the file "TestUnitTest.level" to match the other test levels?

Well, I had something else in mind. First, when unit test will work, I thought about using a special folder as we don't want unit test maps to be changed (and a new program option to launch them from the good folder).
Secondly, I thought about coding in the test name the testing process (for example, if it requires to launch a server with the specific test map) so that we can launch a script that would list all boosttest-source_tests-\* and will do required stuff. This way, adding a new unit test would not require to change the tests scripts (because it would be easy when testing on windows, to not update the linux script and an error would not be visible)

**Comment by akien-mga** [comment]
> Well, I had something else in mind. First, when unit test will work, I thought about using a special folder as we don't want unit test maps to be changed (and a new program option to launch them from the good folder).

Sounds good yes.

> Secondly, I thought about coding in the test name the testing process (for example, if it requires to launch a server with the specific test map) so that we can launch a script that would list all boosttest-source_tests-\* and will do required stuff. This way, adding a new unit test would not require to change the tests scripts (because it would be easy when testing on windows, to not update the linux script and an error would not be visible)

That would indeed prevent us from having to maintain concurrent testing scripts for all platforms, etc.. In the meantime, I've made a linux shell script that matches your batch script:

```
#!/bin/sh
# Shell script to run the unit tests for OpenDungeons

OD_BINARY="opendungeons"
UNIT_TESTS="ConsoleInterface Random Goal ODPacket Pathfinding LaunchGame"

if [ ! -x $(pwd)/${OD_BINARY} ]; then
    echo "Can't find the ${OD_BINARY} binary in the current directory, aborting."
    exit 0
fi

TESTS_PASSED=""
TESTS_FAILED=""

for test in ${UNIT_TESTS}; do
    echo -e "\n### Unit test: ${test}\n"

    if [ ${test} == "LaunchGame" ]; then
        ./${OD_BINARY} --server UnitTest.level --port 32222 --log srvLog.txt &
    fi
    ./boosttest-source_tests-${test}

    if [ $? == 0 ]; then
        TESTS_PASSED+=" ${test}"
    else
        TESTS_FAILED+=" ${test}"
    fi
done

echo -e "\n#####################################"
echo "The following tests were PASSED: ${TESTS_PASSED}"
echo "The following tests were FAILED: ${TESTS_FAILED}"
echo -e "#####################################\n"
```

(If it looks good to you I'll do a PR once yours is merged).

**Comment by hwoarangmy** [comment]
> I've made a linux shell script that matches your batch script

Cool ^^

Like in yours, I first thought about running all tests so that we know which are ok or not. However, the problem is that if one fails, we are not sure the others can be run. That's because we launch OD in server mode. And since a failed test might not launch the game (and stop the server once it is done), it might make a test launch the wrong test map or something similar. That's why I decided to stop at the first failing test (so that it is clear which one first failed as it might be the root to another failing test).

**Comment by hwoarangmy** [comment]
@akien-mga I've enabled tests on travis (mostly because I needed to trigger a build because the error I had was because of a missing library in the win32 dependencies). If everything goes well with appVeyor, could you please handle the travis part (adding the still missing boost libraries + your script) ?

Thanks

**Comment by hwoarangmy** [comment]
@akien-mga Everything goes well on appVeyor. If you want to handle the travis part, please merge and play with the scripts ^^
If not, let me know and I will do that here.

**Comment by akien-mga** [comment]
Sure, I'll have a go at it.

**Pull request merged**
