### PR TITLE
New GUI with better controls and menus

### LINKED ISSUE #5: New UI: Add a common in-game window fitting the main menu style
I might also fix a few controls on the way

### PR DESCRIPTION
**Pull request by Bertram25**
- New in game window GUI + several new or improved controls.
- Split join and host game to make it much more user-friendly.
- Added the inner map name and description in the loading menus.

Fixes #5 #127

### CODE REVIEW

**Comment by Bertram25** [comment]
Ah, fixes also #40 as the commit was simple.

**Comment by Bertram25** [comment]
Just a teaser of the thing (from CEED): ;)
gui-preview

**Comment by akien-mga** [comment]
Wow, looks great :-D
I guess I should have a look at packaging CEED for Mageia.

I'll try to fix my install (or do a fresh one on another partition) to test this with a functioning OD :-)

**Comment by hwoarangmy** [comment]
That looks nice in the image
I will test that tonight :)

**Comment by Bertram25** [comment]
I wish CEED was much more known. It is indeed becoming a more and more interesting tool for GUI design. :)

**Comment by hwoarangmy** [comment]
I'm compiling. Will test it soon :)

**Comment by hwoarangmy** [comment]
Ok, that's good for me. I think it would be better to have only 1 place for OD version to make sure the displayed value is always correct. If you don't want to change that or you want to do that later, I will merge :)
But the menu is really nice like that. Good job :)

**Comment by Bertram25** [comment]
Thanks a lot :) I'll deal with the game version on my next PR.

**Comment by hwoarangmy** [comment]
ok

**Comment by akien-mga** [comment]
I haven't had time to test it thoroughly, but I'm just slightly concerned about the fact that the main menu buttons draw a Christian cross :-) I may be the only one to notice it, if so it's okay, but I think we should try to avoid symbols that could bother some of our users IMO.

**Comment by Bertram25** [comment]
Dang it, you're right. I'll fix this asap.

**Pull request merged**
