### PR TITLE
Updated SFML cmake file + do not show mood overlay to enemy players

### PR DESCRIPTION
**Pull request by hwoarangmy**

### CODE REVIEW

**Comment by Bertram25** [comment]
Testing...

**Comment by Bertram25** [comment]
Works fine to me. :)

**Comment by hwoarangmy** [comment]
Note that if you want to test easily, you can do a savegame where you have vision on an enemy unit (not rogue seat) and edit the level to set its hunger/awakness to 100/0. If everything goes well, you should not see the mood overlay ^^

**Comment by akien-mga** [comment]
BTW when testing the CMake, make sure to start from a clean repo (without CMakeCache.txt), else it might say that it found SFML just because it's already referenced in the cache.

**Comment by akien-mga** [comment]
I think @Bertram25 and I are both somewhat busy these days, but it doesn't make sense to let this PR idle for too long IMO, I don't see changes that would really threaten stability :)

**Pull request merged**
