### PR TITLE
Drop bin suffix on Linux and the launch script (fixes #57)

### LINKED ISSUE #57: Linux: Drop the ".bin" binary suffix (i.e. encode the data path into the binary?)
I've started some work on the CMakeLists.txt (I'll push it to my fork soon so that it can be reviewed), and dropping the ".bin" binary suffix is not as straight-forward as it looks like.

Currently the file cmake/config/OpenDungeons.in is used to generate a bash script that runs OpenDungeons.bin with the needed environment variable to let OD find its data:

```
#!/bin/sh
OPENDUNGEONS_DATA_PATH="/usr/share/games/opendungeons" exec "/usr/games/OpenDungeons.bin" "$@"
```

If we want to drop the ".bin" suffix (and set the binary name in lower case on Linux if possible), we need to find another way to let OpenDungeons know the location of the data directory (currently defined as OPENDUNGEONS_DATA_PATH here: https://github.com/OpenDungeons/OpenDungeons/blob/development/CMakeLists.txt#L507 ).

Any idea about how this could be done (i.e. how most games do it)? It looks somewhat messy to have a broken (as in, you can't execute it properly) OpenDungeons.bin binary in /usr/games and a script to make it work.

### PR DESCRIPTION
**Pull request by akien-mga**
Also:
- Remove some obsolete installation instructions
- Move OD-specific debug flag to project definition

Note that the credits for fixing #57 all go to @Bertram25, basically I'm just removing ".bin" from CMakeLists.txt ;-)

### CODE REVIEW

**Comment by akien-mga** [comment]
Then I'm on #58.

**Comment by Bertram25** [comment]
Hey,
Thanks for taking care of that. :)
I think you can also drop those unused two:
-> OpenDungeonsDebug.sh
-> OpenDungeonsNoStdoutNoStderr

I'll test the rest asap. ;)

**Comment by akien-mga** [comment]
Done :-)

**Comment by Bertram25** [comment]
Thanks :)

**Comment by akien-mga** [comment]
I might have installation instructions ready in a little while, do you want me to add them to this PR, or wait until this easy one has been validated?

**Comment by akien-mga** [comment]
I have working installation instructions \o/
I'll wait for this PR to be pushed though, since it's quite straight-forward, and what's incoming might need some adjustments.

**Comment by Bertram25** [comment]
Agreed. Here, especially as this part should be easily merged as you said.

My habit of adding more and more commits on a PR is a bad one, and I know it, eh. ;)

**Comment by akien-mga** [comment]
I'll start the integration of my other changes in another branch based on my development branch.

**Comment by Bertram25** [comment]
Testing now :)

**Comment by Bertram25** [comment]
Works fine :) Merging.

**Pull request merged**
