### PR TITLE
Troll bed

### PR DESCRIPTION
**Pull request by Danimal696**
No normals yet

### CODE REVIEW

**Comment by Danimal696** [comment]
http://forum.freegamedev.net/viewtopic.php?f=45&t=4765&p=62443#p62443 for normals isssue

**Comment by Danimal696** [comment]
http://forum.freegamedev.net/viewtopic.php?f=38&t=5866&p=62444#p62444

**Comment by Bertram25** [comment]
@Danimal696 Mind updating the CREDITS file mimicing the other entries? ;P Eh eh, I know you will want my head for that, but we'll have to sort this out on the OD battlefield.

**Comment by Danimal696** [comment]
> we'll have to sort this out on the OD battlefield.

how im gonna enjoy flooding you with killer gnomes

**Comment by Danimal696** [comment]
this pull its gonna keep growing nonstop if you dont do something!

**Comment by hwoarangmy** [comment]
I promise I will test tonight ;-)

**Comment by akien-mga** [comment]
Looks fine for me :-)

_Edit:_ Maybe indentation should be fixed before I merge?

**Comment by hwoarangmy** [comment]
I'm testing

**Comment by hwoarangmy** [comment]
works well, I merge

**Pull request merged**
