### PR TITLE
Misc fixes...

### PR DESCRIPTION
**Pull request by Bertram25**

### CODE REVIEW

**Comment by akien-mga** [comment]
Code looks good, I'm compiling right now.

**Comment by akien-mga** [comment]
I get a segfault when quitting a game with an active event displayed:

```
signal 11 (Segmentation fault), address is 0xfffffffffffffff8 from 0x53ce1f

[bt]: (1) ./opendungeons : GameEditorModeBase::~GameEditorModeBase()+0x9f [0x53ce1f]
[bt]: (2) ./opendungeons : GameEditorModeBase::~GameEditorModeBase()+0x9f [0x53ce1f]
[bt]: (3) ./opendungeons : GameMode::~GameMode()+0x237 [0x5311f7]
[bt]: (4) ./opendungeons : GameMode::~GameMode()+0x9 [0x531249]
[bt]: (5) ./opendungeons : ModeManager::removeMode()+0x52 [0x55c912]
[bt]: (6) ./opendungeons : ModeManager::checkModeChange()+0x85 [0x55d1b5]
[bt]: (7) ./opendungeons : ModeManager::update(Ogre::FrameEvent const&)+0x13 [0x55d1d3]
[bt]: (8) ./opendungeons : ODFrameListener::frameRenderingQueued(Ogre::FrameEvent const&)+0xc8 [0x5a8cf8]
[bt]: (9) /lib64/libOgreMain.so.1.9.0 : Ogre::Root::_fireFrameRenderingQueued(Ogre::FrameEvent&)+0x65 [0x7f68b8b41335]
[bt]: (10) /lib64/libOgreMain.so.1.9.0 : Ogre::Root::_fireFrameRenderingQueued()+0x21 [0x7f68b8b41821]
[bt]: (11) /lib64/libOgreMain.so.1.9.0 : Ogre::Root::_updateAllRenderTargets()+0x22 [0x7f68b8b41852]
[bt]: (12) /lib64/libOgreMain.so.1.9.0 : Ogre::Root::renderOneFrame()+0x20 [0x7f68b8b41900]
[bt]: (13) /lib64/libOgreMain.so.1.9.0 : Ogre::Root::startRendering()+0x2d [0x7f68b8b4193d]
[bt]: (14) ./opendungeons : ODApplication::ODApplication()+0x64b [0x62d9eb]
[bt]: (15) ./opendungeons : main+0x48 [0x45cc48]
[bt]: (16) /lib64/libc.so.6 : __libc_start_main+0xf0 [0x7f68b501afd0]
[bt]: (17) ./opendungeons() [0x45cd4f]
```

**Comment by Bertram25** [comment]
> I get a segfault when quitting a game with an active event displayed:

Weird, I'll have a look.

**Comment by hwoarangmy** [comment]
I also have the segfault. That's because you delete the messages in the deactivate function but do not clear the vector. Thus, when the mode is deleted, the messages are deleted again in the destructor.

**Comment by Bertram25** [comment]
> I also have the segfault. That's because you delete the messages in the deactivate function but do not clear the vector. Thus, when the mode is deleted, the messages are deleted again in the destructor.

True. I just saw that. I'll fix all that tonight. :)

**Comment by Bertram25** [comment]
Should be good to go now. :)

**Comment by akien-mga** [comment]
Works fine, I merge :)

**Pull request merged**
