### PR TITLE
Resized buttons, its size should be now proportional to the display size

### PR DESCRIPTION
**Pull request by tomluchowski**
As in title resized buttons, maybe worth noting is that their sizes is exactly the percentage of a display not percentage PLUS some constant as it is possible with FALAGARD/CEGUI ...

### CODE REVIEW

**Comment by akien-mga** [comment]
It looks pretty messed up IMO:
screenshot_20190304_092627

That's on 1920x1080.

**Comment by tomluchowski** [comment]
Why ? I asked dozens of times what new outlook should be .... Most of the people said it doesn't mind non-square buttons .... btw write in the console uncheckall or something to get all the rooms. The remove button is a special button that's why I put it in "special " position ....

**Comment by tomluchowski** [comment]
@Bertram25 seems you are the last hope for those three PR's to merge in, care to see and push them ?

**Comment by akien-mga** [comment]
> Why ? I asked dozens of times what new outlook should be .... Most of the people said it doesn't mind non-square buttons .... btw write in the console uncheckall or something to get all the rooms. The remove button is a special button that's why I put it in "special " position ....

Can't you see in my screenshot what's wrong with the current state?

- Action buttons are *huge* compared to the rest of the UI
  * Tab button are still small, tabs themselves are small
  * Minimap buttons are still small, and even get out of the bottom menu due to the change
  * Upper menu buttons are also super small
  * Action buttons overflow their bounding UI panel

I'm not against upscaling buttons, but it needs to be done properly. Everything should be scaled up, while making sure that the GUI elements can adapt to upscaled icons properly. This should also be an option where players can define by what factor they want to scale the UI.

**Review by max-carroll — APPROVED** [review]
Nothing really to approve here, looks ok

**Review by max-carroll — COMMENTED** [review]
oh didnt see others comments

**Pull request merged**
