### PR TITLE
Creature balancing + 3 new spells (Slow, Strength, Weak)

### PR DESCRIPTION
**Pull request by hwoarangmy**

### CODE REVIEW

**Comment by akien-mga** [comment]
I'll test this tonight (_edit:_ tomorrow). We should start thinking about an online game to test all the new stuff in 0.7 :)

**Comment by Danimal696** [comment]
Nice damage triangles, this is starting to get into a serious game

**Comment by akien-mga** [comment]
Testing for real this time, sorry for the delay :)

**Comment by akien-mga** [comment]
There's a size issue with the new icons, they are not square:
icons

_Edit:_ It's of course easily fixed:

```
diff --git a/gui/WindowResearchTree.layout b/gui/WindowResearchTree.layout
index 57e9211..57bf005 100644
--- a/gui/WindowResearchTree.layout
+++ b/gui/WindowResearchTree.layout
@@ -379,7 +379,7 @@
                     </Window>
                 </Window>
                 <Window type="OD/ImageButton" name="CreatureStrengthButton" >
-                    <Property name="Area" value="{{0.7,-25},{0,195},{0.7,25},{0,255}}" />
+                    <Property name="Area" value="{{0.7,-25},{0,195},{0.7,25},{0,245}}" />
                     <Property name="ButtonImage" value="OpenDungeonsIcons/CreatureStrengthButton" />
                     <Property name="TooltipText" value="Spell: Increase creature strength" />
                     <Window type="OD/ProgressBar" name="CreatureStrengthButtonProgressBar" >
@@ -396,7 +396,7 @@
                     </Window>
                 </Window>
                 <Window type="OD/ImageButton" name="CreatureWeakButton" >
-                    <Property name="Area" value="{{0.3,-25},{0,195},{0.3,25},{0,255}}" />
+                    <Property name="Area" value="{{0.3,-25},{0,195},{0.3,25},{0,245}}" />
                     <Property name="ButtonImage" value="OpenDungeonsIcons/CreatureWeakButton" />
                     <Property name="TooltipText" value="Spell: Decrease creature strength" />
                     <Window type="OD/ProgressBar" name="CreatureWeakButtonProgressBar" >
```

**Comment by akien-mga** [comment]
Works fine so far, let's merge.

**Comment by hwoarangmy** [comment]
@akien-mga Will you handle the icon resizing ?

**Comment by akien-mga** [comment]
> @akien-mga Will you handle the icon resizing ?

Yes I have it queued in my fork. I'm also working on a proposal to switch the bottom panels to scrollable panes so that we can keep icons full size instead of having small icons on two lines, I'll soon push it for feedback.

**Pull request merged**
