### PR TITLE
Cegui not found on my system. CEGUIDIR env variable use lacking

### PR DESCRIPTION
**Pull request by hwoarangmy**

### CODE REVIEW

**Comment by Bertram25** [comment]
The PR is simple enough to say that if it is working a linux environment, it can be merged.
I'll test asap, though.

**Comment by akien-mga** [comment]
Working fine, I merge :-)

**Comment by oyvindln** [comment]
Feel free to suggest this upstream

**Comment by oyvindln** [comment]
The scripts already checks CEGUI_DIR, why not use that instead?

**Pull request merged**
