### PR TITLE
Improved worker behaviour

### PR DESCRIPTION
**Pull request by hwoarangmy**
Now, workers won't go all at the same time for each task (claiming workers per tile and digging workers per tile are configurable)

### CODE REVIEW

**Comment by Danimal696** [comment]
another game changing PR, im surprised how much you bring with each one

**Comment by Bertram25** [comment]
Woohoo. I'll test all that tonight, along with the other one.

**Comment by akien-mga** [comment]
> I'll test all that tonight, along with the other one.

I'll try to test it tonight too. Don't hesitate to drop by on the IRC channel if you want to test it (and all previous PRs that we merged without playing them much) directly in a network game with me :)

**Comment by akien-mga** [comment]
@Bertram25 Looks like 0.7.0 will be "OpenDungeons hwoarangmy Edition" :D We need to find stuff to do to keep our names in the changelog hehe.

**Comment by akien-mga** [comment]
I've just gave it a quick test right now, and as I feared there are some issues when you don't have many workers and they don't have so much to do, they tend to enter a state of "walkToTile searchTilesToDig" forever (and stay still without doing anything).

I could reproduce this easily on Stonekeep Siege, by ordering to clear a rectangular area that covers the gold patch to the west of the starting point. First with two workers, one got quickly stuck, then I added a 2nd worker who also got stuck, and finally the third one got stuck too.

stuck

**Comment by akien-mga** [comment]
I also saw one of the workers dive through an undig patch of gold (actually the worker on the bottom on my screenshot, he just went diagonally through the patch at the top and right of him to reach the position he got stuck in.

**Comment by akien-mga** [comment]
Here's a quick replay showing the almost exact same behaviour as above: http://remi.verschelde.fr/files/opendungeons/replay_20151105_082049.odr

_Edit:_ This was with the latest commit btw, i.e. 467d8f2.

**Comment by hwoarangmy** [comment]
> I've just gave it a quick test right now, and as I feared there are some issues when you don't have many workers and they don't have so much to do, they tend to enter a state of "walkToTile searchTilesToDig" forever

Thanks for the tests. I will have a look ASAP

**Comment by akien-mga** [comment]
I confirm that b041e14 fixes all the bugs reported above :)

Let's merge!

**Comment by akien-mga** [comment]
And of course the new worker behaviour is awesome :D

**Comment by Bertram25** [comment]
Oh my, it's Christmas :D

**Pull request merged**
