### PR TITLE
Small fixes : workers claim ennemy room + Cannonns keep shooting + sometimes, ennemy kobold can claim claimed walls

### PR DESCRIPTION
**Pull request by hwoarangmy**
To test this patch, the most simple is to play multiplayer map small free for all (it is the same as multiplayer small but no alliance)
With player 2, try to mark tiles from dungeon 2 to dungeon 1. During kobolds are digging, with player 1, claim the tile in the way. The tile should not be marked anymore in player 2 screen and it should not be possible to mark it.
If you do the same with the multiplayer small 2v2 map, the claimed wall should be left marked and kobolds should dig it.
To test "kobolds can claim ennemy rooms", the most simple is to use the editor to build a room not too far from your dungeon :) Be careful of not doing it too near or your creatures will attack it

### CODE REVIEW

**Comment by hwoarangmy** [comment]
BTW, #165 room part is fixed. The trap part will wait until we decide what we do about them

**Comment by Bertram25** [comment]
Will test asap. The code change looks fine. :)

**Comment by Bertram25** [comment]
I've tested it. Working fine for every points. IMHO, this can be merged. Anyone else wants to test before I do?

**Comment by akien-mga** [comment]
I've tested that marked tiles are effectively unmarked if they are claimed by an enemy.
For the other points I'll rely on your tests, I think you can merge @Bertram25 if the code changes are good.

**Pull request merged**
