### PR TITLE
Basically rewrote the sound manager to handle and fix several features.

### LINKED ISSUE #94: Ramdomizing sounds played on creatures actions.
The same sound is always used, even if we have more than six different ones ready. They should be played at ramdom to have more sound variety.

### PR DESCRIPTION
**Pull request by Bertram25**
- Added random sound playing support for the interface and the creature actions.
- Made the configuration of spatial sounds and the buffer handling done
  per specialized object instead of using multiple shared pointers.
- Also tried better spatial attenuation and min distance values.
- Readd playing claimed tile sounds.

The implementation is still a bit naive in several parts but it's a much better
base for more.

Fixes #94, #52

### CODE REVIEW

**Comment by akien-mga** [comment]
This is _great_! I love the changelog, and even more since it's actually what happens in game :-P
It's quite nice to be able to zoom on some workers and hear them claim tiles, dig or fall dirt with a clear sound. You zoom out again, and you hear some far-away battles...

**Comment by Bertram25** [comment]
> This is great! I love the changelog, and even more since it's actually what happens in game :-P
> It's quite nice to be able to zoom on some workers and hear them claim tiles, dig or fall dirt with a clear sound. You zoom out again, and you hear some far-away battles...

Cool :)

**Comment by hwoarangmy** [comment]
Do you want to go with the commit you were talking about or you will see later ? In any case, I won't test until tonight.

**Comment by Bertram25** [comment]
Np. I will do it but I don't know when, yet. :)

**Comment by hwoarangmy** [comment]
Ok. Then I wait for your commit to test

**Comment by hwoarangmy** [comment]
I've tried the patch, it works fine :)

**Pull request merged**
