### PR TITLE
Workers should not be counted when counting creatures for max + grimoire animation

### PR DESCRIPTION
**Pull request by hwoarangmy**

### CODE REVIEW

**Comment by Bertram25** [comment]
Code looks good. :) I'll test asap.

**Comment by Bertram25** [comment]
Works great, let's merge as it is quite simple.

**Comment by akien-mga** [comment]
The code looks good indeed, and it works fine too.
I just wonder why you increased the max fighting creatures number? (Not that I'm against it, it will all come down to balancing later, but I'd like to know the motivation behind the change ;-)).

**Comment by Bertram25** [comment]
Because the more, the merrier. ;p Let's try this number out, the 15 one was also arbitrary anyway.

**Comment by akien-mga** [comment]
Take cover! There's no more issue assigned to @hwoarangmy for 0.5.0, who knows what devilry he will come up with?! :-D

**Comment by Bertram25** [comment]
Eh eh. Maybe he deserves a bit of fresh air though. Congrats for all the work done @hwoarangmy . I officially owe several coffees :) :coffee: and some other things :cocktail: ;)

**Comment by hwoarangmy** [comment]
> I just wonder why you increased the max fighting creatures number?

Because @Danimal696 has been asking for that for too long ^^

**Comment by hwoarangmy** [comment]
> Eh eh. Maybe he deserves a bit of fresh air though

No, I'm looking at another nicety that I might release soon ^^

**Comment by Bertram25** [comment]
> No, I'm looking at another nicety that I might release soon ^^

Cool! :)

Btw, is it me alone or is the configure seat screen a bit weird? I mean try to start a skirmish, quit the game but not the app, and try restarting another game. The comboboxes values go crazy. Can someone confirm?

**Comment by akien-mga** [comment]
> Btw, is it me alone or is the configure seat screen a bit weird? I mean try to start a skirmish, quit the game but not the app, and try restarting another game. The comboboxes values go crazy. Can someone confirm?

For me it seems to be working fine, at least on the current development branch.

**Comment by Bertram25** [comment]
> For me it seems to be working fine, at least on the current development branch.

Dang it. Could you try that with my PR just in case?

**Comment by akien-mga** [comment]
> Could you try that with my PR just in case?

I tried your PR, but no issue either. Could you be more specific on how the bug looks like?

**Comment by Bertram25** [comment]
Sure, let me open an issue. :)

**Pull request merged**
