### PR TITLE
Reworked console

### PR DESCRIPTION
**Pull request by oyvindln**
Made a new console, this one using CEGUI. The old one was half-finished and rather messy, so I found it easier to rewrite. 
I'm not done with it yet, the console commands haven't been added, but I want to get it merged because its getting tedious to keep the branch up to date due to it containing many changes.

### CODE REVIEW

**Comment by Bertram25** [comment]
> I'm not done with it yet, the console commands haven't been added, but I want to get it merged because its getting tedious to keep the branch up to date due to it containing many changes.

Hi @oyvindln I'll review the code, but first things first, you need to do a good rebase before we can move on with this:
`git pull --rebase git://github.com/OpenDungeons/OpenDungeons.git development`
deal with potential conflicts and:
`git push -f`

**Comment by Bertram25** [comment]
Ok, after reading about the code, I do think that you should squash all your commits into one (after rebasing of course), and there are still commented stuff added in your commits that needs to be sorted out.
Once all that is fixed, I guess we will have a new and shiny console. :)

**Comment by oyvindln** [comment]
I have ran the commands you requested.

**Comment by Bertram25** [comment]
Oops, you pushed on the main repository!!

I'll deal with removing the commits there.
If you didn't clone your fork, do:
`git push -f git@github.com:oyvindln/OpenDungeons.git development`
instead.
This will push to your fork.

**Comment by Bertram25** [comment]
I assumed your cloned your fork. Next time I'll be more cautious, sorry.

**Comment by oyvindln** [comment]
It's done. Didn't notice it was set to push to upstream by default.

**Comment by Bertram25** [comment]
Thanks! Now, do you know how to squash (merge) commits?

**Comment by oyvindln** [comment]
nope

**Comment by Bertram25** [comment]
You will have to wait for me to clean the main repo before the commits appear here, btw. But don't worry, this will be done, soon. In the meanwhile, you can already squash them:

To squash commits, you can use interactive rebasing:
git rebase -i <commit-hash-before-the-first-one-to-squash>
here:
`git rebase -i b90f873101ce35115f2e67fee463b8f1cdd670ca`

An editor will then open (nano, vim, or notepad depending on your OS, ...)
It will show the list of commits after the commit hash given with the word 'pick' in front of each.
Change the word and only that word to 's' for every commits except the oldest, save and close. Every commits with a s will be squashed with the previous.

A new editor will then show the final commit message to display. You can modify as needed, save and close, and voilà, locally it's done.

then, you can do a:
`git push -f git@github.com:oyvindln/OpenDungeons.git development`

To update on remote

**Comment by Bertram25** [comment]
Ok cool :) Now, I bet you have seen there is that material removed by Danimal by mistake in your squashed commits.
If you feel like readding it, commit to your fork and squash, you would have a clean patch.
If you don't, I'll readd it afterwards, or you can readd it in another commit.

Thanks for the work anyway.

**Comment by oyvindln** [comment]
material file is sorted, I will look at removing commented code later, can't really work more today. (Though I don't want to remove all the commented stuff yet, as I want to use it for reference when adding commands to the console.)

**Comment by Bertram25** [comment]
> I will look at removing commented code later, can't really work more today. 

Sure, np. :)
At least, now you know how to refresh your commits, or merge them on need in your fork, so you can push WIP stuff, and resume later.

> (Though I don't want to remove all the commented stuff yet, as I want to use it for reference when adding commands to the console.)

Again, np. Take the time needed to finish all that. I'll happily test afterwards. (and I'm sure the others, too.)

I only had two comments (which were removed from what I saw):
1. I understand the use of emplace_back() but i wonder why you're using unique_ptr() for application modes. What are you trying to achieve with those?
2. Is the modemanager interface class actually needed? I understand the enum separation, but the class looks useless to me. Can you tell me more?

Good evening! :)

**Comment by oyvindln** [comment]
1.
I use unique_ptr because using plain new/delete will result in a memory leak if something in the constructor throws an exception, as the destructor won't be called in that case.
2.
It's for unit testing. The modeManager class depends on a lot of other things, using an interface class makes it easier to unit test without pulling in half the project.

**Comment by Bertram25** [comment]
> It's for unit testing. The modeManager class depends on a lot of other things, using an interface class makes it easier to unit test without pulling in half the project. 

Makes sense as well.

@hwoarangmy @akien-mga I'll remove the commits pushed by mistakes on the main repo.

**Comment by hwoarangmy** [comment]
> I use unique_ptr because using plain new/delete will result in a memory leak if something in the constructor throws an exception, as the destructor won't be called in that case.

Well, that is true for half the project (AFAIK, most exceptions aren't handled - for example in memory allocation). Moreover, an unhandled exception in a mode creation means the application will crash anyway...

**Comment by hwoarangmy** [comment]
I also think we should decide what we want to use modes for. AFAIK, modes are independent (that's pretty clear in the mode manager). That's why I'm not sure it is such a good idea to let the console be a mode as it is pretty obvious that it shall be used at least at the same time as the game mode (and, why not, every other modes).

@oyvindln since you've worked pretty much on console, do you think it would be hard to let it behave as a window rather than a mode ?

**Comment by Bertram25** [comment]
Ok, I've fixed the main repo. :)

**Comment by akien-mga** [comment]
It looks good, though I noticed two things:
- The close button (cross in the top right corner) can be clicked but does not close the console
- It seems no commands are available (yet?) apart from `help`. As we're close to the 0.4.9 release maybe this could be merged in a 0.5 branch?

**Comment by Bertram25** [comment]
Hey :)

> It seems no commands are available (yet?) apart from help. As we're close to the 0.4.9 release maybe this could be merged in a 0.5 branch?

As @oyvindln said a few times already, it is not finished yet. I assume he opened a PR to get feedback, but IMHO, this isn't ready to be on mainline so we shouldn't worry about which branch to use yet.

As for the cross button, I'd propose it to be used as a disable console mode button, what do you think?

**Comment by hwoarangmy** [comment]
> I assume he opened a PR to get feedback

Well, if you re-read his first post, he wants it to be merged to avoid too many conflicts when he will have finished (which I can understand and makes sense). I've not tested it yet so I can't figure what is broken or not.
But I guess in any case, we should at least wait for the 0.4.9 version to be released to merge that.

**Comment by Bertram25** [comment]
> Well, if you re-read his first post, he wants it to be merged to avoid too many conflicts when he will have finished.

Well, he also wanted to merge his code because he was having too much messy merge conflicts. Now he knows how to refresh his commits, I guess this is less urgent for him.

**Comment by hwoarangmy** [comment]
> Well, he also wanted to merge his code because he was having too much mess merge conflicts. Now he knows how to refresh his commits, I guess this is less urgent for him.

Yep, github has some not very intuitive aspects concerning merging.

**Comment by Bertram25** [comment]
@oyvindln Do you want to do another PR once done?

**Comment by oyvindln** [comment]
Probably.

**Pull request closed without merging**
