### PR TITLE
Fixing two small issues

### PR DESCRIPTION
**Pull request by Bertram25**
@hwoarangmy Could you?

It would be your turn for once. ;)

### CODE REVIEW

**Comment by hwoarangmy** [comment]
ok, I will try it tomorrow :)

**Comment by hwoarangmy** [comment]
Is gui/OpenDungeonsIcons.png different from the one I uploaded ?

**Comment by akien-mga** [comment]
> Is gui/OpenDungeonsIcons.png different from the one I uploaded ?

From a quick visual comparison it seems the only difference is the removal of the two obsolete icons (system buttons).

**Comment by akien-mga** [comment]
Builds fine, and the system tab is indeed removed. You can merge :-)

Note that there is (at least) one other missing model in the oldTest.level, I commented on issue #76.

**Comment by Bertram25** [comment]
> From a quick visual comparison it seems the only difference is the removal of the two obsolete icons (system buttons).

Yep, on the image, that's the only difference, but I fixed the cannon icon position in the imageset parameters, too.

**Comment by hwoarangmy** [comment]
> From a quick visual comparison it seems the only difference is the removal of the two obsolete icons

Can't believe I missed that. I should learn to open my eyes

**Comment by Bertram25** [comment]
> Can't believe I missed that. I should learn to open my eyes

Np. Can happen to anybody. :)

@akien-mageia I realize I didn't truly requested your review. My apologize, you're of course free to review any pull request. That goes for anyone without saying. :)
Also, I'm utterly impolite as I didn't even thank you for the review. Thanks!

**Comment by akien-mga** [comment]
> @akien-mageia I realize I didn't truly requested your review. My apologize, you're of course free to review any pull request. That goes for anyone without saying. :)

Well you don't need to explicitly request my review, I'm "watching" the repo so I get an email for every change in an issue or a pull request, and I try to test changes as they come in: it's easier to spot regressions this way.

And I'm not confident enough with the code to spot logical issues, so it's good to have a real developer proofread the changes before merging the pull request :-)

**Pull request merged**
