### PR TITLE
Stonekeep siegue remake and some balancing to cript

### LINKED ISSUE #929: Rework Stonekeep Siege once bridges are implemented
The north dungeon (I guess the "Stonekeep") in Stonekeep Siege is a pre-built based for seat 4 (light blue), but all the claimed tiles and traps seem to belong to seat 0. So the traps actually attack the creatures of seat 4 :)

The rooms seem to belong to seat 4 though.

### PR DESCRIPTION
**Pull request by Danimal696**
I would like your opininons on this one, its a hard level, problably needs more balancing. Dont go north too soon or too late; at first, before digging for the south gold blocks create a full army.
Preparing traps along the way will help at the north battlefield.

I challenge you to play this map without looking at it in the editor. ;D.

Fixes #929

### CODE REVIEW

**Comment by akien-mga** [comment]
27661 added lines... I'm getting curious :D

**Comment by Danimal696** [comment]
its hard but doable

**Comment by Bertram25** [comment]
I'll test asap. :)

**Comment by hwoarangmy** [comment]
I've made a quick tries and seen 2 things so far:
- Since my last PR, torture room and prison need another parameter to launch. You will need to add a new line with "0" at the end of the room definition or the map won't launch. I'm currently building you new binaries so you can try it
- You start the game without portal and you don't know where it is. Moreover, it is pretty far from the dungeon center. That makes the game pretty random as you may be lucky and find the portal or, reach enemies with no portal and, thus, no creature to defend (I was in this case as I found both but it was too late to get creatures before getting raped by tentacles)

**Comment by hwoarangmy** [comment]
The binary is uploaded:
http://download.tuxfamily.org/opendungeons/WIP/OpenDungeons-git20160217-Win32-MSVS2013.zip

**Comment by Danimal696** [comment]
The new exe is not working. It just creates a process of 104 RAM KBs that never launches and cant be killed by normal means.

Regarding this pull can it be merged? i have others pending and would like to have this one out of the way.

**Pull request merged**
