### PR TITLE
Added animated Grimoire for library AND Workshop basic elements

### PR DESCRIPTION
**Pull request by Danimal696**
To replace the podium as a researched item; it has an animation called
"Loop" to be used as a loop

### CODE REVIEW

**Comment by Danimal696** [comment]
Looking good :)
opendungeons 2015-03-14 00-22-29-351

**Comment by Bertram25** [comment]
Woohoo \O/ An icon for the workshop anyone?
http://game-icons.net/lorc/originals/grease-trap.html
http://game-icons.net/lorc/originals/wolf-trap.html
Just tell me what icon suits you and I'll do it. :)

**Comment by akien-mga** [comment]
I'd be more for the wolf-trap one, though it could be confused with an actual trap if you're not aware that you're in the "Rooms" tab ;-)
If we want to go with tools, we can pick from those: http://game-icons.net/tags/tool.html

_Edit:_ Just to clarify, the intended behaviour for the workshop would only be to build the traps? If so the wolf trap icon is probably a good choice :)

**Comment by Bertram25** [comment]
> Edit: Just to clarify, the intended behaviour for the workshop would only be to build the traps? If so the wolf trap icon is probably a good choice :)

Yeah, workshop for traps, library for skills and the next-gen forge for creature equipment.
Maybe we shouldn't use a too trap-ish like icon to show it's a room in any case, as you said.
What about this one for workshops:
http://game-icons.net/lorc/originals/pincers.html
And this one for the next-gen forge?
http://game-icons.net/lorc/originals/sword-smithing.html

The sword makes it clear what it is about.

**Comment by Bertram25** [comment]
@Danimal696 Btw, congrats! You're now using git like a real dev. :)

**Comment by Danimal696** [comment]
> @Danimal696 Btw, congrats! You're now using git like a real dev. :)

Thanks, and i just nearly broke the project twice ;-)

**Comment by hwoarangmy** [comment]
The models look good ^^

> And this one for the next-gen forge?

Seems pretty clear

> What about this one for workshops:

If the workshop is only for traps, the wolf trap is better IMO. Even if it looks like a trap, the fact that it will be in the room tab next to the other rooms make it pretty clear it is not a trap.

**Comment by Bertram25** [comment]
> If the workshop is only for traps, the wolf trap is better IMO. Even if it looks like a trap, the fact that it will be in the room tab next to the other rooms make it pretty clear it is not a trap.

Ok, I'll work on both icons asap. :) (Research GUI is being added atm. ;])

**Comment by akien-mga** [comment]
For once I'll take @Bertram25's role: @Danimal696, could you also update the CREDITS file? ;-)

**Comment by Danimal696** [comment]
-_- i hate you all

**Comment by Bertram25** [comment]
> For once I'll take @Bertram25's role: @Danimal696, could you also update the CREDITS file? ;-)

eh eh. :D

**Comment by Bertram25** [comment]
> -_- i hate you all

Nothing personal :gun: :wink:

**Comment by Bertram25** [comment]
@Danimal696 If you give me pointers and URL on the licensing info, I can do it if you want.

**Comment by Bertram25** [comment]
Looks fine enough. I'll take care of the rest as I'll have to review the license file before release.. Thanks for the effort on this @Danimal696 . Licensing can't be taken lightly anyway. If just as a matter of respect for your own work. :)

**Comment by Bertram25** [comment]
@hwoarangmy @akien-mga If the PR is fine for you guys, you can merge it. I'll add the icon in my PR tonight. ;)

**Comment by hwoarangmy** [comment]
fine

**Pull request merged**
