### PR TITLE
Dungeon Biome tileset Upgrade

### PR DESCRIPTION
**Pull request by Danimal696**
First iteration, it looks weird at first but its already better than the
last one. I would like your opinions

### CODE REVIEW

**Comment by Danimal696** [comment]
Sneak peak:
opendungeons 2015-06-15 16-21-00-679
opendungeons 2015-06-15 16-22-53-120

**Comment by hwoarangmy** [comment]
Testing

**Comment by hwoarangmy** [comment]
Works well

**Comment by Danimal696** [comment]
> You used a tab here. As I know you don't like handling that, I will fix that when the PR is merged if you want.

Thanks, i used scilla, ill use notepad next time, what do you think of it anyways?

**Comment by hwoarangmy** [comment]
I think the new claimed walls are pretty nice. That's better than the single texture on all sides ^^

**Comment by Bertram25** [comment]
Woohoo :D

**Pull request merged**
