### PR TITLE
Resized textures

### PR DESCRIPTION
**Pull request by Danimal696**

### CODE REVIEW

**Comment by hwoarangmy** [comment]
Is it normal that WallClaimed is not there ?

**Comment by Danimal696** [comment]
i closed that pull,let me try later with the updated version if not ill reupload the big file

**Comment by Bertram25** [comment]
@Danimal696 What is the status of your work here?

**Comment by Danimal696** [comment]
it depends on the multitexture, if i get no result ill try another simpler approach

**Comment by Danimal696** [comment]
Im reuploading everything

**Pull request closed without merging**
