### PR TITLE
Add support for hatchery

### LINKED ISSUE #61: Add a basic hatchery room
Using the models given by @Danimal696 , add support for the hatchery model.
http://forum.freegamedev.net/viewtopic.php?p=58160#p58160

The hunger system and chicken handling are other issues.

### PR DESCRIPTION
**Pull request by hwoarangmy**
fixes #61

### CODE REVIEW

**Comment by hwoarangmy** [comment]
@Bertram25 Sorry, another pull request with more than 20 files :(

**Comment by Bertram25** [comment]
I'll test live in a few hours.

**Comment by Bertram25** [comment]
Btw, you also added support for hunger and animated chicken and eating. It's awesome! :)
This one also fixes #13 and the first half of #8

**Comment by hwoarangmy** [comment]
> Btw, you also added support for hunger

Yes but currently, it does nothing :)
Maybe we could increase hunger when the creatures do something (I did nothing during training because it was too close from sleeping and I didn't want to do exacly the same).

**Comment by Bertram25** [comment]
> Yes but currently, it does nothing :)
> Maybe we could increase hunger when the creatures do something (I did nothing during training because it was too close from sleeping and I didn't want to do exacly the same).

At least, it bothers the creature from time to time. It's a start. :)

**Comment by Bertram25** [comment]
I've tested it in game and it's awesome. :) 
I've played the big single player map and I was able to finish my game with an hatchery, a dormitory, and training room all three functional and alive! :D 

No segfault, no weird log output or faulty assert.
I'lll merge now. This is great step ahead. Thanks @hwoarangmy :)

**Comment by akien-mga** [comment]
Chickens! :-D

**Comment by akien-mga** [comment]
This button looks rad and the new hatchery seems functional, I did not spot obvious regressions. Great job :-D

**Pull request merged**
