### PR TITLE
Normalized sounds and made them mono.

### LINKED ISSUE #885: Sounds - Normalize, monoify the new sounds, use ogg, and maybe a few other tricks
This is a blocker for 0.6, after: https://github.com/OpenDungeons/OpenDungeons/pull/876

Related to #126

### PR DESCRIPTION
**Pull request by Bertram25**
I also modified the die sounds to fit either fighters or keeper workers.

This is fixing the issue with sounds being too loud.

On the other hand, music can now be too loud compared to sfx, and settings
between sounds and music volume should IMHO be separated.

Fixes #885

### CODE REVIEW

**Comment by Bertram25** [comment]
On a side-note, I don't have the bug of sound glitches anymore when using SFML 2.3 on Linux. :)

**Comment by akien-mga** [comment]
> On a side-note, I don't have the bug of sound glitches anymore when using SFML 2.3 on Linux. :)

Nice, I'll try SFML 2.3 to see then :)

**Comment by akien-mga** [comment]
> Nice, I'll try SFML 2.3 to see then :)

Actually I'll test 2.3.1, I just notice it has been released ;)

**Comment by akien-mga** [comment]
It works great, and I confirm that the sound glitches seem to disappear when using SFML 2.3.x :)
I'll use it for my Linux binaries then.

**Pull request merged**
