### PR TITLE
Dropped pthreads

### PR DESCRIPTION
**Pull request by oyvindln**
Removed the last references to pthreads. It was basically already out of use, unless one was using some custom-built ogre without thread support. Needs testing on windows.

### CODE REVIEW

**Comment by Bertram25** [comment]
Working fine on Linux for me. I'll let @hwoarangmy handle the windows side of things. ;)

**Comment by hwoarangmy** [comment]
Cool, no more pthread ^^
I will try with MinGW and, since this can break things, with MSVS too.

**Comment by hwoarangmy** [comment]
It is ok with MinGW and MSVS. @oyvindln do you want to remove the ws2_32 in this PR or in a later one ?

**Comment by Bertram25** [comment]
It's cool to see we're only using a few sf::Thread() now. :D

**Comment by oyvindln** [comment]
I'll remove winsock in this PR.

**Comment by Bertram25** [comment]
@oyvindln You will want to crush me but I'll do my @akien-mga ;) : 
There are a few boost threads/pthreads reference left AFAIK:
https://github.com/OpenDungeons/OpenDungeons/blob/development/FAQ.txt#L323
https://github.com/OpenDungeons/OpenDungeons/blob/development/FAQ.txt#L329
https://github.com/OpenDungeons/OpenDungeons/blob/development/README#L32
https://github.com/OpenDungeons/OpenDungeons/blob/development/README#L63
Care to remove them? (If not, I'll do it later.)

**Comment by oyvindln** [comment]
Not sure if I can get much done today, so it's probably better that you do it later.

**Comment by hwoarangmy** [comment]
That's what I tested yesterday so it shall bo ok for MinGW and MSVS. Since the last commit only concerns windows and that @Bertram25 already tested with Linux, I think it can be merged.
I will open an issue for the remaining thread/pthread references.

**Comment by Bertram25** [comment]
Sure I'll handle the remaining refs if nobody else does it before me. :)

**Pull request merged**
