### PR TITLE
Add support for team games

### LINKED ISSUE #145: Add support for team game

### PR DESCRIPTION
**Pull request by hwoarangmy**
fixes #145

### CODE REVIEW

**Comment by hwoarangmy** [comment]
@Bertram25 @akien-mga 
Here is the multiplayer support. To test it, I've added teams in level test small (both skirmish and multiplayer). In the skirmish one, you will see 3 tiles claimed by you, your ally and an ennemy. Your kobolds should claim the ennemy one but not yours nor your ally's.
You shoukd also be able to drop workers or fighters in your ally dungeon (top left) and to claim tiles next to his.

**Comment by hwoarangmy** [comment]
I've just seen that there was no test when absorbing room about ownership. That means you could absorb an ennemy or allied room :)
Gonna fix it right now

**Comment by hwoarangmy** [comment]
Just saw that it's the same for using rooms. If you manage to get a creature on an ennemy room, it will use it :)

**Comment by Bertram25** [comment]
Nice work :)

The cleanup on seat use alone is worth it, IMHO.

I'd rename a few members which were quite badly named from the start as told inline, but this is not your fault. I'll test live now.

**Comment by hwoarangmy** [comment]
ok. If something is found before merging, I will change variables names. If not, I will do that in some next pull request.

**Comment by Bertram25** [comment]
I'm testing. So far, it's working good. :)

**Comment by Bertram25** [comment]
Well, so far, I've beaten several matches, both with team and alone, and it seems to work good.

No creature, traps or rooms were deceiving in term of team/seat id handling. I do think it's mergeable but I will let @akien-mga test a bit though unless he tells otherwise.

**Comment by akien-mga** [comment]
I'll do a quick test now.

**Comment by akien-mga** [comment]
Both with skirmish and multiplayer mode, I get "Error: Couldn't connect to local server!" when trying to start a game. I'll try again with a clean build environment, for this one I built the pull request on top of my previous build of the hwoarangmy/development branch, maybe some files were omitted that should have been rebuilt.

**Comment by akien-mga** [comment]
Same with a new build. I get the following in the terminal:

> Server connected and listening
> ERROR : Could not connect to distant server status=3
> ERROR: Could not connect to server for single player game !!!

It seems to be a problem on my end actually, because an old build of @Bertram25's development branch produces the same error. It's probably related to a shared library: since I'm using the development version of Mageia, so basically I'm installing new cores packages regularly, some of which might have an influence in connecting to the server. Do you have an idea about which components might cause such as issue so that I look into it?

**Comment by akien-mga** [comment]
@Bertram25: You may merge this one if you want, my issue is not related to the pull request.

**Comment by Bertram25** [comment]
> @Bertram25: You may merge this one if you want, my issue is not related to the pull request.

Ok, I will. But I guess you didn't try it yet, right?

**Comment by Bertram25** [comment]
> Server connected and listening
> ERROR : Could not connect to distant server status=3
> ERROR: Could not connect to server for single player game !!!

Btw, the error you have is triggered here:
https://github.com/OpenDungeons/OpenDungeons/blob/development/source/ODSocketClient.cpp#L33

The status= 3 means SFML encountered an unknown error:
http://sfml-dev.org/documentation/2.1-fr/classsf_1_1Socket.php#a51bf0fd51057b98a10fbb866246176dc

After a fresh reboot, could you try to see if you can ping your local loop, for instance. See your routes, check whether the port 31222 isn't already taken by another service, check your MTU size, ...

... Maybe the error is there somewhere.

Without more info, I can't unfortunately really help you. :S

**Comment by akien-mga** [comment]
Thanks for the info, I'll look into it in the evening. Maybe something took the port 31222 yes; I'll look at my RPM packages that go updated lately, this might point us in the right direction (I know that I switched from kernel 3.17.0 RC4 to RC5, but that shouldn't impact much IMO).

**Comment by hwoarangmy** [comment]
It should not be because the port is in use. If it was the case, it would be the server that would complain, not the client. I'm sorry but I have no clue about what is going on...

**Comment by Bertram25** [comment]
> If it was the case, it would be the server that would complain, not the client.

I see your point, but I already encountered weird things in that regards (two services trying to steal a port to each others with timeouts), so I won't have an opinion about this. :S

**Comment by akien-mga** [comment]
It seems OD correctly uses port 31222/tcp, when I attempt to start a game, it shows up as the process using it. So the server seems to start properly, but then I can't join it.

**Comment by akien-mga** [comment]
I've noticed that I manage to join a game on one out of 20 attempts or something. There's definitely something wrong on my end :-)

**Pull request merged**
