### PR TITLE
Levels cleanup + put doors in model's fair test level

### PR DESCRIPTION
**Pull request by akien-mga**

### CODE REVIEW

**Comment by Danimal696** [comment]
neither i do, its from someone from the original team

**Comment by Bertram25** [comment]
> Let's attribute it to OD Team then. Personally I would be in favour of attributing credits for all our levels to OD Team directly, and maybe just specify a contributor name for external community contributions that we might want to upstream.

Sounds sane. Do you agree everyone?

**Comment by Danimal696** [comment]
"OD Team", yes, best option for any core level we do, i dont think we are that hungry for credit on everything we do

**Comment by Bertram25** [comment]
It's mergeable and working, so I'll merge it too. Let's fix the credits part afterwards.

**Pull request merged**
