### PR TITLE
Small misc fixes.

### PR DESCRIPTION
**Pull request by Bertram25**

### CODE REVIEW

**Comment by hwoarangmy** [comment]
I will test tonight but it seems pretty straight forward

**Comment by akien-mga** [comment]
You'll need to rebase this one @Bertram25.

**Comment by Bertram25** [comment]
> You'll need to rebase this one @Bertram25.

Sure. :)

**Comment by Bertram25** [comment]
Rebased + Added the wooden door to the new available traps events. :)

**Comment by hwoarangmy** [comment]
seems good, and straight forward enough to not need too much testing ^^

**Comment by akien-mga** [comment]
Nice set of fixes :)

**Pull request merged**
