### PR TITLE
Make portals claimable + max creature number increases with portals + small fixes

### PR DESCRIPTION
**Pull request by hwoarangmy**
To test, the skirmish small test map (2v2 and empty) now start for seat 1 with 1 rogue portal that needs to be claimed. Note that the max creature number should increase when the portal is claimed (5 in 2v2 map and 10 in empty map).
I've not tested with 2 portals but it should work ^^

### CODE REVIEW

**Comment by Bertram25** [comment]
I've got a few questions but overall it's worth being integrated. :) I'll test asap.

**Comment by Bertram25** [comment]
Code looks good. Once it's tested, let's merge. :)

**Comment by akien-mga** [comment]
It works great :) I've confirmed that you can even get your portal claimed by your ally if you prevent your own worker from claiming it. The AI does not focus on claiming portals for now though, so if you leave them be your worker will claim it first - and anyway that's not an issue because the setting that we have in the 2v2 map is only for testing :)

**Comment by akien-mga** [comment]
Good to merge as far as I'm concerned :)

**Comment by akien-mga** [comment]
Four pull requests at once! We're only missing @Bertram25's ;-)

Code has been reviewed and I tested it live, so I'll merge this one.

**Pull request merged**
