### PR TITLE
Use entity tile to pickup creatures instead of using a ray + minor fixes + added logs

### PR DESCRIPTION
**Pull request by hwoarangmy**
Note that if several units are on the same tile, you can choose one or the other by moving the mouse (if you let the mouse on the right part of the tile, you will select the creature on the right).

### CODE REVIEW

**Comment by akien-mga** [comment]
@hwoarangmy There's a typo which makes compilation fail on Unix (it should be "Pathfinding"):

```
/home/akien/Projects/opendungeons/OpenDungeons/source/modes/EditorMode.cpp:25:33: fatal error: gamemap/PathFinding.h: No such file or directory
 #include "gamemap/PathFinding.h"
                                 ^
```

It also needs to be fixed in source/modes/GameMode.cpp

**Comment by akien-mga** [comment]
Afterwards I get another build issue with gcc:

```
/home/akien/Projects/opendungeons/OpenDungeons/source/spells/SpellCreatureExplosion.cpp: In static member function 'static bool SpellCreatureExplosion::castSpell(GameMap*, Player*, ODPacket&)':
/home/akien/Projects/opendungeons/OpenDungeons/source/spells/SpellCreatureExplosion.cpp:173:103: error: no matching function for call to 'min(uint32_t, std::vector<Creature*>::size_type)'
     uint32_t nbTargets = std::min(static_cast<uint32_t>(playerMana / pricePerTarget), creatures.size());
                                                                                                       ^
```

I guess creatures.size() needs a static_cast too?

**Comment by akien-mga** [comment]
This patch fixes the build issues for me:

```
diff --git a/source/modes/EditorMode.cpp b/source/modes/EditorMode.cpp
index ef3ae1e..fd7071c 100644
--- a/source/modes/EditorMode.cpp
+++ b/source/modes/EditorMode.cpp
@@ -22,7 +22,7 @@
 #include "gamemap/GameMap.h"
 #include "gamemap/MiniMap.h"
 #include "gamemap/MapLoader.h"
-#include "gamemap/PathFinding.h"
+#include "gamemap/Pathfinding.h"
 #include "render/ODFrameListener.h"
 #include "render/Gui.h"
 #include "render/TextRenderer.h"
diff --git a/source/modes/GameMode.cpp b/source/modes/GameMode.cpp
index d4235f4..5d14ed3 100644
--- a/source/modes/GameMode.cpp
+++ b/source/modes/GameMode.cpp
@@ -29,7 +29,7 @@
 #include "game/Research.h"
 #include "game/Seat.h"
 #include "gamemap/GameMap.h"
-#include "gamemap/PathFinding.h"
+#include "gamemap/Pathfinding.h"
 #include "render/Gui.h"
 #include "render/ODFrameListener.h"
 #include "render/RenderManager.h"
diff --git a/source/spells/SpellCreatureExplosion.cpp b/source/spells/SpellCreatureExplosion.cpp
index 1b2f804..086fcbb 100644
--- a/source/spells/SpellCreatureExplosion.cpp
+++ b/source/spells/SpellCreatureExplosion.cpp
@@ -170,7 +170,7 @@ bool SpellCreatureExplosion::castSpell(GameMap* gameMap, Player* player, ODPacke

     int32_t pricePerTarget = ConfigManager::getSingleton().getSpellConfigInt32("CreatureExplosionPrice");
     int32_t playerMana = static_cast<int32_t>(player->getSeat()->getMana());
-    uint32_t nbTargets = std::min(static_cast<uint32_t>(playerMana / pricePerTarget), creatures.size());
+    uint32_t nbTargets = std::min(static_cast<uint32_t>(playerMana / pricePerTarget), static_cast<uint32_t>(creatures.size()));
     int32_t priceTotal = nbTargets * pricePerTarget;

     if(creatures.size() > nbTargets)
diff --git a/source/spells/SpellCreatureHeal.cpp b/source/spells/SpellCreatureHeal.cpp
index d83555b..e08e31a 100644
--- a/source/spells/SpellCreatureHeal.cpp
+++ b/source/spells/SpellCreatureHeal.cpp
@@ -170,7 +170,7 @@ bool SpellCreatureHeal::castSpell(GameMap* gameMap, Player* player, ODPacket& pa

     int32_t pricePerTarget = ConfigManager::getSingleton().getSpellConfigInt32("CreatureHealPrice");
     int32_t playerMana = static_cast<int32_t>(player->getSeat()->getMana());
-    uint32_t nbTargets = std::min(static_cast<uint32_t>(playerMana / pricePerTarget), creatures.size());
+    uint32_t nbTargets = std::min(static_cast<uint32_t>(playerMana / pricePerTarget), static_cast<uint32_t>(creatures.size()));
     int32_t priceTotal = nbTargets * pricePerTarget;

     if(creatures.size() > nbTargets)
```

**Comment by akien-mga** [comment]
I've tested the PR (and particularly the new entity pickup), and it works fine :)

The tile-based entity pickup works very well in top-down view.

In the default (tilted) and isometric views, it's a bit trickier, since to select a creature you have to make sure to select the tile the creature is on, and the perspective does not make it easy. But that's a general problem of our tile selector IMO, so I'd in favour of using this tile-based pickup behaviour, but to try to improve the tile selector behaviour further.

In the tilted view, the region of the display that corresponds to a given tile is far from being obvious (it's the region which corresponds to the top of the tile selector):
od-tileselector

With the isometric view, it's even trickier. Basically, by hovering over a given tile with the mouse pointer, you can select up to 4 different tiles.
od-tileselector2

That's for another issue of course, just dropping some thoughts here :)

**Comment by akien-mga** [comment]
About the tile selector, I wonder: wouldn't we make our life much easier if we had a smaller selector? i.e. not as high as wall tiles, but maybe just 20% of the current height, with a nice particle effect that highlights the tile? :) Of course the selector would have to be higher when selecting full tiles, so it should probably be something that shows a visible selector or particle effect 0.2*tile_height above the selected tile.

**Comment by hwoarangmy** [comment]
> In the default (tilted) and isometric views, it's a bit trickier, since to select a creature you have to make sure to select the tile the creature is on

IIRC, that's the same as in DK. The trick is to aim on the top of the tile selector what we want to target.

**Comment by akien-mga** [comment]
The PR is good to merge for me, I'll let @Bertram25 do his usual code review :)

**Comment by Bertram25** [comment]
The changes are IMHO good. I like the new way to pick a creature. In fact, as the skull flag appears when you're actually hovering the creature, it looks like clicking on the flag to pick the creature and IMO it's better once you get it. I'll merge.

**Pull request merged**
