### PR TITLE
Improved the way creatures see and seek claimable and diggable tiles.

### PR DESCRIPTION
**Pull request by Bertram25**
This fixed the small pathfinding glitches for me and improves already a lot the efficiency of workers. :)

### CODE REVIEW

**Comment by akien-mga** [comment]
I'm getting a linking issue with your PR, though I can't find a reason why:

```
Linking CXX executable opendungeons
/usr/bin/ld: libangelscript.a(as_thread.cpp.o): undefined reference to symbol 'pthread_rwlock_wrlock@@GLIBC_2.2.5'
/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/opendungeons.dir/build.make:2642: recipe for target 'opendungeons' failed
make[2]: *** [opendungeons] Error 1
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/opendungeons.dir/all' failed
make[1]: *** [CMakeFiles/opendungeons.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2
```

I've tried to build again @oyvindln's branch, and it works fine. Will try to build development.

**Comment by oyvindln** [comment]
Hm, sounds like angelscript may require linking with the thread libraries.

**Comment by Bertram25** [comment]
> Hm, sounds like angelscript may require linking with the thread libraries.

Then, why on the same machine, your branch is fine while mine isn't? I thought both our branches had the AS update and pthread removal?

**Comment by akien-mga** [comment]
Same issue in OpenDungeons/development

**Comment by Bertram25** [comment]
@akien-mga Sorry for the question but can you clear both your cmake cache and CMakeFiles/ temp folder and try again? (Or maybe you already did it?)

**Comment by akien-mga** [comment]
I did it for @Bertram25's branch and for OpenDungeons/development. I don't remember for @oyvindln's, I'll try.

**Comment by akien-mga** [comment]
Ah it seems I wasn't fully up-to-date on @oyvindln's branch, so one of the his later commits might explain the issue.

**Comment by akien-mga** [comment]
Maybe this? https://github.com/OpenDungeons/OpenDungeons/commit/be5a2db3a086566cc76a07af09f4f5eac06878d4#diff-af3b638bc2a3e6c650974192a53c7291L475

**Comment by Bertram25** [comment]
Taken from the CMakeLists.txt from the library latest version download, those lines clearly shows a need for thread:

``` cmake
find_package(Threads)
target_link_libraries(Angelscript ${CMAKE_THREAD_LIBS_INIT})
```

Maybe we can use boost::thread instead of pthread?

**Comment by Bertram25** [comment]
Update:
http://stackoverflow.com/questions/5395309/cmake-and-threads
I wonder whether liangelscript.a would compile if we force the cmake module not to search for pthread and invoke the find_package statement, such as:

``` cmake
set(CMAKE_THREAD_PREFER_PTHREAD FALSE)
find_package(Threads REQUIRED)
target_link_libraries (${AS_LIBRARY_NAME} ${CMAKE_THREAD_LIBS_INIT})
```

Maybe boost must have to readded in that case?

**Comment by oyvindln** [comment]
Well we could just readd linking to pthreads on linux.

**Comment by Bertram25** [comment]
@oyvindln Well, true. I just wondered whether we could still get rid of it.
Btw, the same issue will probably arise on windows, right?
I guess pthreads should be reinstated in that case.
@hwoarangmy Can you tell us whether AS still compile fine for you on development?

**Comment by oyvindln** [comment]
It won't be an issue on windows, it's not used by anything on windows any more.

**Comment by Bertram25** [comment]
@oyvindln ? Then, there is something I don't get. Angel Script is requiring threads on linux but not on windows?

**Comment by oyvindln** [comment]
It uses the native thread libraries on each system, pthreads is the native thread library on linux, but not on windows. The extra library we used was just an implementation of pthreads on top of the windows thread libraries.

**Comment by Bertram25** [comment]
> It uses the native thread libraries on each system, pthreads is the native thread library on linux, but not on windows. The extra library we used was just an implementation of pthreads on top of the windows thread libraries. 

Ah of course, silly me, pthreads mean posix threads. It makes sense now. Thanks for helping an old fool lurking in the middle of his own-made desert. XD
(I don't know why, I was truely thinking pthreads were some custom made thread library, without remembering about the posix ones.)
Then, the issue is about simply readding a few lines in the CMakeLists.txt file.

@akien-mga Could you try readding those lines (where relevant) and test?

``` cmake
set(CMAKE_THREAD_PREFER_PTHREAD TRUE)
find_package(Threads REQUIRED)
target_link_libraries (${AS_LIBRARY_NAME} ${CMAKE_THREAD_LIBS_INIT})
```

**Comment by akien-mga** [comment]
@Bertram25 Adding you code snippet fixes the issue. I'll let you see where it is most relevant to add it, and maybe if it should be UNIX-only (I guess the find_package(Threads REQUIRED) might be relevant for Windows too, but I wonder about the CMAKE_THREAD_PREFER_PTHREAD.

**Comment by oyvindln** [comment]
CMAKE_THREAD_PREFER_PTHREAD is at least not relevant on windows. Not sure if it should be used on linux either.

**Comment by Bertram25** [comment]
@akien-mga If checking for the existence of thread support is also relevant for windows. Then, indeed we shouldn't make cmake prefer pthreads in that case.

**Comment by Bertram25** [comment]
@ everyone: I'm making a patch. If both you and @hwoarangmy tell me it is fixing the issue (or at least not breakig anything), then we'll be out of trouble. :)

**Comment by oyvindln** [comment]
CMAKE_THREAD_PREFER_PTHREAD seems to be only relevant on IRIX and HP-UX, so I don't think it's needed.

**Comment by Bertram25** [comment]
Ok, I've added the change. @oyvindln Thanks for bearing with my sometimes surprising stupidity. ;)

**Comment by oyvindln** [comment]
@Bertram25 No problem

**Comment by hwoarangmy** [comment]
I will try that tonight

**Comment by hwoarangmy** [comment]
I've tested the PR with MinGW (before the last commit) and it works (I could launch a level successfully).

**Comment by hwoarangmy** [comment]
The crash problem I was talking about happens when the plugin.cfg file is not good (or the renderer is missing). That should not happen that often and is much less important than cancelling ogre window.
I merge

**Comment by Bertram25** [comment]
I may handle it the next pr if you want. That won't be difficult to add. :)

**Pull request merged**
