### PR TITLE
Add support to sell rooms/traps + chicken spawn problem

### LINKED ISSUE #108: Add support to destroy a room using a new button.
Destroying a room gives back half the tile price.

The icon is ready (The wrecking ball)
Should we add this to 0.4.9 or later?

### LINKED ISSUE #215: Chickens spawn at tile 0,0
They spawn at tile 0,0 and then walk to their hatchery. That's pretty weird :)

### PR DESCRIPTION
**Pull request by hwoarangmy**
fixes #108 
fixes #215 

You can achieve weird things when selling a hatchery. Do not bother to much with it, I'm planning on doing something about it soon :)

### CODE REVIEW

**Comment by akien-mga** [comment]
Testing, it works quite fine :-)

I have a problem though that would probably be related to the previous pull request: the behaviour of the creature grab is erratic, I'm having a hard time grabbing kobolds for example. I haven't understood yet in which cases it works and in which cases it doesn't, but something is wrong :-)

As for the room selling, it brings a bunch of bugs, but that is to be expected. For example if you sell the treasure tile had some gold at first (and which is probably considered the "First treasury tile", then you can't collect gold anymore (even if your dungeon heart is paved with treasure tiles): you have to place a new "first" treasury tile for 0 gold.

**Comment by hwoarangmy** [comment]
when it will be possible to drop objects on map, destroyed treasury tiles will drop gold on the ground. But for now, it is just lost :)

> I'm having a hard time grabbing kobolds for example

It happened once to me also. I wasn't sure if I was doing something wrong or not but it seems it is a real bug. Maybe someone will see how to reproduce. But this bug might be introduced by this PR as I've changed stuff within GameMode. I will try to test a little bit more.

**Comment by hwoarangmy** [comment]
I confirm it is a bug from this PR. I'm gonna have a look and add fix it

**Comment by hwoarangmy** [comment]
It is fixed :)

**Comment by akien-mga** [comment]
Fix confirmed :-)

**Comment by Bertram25** [comment]
Fix confirmed to me as well. I'm merging.

**Pull request merged**
