### PR TITLE
Turn warnings on + active spots + renaming camera manager in ODFrameListener

### PR DESCRIPTION
**Pull request by hwoarangmy**
Same as #179 but after a rebase to avoid too many conflicts

### CODE REVIEW

**Comment by Bertram25** [comment]
Nice work! Tested it and it's working fine!
With you it makes 5 issues killed in a row tonight. :D 
I'll wait for @akien-mga and we'll merge afterwards if nothing else is found.

**Comment by Bertram25** [comment]
@hwoarangmy  Seems one can't merge automatically this one. Can you rebase?

@akien-mga Do you want to test this one?

**Comment by hwoarangmy** [comment]
Yes, seems like both our PR are not mergeable anymore. I hope I will do better than last time I tried a merge ^^

**Comment by Bertram25** [comment]
No worries. :)

But I'll let @oyvindln show his change about dirent.h removal first. It can only simplify things for later.

**Comment by Bertram25** [comment]
@hwoarangmy Sill want to make this mergeable?

**Comment by hwoarangmy** [comment]
I'm trying to merge but I cannot find a way where I do not overwrite all the commits ahead of my fork. I've seen you have resolved your conflicts. Can you please tell me the commands to resolve ? Otherwise, I will drop again my fork and redo my PR.

**Comment by Bertram25** [comment]
usually, I do a `git pull --base git://github.com/OpenDungeons/OpenDungeons.git development`
I resolve the conflicts is there are ones. While dealing with conflicts, do a `git status` and git will tell you which command to type once conflicts are resolved.
Once I'm done, my commit to PR are on tip of history and I `git push -f` to force update the branch remotely.

I hope this will help you. :)

**Comment by hwoarangmy** [comment]
ok, All my commits have been re-done but at least, it is mergeable again :)

**Comment by Bertram25** [comment]
Let's merge then. :)

**Pull request merged**
