### PR TITLE
Add buttons to handle researches + improved game entity architecture + small fixes

### PR DESCRIPTION
**Pull request by hwoarangmy**

### CODE REVIEW

**Comment by akien-mga** [comment]
Pretty good stuff :-) Apart from our good old "spacial" typo, this is good to merge IMO. I'll let @Bertram25 do a more thorough code review.

**Comment by Bertram25** [comment]
Pretty good addition. The code is good and special kudos for the clean commits done. Review was a breeze. I'll test now.

**Comment by Bertram25** [comment]
The Apply button in the Research tree is above the window border.

**Comment by Bertram25** [comment]
The new sounds are either not normalized or not mono, making them be played too loud AFAIH.
The battle music restarts when multiple allies are attacked. It should simply keep playing in that case.

**Comment by Bertram25** [comment]
@akien-mga Is Ruins of the Confluent winnable? It seems I cannot defeat the yellows as I can't reach the Wave portal. ?

**Comment by hwoarangmy** [comment]
> The Apply button in the Research tree is above the window border.

Depends on the resolution I guess. For me, it is well displayed. Could you please post a snapshot?

> The new sounds are either not normalized or not mono

I've just converted them to ogg for testing purpose. Now, it is @Danimal696 duty to find sounds ^^

> The battle music restarts when multiple allies are attacked. It should simply keep playing in that case.

I don't remember changing anything about this. Is it different than it was ?

**Comment by Bertram25** [comment]
> Depends on the resolution I guess. For me, it is well displayed. Could you please post a snapshot?

1366x789. I can fix it after the merge, though. :)
odscreenshot_2015-07-24_004314_0

> I've just converted them to ogg for testing purpose. Now, it is @Danimal696 duty to find sounds ^^

Yeah :D I'll modify a few sounds to make them more fun whenever I'll get the time to. :)

> I don't remember changing anything about this. Is it different than it was ?

IMHO yes. I clearly remember testing that point when implementing, but it might have come in another commit. I haven't tried a map with multiple allies for a while after all. In any case, it can be a new issue.

**Comment by Bertram25** [comment]
Gentlemen, this is clearly starting to look like a full game. :D

**Comment by hwoarangmy** [comment]
> 1366x789. I can fix it after the merge, though. :)

I tested again and indeed, I have the same. I should open my eyes when I test ^^
However, I'm currently trying to setup a MinGW-64 env so I cannot really do any dev. So please merge if there is nothing else and open an issue.

**Comment by Bertram25** [comment]
> I tested again and indeed, I have the same. I should open my eyes when I test ^^
> However, I'm currently trying to setup a MinGW-64 env so I cannot really do any dev. So please merge if there is nothing else and open an issue.

Np at all. :) It can happen. I'll make a PR to fix that.

Would you mind if I have a look at the current sounds format and normalization something like tonight?

**Comment by hwoarangmy** [comment]
> Would you mind if I have a look at the current sounds format and normalization something like tonight?

Of course not ! I don't really like to mess with it anyway. BTW, if you want, I can take something on your shoulders as I'm not planning on adding new functionalities before the next release.

**Comment by Bertram25** [comment]
> Of course not ! I don't really like to mess with it anyway. BTW, if you want, I can take something on your shoulders as I'm not planning on adding new functionalities before the next release.

Deal! It's not that I'm lazy (I promise) but well, you know how RL can be :S Take whatever you want from me if you feel like doing it. Maybe it's time I assign one issue at a time to actually show what I'm doing instead of dragging stuff for too long.
I'll unassign stuff from me tonight but I'll work on UI and sounds as discussed.

**Comment by Bertram25** [comment]
Btw, there are not much issues left before release, announcement and discussed small fix apart. :D 
The biggest thing left to do is to have a few lan to ~~enjoy~~ work dutifully on analysing the remaining flaws.

**Comment by akien-mga** [comment]
> Is Ruins of the Confluent winnable? It seems I cannot defeat the yellows as I can't reach the Wave portal. ?

That's a good question. To be honest I never played it more than 10 minutes ;-)
What prevents you from reaching the wave portal? Too many traps, or too strong opponents?

**Comment by Bertram25** [comment]
> What prevents you from reaching the wave portal? Too many traps, or too strong opponents?

Something straighter than that. ;) You can't claim the wave portal, as you can't pass the yellow north claimed walls, and there are no other entrance. But all this will be solved once the bridges are in. ;)

**Comment by akien-mga** [comment]
> Something straighter than that. ;) You can't claim the wave portal, as you can't pass the yellow north claimed walls, and there are no other entrance. But all this will be solved once the bridges are in. ;)

Ah right I forgot most creatures can't swim :-D

So by removing the small pond in front of the door, it should be possible to break the door and go in, yes? And I should probably add some dirt bridges on the bottom-left and bottom-right sides of the "presqu'île" to be more fair to the seats of the bottom.

BTW, as it's pretty hard to find if you're not familiar with this city, the map was modelled after Lyon ;-)

**Comment by akien-mga** [comment]
> So by removing the small pond in front of the door, it should be possible to break the door and go in, yes?

I can also dig some holes in the wall, it was not meant as a true barrier that would hinder players, but more a ruined wall to set the atmosphere :)

**Pull request merged**
