### PR TITLE
Implementation of server side FOW

### PR DESCRIPTION
**Pull request by hwoarangmy**
Merry christmas everybody ^^

As a christmas gift, here is the PR implementing FOW.
This PR also contains a lot of small fixes / improvements.

Known bugs:
- When an ennemy claims your last visible tile, you loose vision but the tile is still displayed with your color (I will create an issue for that because this commit was big enough) #395 
- Creature vision is not well handled (that's really visible now that it is used for FOW - I will create an issue) #396 
- The not visible tiles are displayed like the visible ones so it's not obvious which tiles you have vision on or not

This needs to be tested well.
Please note that on the 2v2 skirmish test map, I've added a dead creature and an ennemy kobold to see what happens when you loose vision on a kobold carrying a dead corpse.

@Bertram25 Sorry for the big PR to review

@oyvindln Don't hesitate to have a look if you can

@akien-mga As I said, this PR changes the architecture of most of the game so it can introduce regressions nearly everywhere. Please don't hesitate to test it as much as you can ^^

Enjoy ^^

### CODE REVIEW

**Comment by hwoarangmy** [comment]
I've spotted a regression. Because rooms are not sent to clients anymore, the first treasury tile is always shown as free. I will fix that

**Comment by hwoarangmy** [comment]
Room/trap cost preview is fixed ^^

**Comment by Bertram25** [comment]
Wow, Merry Christmas to you too, @hwoarangmy :D :santa: 

I'll try to review all that little by little to make it throughly.

> The not visible tiles are displayed like the visible ones so it's not obvious which tiles you have vision on or not

IMHO, tiles too much away from sight should disappear, and later the surrounding black could be hidden with some distance fog + a sky box. Of course, this is all open to discussion. :)

**Comment by hwoarangmy** [comment]
> IMHO, tiles too much away from sight should disappear, and later the surrounding black could be hidden with some distance fog + a sky box. Of course, this is all open to discussion. :)

Well, IMHO, it is good to let the tile be as it was the last time it has been seen (and easy to do as we just don't have to refresh it). IIRC, that's also how DK handled the tiles. And also how the games I use to play handle things (when you see an ennemy building, you see it until you get vision again even if it has been destroyed during the time you had not vision)

**Comment by Bertram25** [comment]
> Well, IMHO, it is good to let the tile be as it was the last time it has been seen (and easy to do as we just don't have to refresh it). IIRC, that's also how DK handled the tiles. And also how the games I use to play handle things (when you see an ennemy building, you see it until you get vision again even if it has been destroyed during the time you had not vision)

Nevermind my latest comment. I had a full play with the patch and nevermind that. Let's keep the current behaviour. It is quite fine in fact.

I've got a few other comments, hopefully more useful ;)
- When digging, tiles get unselected when they become lava, rock, ground, ... and it's fine. But enemy claimed walls that are undiggable should also get unselected.
- Should we really show rock tiles? IMHO, they easy sell the overall level shape. But that's personal taste of course. What do you think guys?
- Spotted something funny. When your kobolds are digging an area. If you click on the grab workers button, they get in your hand (which is fine), but if they were digging and you don't drop them quickly, you cannot put them back anywhere. You have to grab some other creatures and quicky drop all of them not to be stuck anymore.

Last but not least, this is awesome as it really change the way the game is played now :D

**Comment by hwoarangmy** [comment]
> But enemy claimed walls that are undiggable should also get unselected

I've not paid attention. I will have a look.

> Should we really show rock tiles?

That's what was decided in the corresponding issue. Anyway, we can change that later if we find something better. But IMHO, it is better to use them to show the level shape.

> When your kobolds are digging an area. If you click on the grab workers button, they get in your hand (which is fine), but if they were digging and you don't drop them quickly, you cannot put them back anywhere

I couldn't reproduce that. Is it systematic ? That makes me think that kobolds should not be dropped somewhere you don't have vision on (even if acceptable tile).

**Comment by hwoarangmy** [comment]
I've added a commit to display tiles without sight with a different color. It is not very nice and I couldn't change the claimed tiles to keep their original color.

@Bertram25 since you are more used than me with Ogre, could you have a look or do something once this PR gets merged ?

**Comment by Bertram25** [comment]
> @Bertram25 since you are more used than me with Ogre, could you have a look or do something once this PR gets merged ?

Ok, I've read and I now think understood most of the changes. They are pretty logical and it's a good point. :)
I wonder how network games will behave with vision and such things, and I guess it's the next thing to test. ;) But I do think it should do well as far as I've seen. There is not much added per turn, maybe except for end games.

Now as for colors, I think you're on the right track but I would change a few things to make it look a bit nicer:
- Don't taint rock, water, and lava tiles colors at all. Later, even if there are bridges, we'll simply have to refresh the tile. The vision tainting is IMHO a bad idea for those.
- Don't taint gold and dirt walls, only dirt ground, IMHO. They can simply be refreshed when a creature see them. This would be better looking IMHO and won't spoil the game as far as I tested.
- Enemy tainted claimed walls should have a specific taint to look different from a selected tile. If you have problem with this one, I'll deal with that part after the merge.

Feel free to comment. :) And thanks a lot for the work done on this. This is already another game. :D
Are you ok with the proposed changes?

**Comment by hwoarangmy** [comment]
> Don't taint rock, water, and lava tiles colors at all. Later, even if there are bridges, we'll simply have to refresh the tile. The vision tainting is IMHO a bad idea for those

The goal is to see which tiles ou have vision on or not. When we will have some kind of "fog", it might be easier as there will be no need to taint those tiles. But if you prefer, we can have a try.

> Don't taint gold and dirt walls, only dirt ground, IMHO. They can simply be refreshed when a creature see them. This would be better looking IMHO and won't spoil the game as far as I tested.

ok, why not.

> Enemy tainted claimed walls should have a specific taint to look different from a selected tile. If you have problem with this one, I'll deal with that part after the merge.

The best would be to keep the color so we can see to which enemy claimed tiles you lost vision on belongs to but I couldn't so far. If you want to do it, please do so.

> I wonder how network games will behave with vision and such things, and I guess it's the next thing to test

Yep, once we are done with the PR itself, it should be good to test if sending all the tiles is not too much. Especially on big maps.

**Comment by hwoarangmy** [comment]
I've done as we said. It is less messy like that ^^

**Comment by Bertram25** [comment]
Looks good now. :D Thanks for following my advice. Glad it turned out well. IMHO, it's ready to be merged. I'll let @akien-mga do his usual testing tricks if he has the time to. ;)

**Comment by hwoarangmy** [comment]
I will try to be on IRC tonight. If you have time, we could try a lan to see if it works well with this PR.

**Comment by Bertram25** [comment]
Ok, I can be there on ~9pm. :)
I can stay up to 10-11pm.

It will be cool. ;)

**Comment by hwoarangmy** [comment]
ok. I'll try to catch you as soon as the children are sleeping ^^

**Comment by akien-mga** [comment]
I'm recompiling to get the latest commits and I'll test in the afternoon. I might be around in the evening too, but I can't be 100% sure yet :-)

**Comment by akien-mga** [comment]
I've tested live on Greed or Might, and it works great :-)
I did not notice any huge regression so far, I think we can merge and test the multiplayer in LAN; we'll probably go forward starting from the status created by this PR, more than trying to fine tune everything before we merge it.

**Comment by Bertram25** [comment]
Agreed. But still, it's good to keep the game rather good looking when merging. That's what count I guess IMHO. :)
Eager to see how it will change our play behaviour. ;)

**Comment by Bertram25** [comment]
Btw, if I can reproduce the "can't drop workers" bug tonight, I'll open an issue.
And I'll handle the tainted enemy walls, options menu and GUI layout upgrade in that order. :)

**Comment by akien-mga** [comment]
> But enemy claimed walls that are undiggable should also get unselected.

I'm playing Greed or Might, and since the map is big, all seats usually have the time to claim the walls of most of their domain before the enemy arrives (unless you rush). Now I wonder: if claimed walls are undiggable, how is one supposed to break into a dungeon and kill its enemy?

**Comment by hwoarangmy** [comment]
> how is one supposed to break into a dungeon and kill its enemy

One will have to wait for spells. And there will be one (advanced) that will allow to unclaim ennemy walls (like in DK) ^^

Until then, we should take care, when designing a map, to have common gold that every seat will want

**Comment by akien-mga** [comment]
> One will have to wait for spells. And there will be one (advanced) that will allow to unclaim ennemy walls (like in DK) ^^
> 
> Until then, we should take care, when designing a map, to have common gold that every seat will want

Ok that sounds good. So Greed or Might is not really skirmish-ready yet, it's too big. In multiplayer it might be alright, since human players will want to attack their foes, so they will create breaches in their walls anyway.

**Comment by Bertram25** [comment]
Yeah, btw, workers will only spawn after a spell, too. :)

**Comment by hwoarangmy** [comment]
> Ok that sounds good. So Greed or Might is not really skirmish-ready yet, it's too big

The thing is that at somepoint, the AI will have too many gold and will stop looking for more (when it gots 20000 with full treasuries).
When the game will be more advanced, with creatures wanting to get paid, gold will decrease automatically and AI won't stop looking for it.

**Pull request merged**
